rpg_data = [
    {"text": "Exploring the vast world of Skyrim with a sword in hand", "expected_label": "rpg"},
    {"text": "Choosing dialogue options to shape the story in The Witcher 3", "expected_label": "rpg"},
    {"text": "Embarking on an epic journey through the wasteland in Fallout 4", "expected_label": "rpg"},
    {"text": "Building relationships with party members in Dragon Age: Inquisition", "expected_label": "rpg"},
    {"text": "Leveling up my character in Dark Souls III", "expected_label": "rpg"},
    {"text": "Crafting powerful potions in Divinity: Original Sin 2", "expected_label": "rpg"},
    {"text": "Managing a squad of heroes in Baldur's Gate 3", "expected_label": "rpg"},
    {"text": "Exploring dungeons and looting treasure in Pillars of Eternity", "expected_label": "rpg"},
    {"text": "Battling dragons in Neverwinter Nights", "expected_label": "rpg"},
    {"text": "Making moral choices in Mass Effect that affect my story", "expected_label": "rpg"},
    {"text": "Exploring a rich fantasy world in Final Fantasy XV", "expected_label": "rpg"},
    {"text": "Uncovering ancient secrets in The Elder Scrolls IV: Oblivion", "expected_label": "rpg"},
    {"text": "Crafting armor and weapons in Monster Hunter: World", "expected_label": "rpg"},
    {"text": "Journeying through a fantastical realm in Xenoblade Chronicles", "expected_label": "rpg"},
    {"text": "Becoming a vampire lord in The Elder Scrolls V: Skyrim", "expected_label": "rpg"},
    {"text": "Role-playing a post-apocalyptic survivor in Fallout: New Vegas", "expected_label": "rpg"},
    {"text": "Solving quests and fighting enemies in Gothic II", "expected_label": "rpg"},
    {"text": "Building my own settlement in Fallout 76", "expected_label": "rpg"},
    {"text": "Exploring the futuristic dystopia of Cyberpunk 2077", "expected_label": "rpg"},
    {"text": "Saving the kingdom in Kingdom Come: Deliverance", "expected_label": "rpg"},
    {"text": "Collecting legendary items in Diablo III", "expected_label": "rpg"},
    {"text": "Taming monsters in Ni no Kuni: Wrath of the White Witch", "expected_label": "rpg"},
    {"text": "Fighting colossal bosses in Dragon's Dogma: Dark Arisen", "expected_label": "rpg"},
    {"text": "Exploring the open world of The Legend of Zelda: Breath of the Wild", "expected_label": "rpg"},
    {"text": "Embarking on a quest to find the Holy Grail in King Arthur: Knight's Tale", "expected_label": "rpg"},
    {"text": "Interacting with villagers in The Legend of Heroes: Trails of Cold Steel", "expected_label": "rpg"},
    {"text": "Traveling through the planes in Planescape: Torment", "expected_label": "rpg"},
    {"text": "Fighting dark forces in Shadowrun Returns", "expected_label": "rpg"},
    {"text": "Completing epic story missions in Guild Wars 2", "expected_label": "rpg"},
    {"text": "Engaging in strategic battles in Fire Emblem: Three Houses", "expected_label": "rpg"},
    {"text": "Exploring dungeons with a group in Torchlight II", "expected_label": "rpg"},
    {"text": "Customizing my character in Dragon Quest XI", "expected_label": "rpg"},
    {"text": "Exploring a sci-fi universe in Star Wars: Knights of the Old Republic", "expected_label": "rpg"},
    {"text": "Building a town in Ni no Kuni II: Revenant Kingdom", "expected_label": "rpg"},
    {"text": "Creating spells in Magicka", "expected_label": "rpg"},
    {"text": "Battling creatures in Pathfinder: Kingmaker", "expected_label": "rpg"},
    {"text": "Exploring forgotten ruins in The Bard's Tale IV", "expected_label": "rpg"},
    {"text": "Wielding powerful magic in Fable III", "expected_label": "rpg"},
    {"text": "Battling evil forces in Dark Messiah of Might & Magic", "expected_label": "rpg"},
    {"text": "Fighting corrupted creatures in GreedFall", "expected_label": "rpg"},
    {"text": "Becoming a legendary hero in Sacred 2: Fallen Angel", "expected_label": "rpg"},
    {"text": "Surviving in a gothic horror setting in Bloodborne", "expected_label": "rpg"},
    {"text": "Managing a hero's path in Mount & Blade II: Bannerlord", "expected_label": "rpg"},
    {"text": "Recruiting companions in Wasteland 3", "expected_label": "rpg"},
    {"text": "Embarking on an epic adventure in Tales of Arise", "expected_label": "rpg"},
    {"text": "Solving mysteries and puzzles in Risen", "expected_label": "rpg"},
    {"text": "Joining guilds and factions in The Elder Scrolls III: Morrowind", "expected_label": "rpg"},
    {"text": "Exploring the wonders of Amalur in Kingdoms of Amalur: Re-Reckoning", "expected_label": "rpg"},
    {"text": "Fighting beasts with a cursed arm in Sekiro: Shadows Die Twice", "expected_label": "rpg"},
    {"text": "Forging alliances in The Outer Worlds", "expected_label": "rpg"},
    {"text": "Venturing into dark forests in Grim Dawn", "expected_label": "rpg"},
    {"text": "Making choices that change the outcome in Vampire: The Masquerade – Bloodlines", "expected_label": "rpg"},
    {"text": "Exploring the galaxy with a crew in Starbound", "expected_label": "rpg"},
    {"text": "Battling giant monsters in Dragon Quest Builders 2", "expected_label": "rpg"},
    {"text": "Creating your destiny in Divinity: Dragon Commander", "expected_label": "rpg"},
    {"text": "Engaging in turn-based combat in Octopath Traveler", "expected_label": "rpg"},
    {"text": "Recruiting adventurers in Darkest Dungeon", "expected_label": "rpg"},
    {"text": "Saving the kingdom in Dragon Quest VIII: Journey of the Cursed King", "expected_label": "rpg"},
    {"text": "Defeating dark mages in Gothic 3", "expected_label": "rpg"},
    {"text": "Exploring the rich lore in Pillars of Eternity II: Deadfire", "expected_label": "rpg"},
    {"text": "Fighting against evil in the fantasy world of Arcanum: Of Steamworks and Magick Obscura", "expected_label": "rpg"},
    {"text": "Surviving in a bleak post-nuclear future in Underrail", "expected_label": "rpg"},
    {"text": "Managing resources in Kenshi", "expected_label": "rpg"},
    {"text": "Navigating the politics of a magical academy in SpellForce 3", "expected_label": "rpg"},
    {"text": "Fighting in ancient China in Jade Empire", "expected_label": "rpg"},
    {"text": "Exploring mysterious caves in Etrian Odyssey", "expected_label": "rpg"},
    {"text": "Role-playing as a hero in Albion in Fable II", "expected_label": "rpg"},
    {"text": "Becoming a monster hunter in The Witcher", "expected_label": "rpg"},
    {"text": "Creating potions and exploring the world in Alchemy Story", "expected_label": "rpg"},
    {"text": "Leading a group of adventurers in Might & Magic VII: For Blood and Honor", "expected_label": "rpg"},
    {"text": "Fighting in massive battles in The Banner Saga", "expected_label": "rpg"},
    {"text": "Exploring a rich, open world in Horizon Zero Dawn", "expected_label": "rpg"},
    {"text": "Fighting through countless dungeons in Wizardry VIII", "expected_label": "rpg"},
    {"text": "Recruiting heroes to save a kingdom in Grandia II", "expected_label": "rpg"},
    {"text": "Exploring an alternative world in Shin Megami Tensei III: Nocturne", "expected_label": "rpg"},
    {"text": "Battling with powerful skills in Chrono Cross", "expected_label": "rpg"},
    {"text": "Playing as a lone wanderer in The Sinking City", "expected_label": "rpg"},
    {"text": "Surviving in the deep space RPG Star Traders: Frontiers", "expected_label": "rpg"},
    {"text": "Uncovering the secrets of magic in Tyranny", "expected_label": "rpg"},
    {"text": "Leading a group of exiles in Pyre", "expected_label": "rpg"},
    {"text": "Becoming the hero of Albion in Fable Anniversary", "expected_label": "rpg"},
    {"text": "Fighting off the infected in The Last Stand: Aftermath", "expected_label": "rpg"},
    {"text": "Crafting my own spells in Spellcaster University", "expected_label": "rpg"},
    {"text": "Managing a farm in a magical land in Kynseed", "expected_label": "rpg"},
    {"text": "Exploring dungeons in Legend of Grimrock", "expected_label": "rpg"},
    {"text": "Battling mystical enemies in Trials of Mana", "expected_label": "rpg"},
    {"text": "Choosing my path as a Jedi in Star Wars: The Old Republic", "expected_label": "rpg"},
    {"text": "Fighting mythical creatures in Odin Sphere", "expected_label": "rpg"},
    {"text": "Building an adventure team in Children of Morta", "expected_label": "rpg"},
    {"text": "Exploring a haunted village in Koudelka", "expected_label": "rpg"},
    {"text": "Fighting dragons in Dragon's Dogma Online", "expected_label": "rpg"},
    {"text": "Navigating a cyberpunk world in Shadowrun: Dragonfall", "expected_label": "rpg"},
    {"text": "Building a powerful deck of spells in Slay the Spire", "expected_label": "rpg"},
    {"text": "Joining and managing different factions in Outward", "expected_label": "rpg"},
    {"text": "Exploring an alien world in Beyond Good & Evil", "expected_label": "rpg"},
    {"text": "Fighting against a corrupt empire in Tyranny", "expected_label": "rpg"},
    {"text": "Embarking on an adventure in Atelier Ryza", "expected_label": "rpg"},
    {"text": "Playing as a samurai in a fantasy Japan in Nioh", "expected_label": "rpg"},
    {"text": "Building and expanding my own settlement in Rune Factory 5", "expected_label": "rpg"},
    {"text": "Exploring a dark fantasy world in Salt and Sanctuary", "expected_label": "rpg"},
    {"text": "Choosing the fate of my companions in Mass Effect 2", "expected_label": "rpg"},
    {"text": "Crafting magical spells to defeat monsters in The Witcher 2", "expected_label": "rpg"},
    {"text": "Exploring the open fields of Hyrule in Zelda: Breath of the Wild", "expected_label": "rpg"},
    {"text": "Embarking on an adventure to save the world in Secret of Mana", "expected_label": "rpg"},
    {"text": "Fighting gods and mythological creatures in God of War", "expected_label": "rpg"},
    {"text": "Making tough choices that shape the storyline in Dragon Age: Origins", "expected_label": "rpg"},
    {"text": "Exploring distant planets in Mass Effect: Andromeda", "expected_label": "rpg"},
    {"text": "Navigating through a world filled with spirits in Ni no Kuni II", "expected_label": "rpg"},
    {"text": "Embarking on an epic quest in Final Fantasy VII Remake", "expected_label": "rpg"},
    {"text": "Uncovering hidden treasures in Tales of Vesperia", "expected_label": "rpg"},
    {"text": "Venturing into haunted dungeons in Dark Souls II", "expected_label": "rpg"},
    {"text": "Developing alchemy skills in Atelier Sophie", "expected_label": "rpg"},
    {"text": "Saving the world from an ancient evil in Persona 5", "expected_label": "rpg"},
    {"text": "Training to become a hero in Dragon Quest IX", "expected_label": "rpg"},
    {"text": "Unraveling the mysteries of a fantasy kingdom in Fable Anniversary", "expected_label": "rpg"},
    {"text": "Exploring the dream-like landscapes of Lost Sphear", "expected_label": "rpg"},
    {"text": "Taming dragons and riding them in Drakan: The Ancients' Gates", "expected_label": "rpg"},
    {"text": "Joining various guilds to complete tasks in Skyrim", "expected_label": "rpg"},
    {"text": "Exploring cursed islands in Risen 2: Dark Waters", "expected_label": "rpg"},
    {"text": "Battling dark forces while building relationships in Fire Emblem: Awakening", "expected_label": "rpg"},
    {"text": "Traveling between dimensions in Radiant Historia", "expected_label": "rpg"},
    {"text": "Gathering resources and crafting items in RuneScape", "expected_label": "rpg"},
    {"text": "Fighting in the dark underworld of Baldur's Gate", "expected_label": "rpg"},
    {"text": "Journeying across the vast land of Tamriel in The Elder Scrolls Online", "expected_label": "rpg"},
    {"text": "Unlocking special abilities in Final Fantasy XIII", "expected_label": "rpg"},
    {"text": "Defeating mythical creatures in Ys VIII: Lacrimosa of Dana", "expected_label": "rpg"},
    {"text": "Exploring floating continents in Skies of Arcadia", "expected_label": "rpg"},
    {"text": "Building a farm while completing quests in Stardew Valley", "expected_label": "rpg"},
    {"text": "Battling monsters while following a story in Xenogears", "expected_label": "rpg"},
    {"text": "Rescuing a kidnapped family member in Fallout 4", "expected_label": "rpg"},
    {"text": "Exploring a demon-infested Tokyo in Shin Megami Tensei V", "expected_label": "rpg"},
    {"text": "Restoring light to the land in Child of Light", "expected_label": "rpg"},
    {"text": "Fighting monsters and crafting gear in Monster Hunter Rise", "expected_label": "rpg"},
    {"text": "Resurrecting a fallen hero in Dragon's Crown", "expected_label": "rpg"},
    {"text": "Becoming a legendary witcher in The Witcher: Wild Hunt", "expected_label": "rpg"},
    {"text": "Helping villagers in trouble in Ni no Kuni: Wrath of the White Witch", "expected_label": "rpg"},
    {"text": "Exploring ancient ruins in Octopath Traveler", "expected_label": "rpg"},
    {"text": "Mastering sword techniques in Ys Origin", "expected_label": "rpg"},
    {"text": "Solving puzzles in a fantasy world in The Legend of Heroes: Trails in the Sky", "expected_label": "rpg"},
    {"text": "Exploring a magical world in I Am Setsuna", "expected_label": "rpg"},
    {"text": "Fighting alongside my party in Persona 4 Golden", "expected_label": "rpg"},
    {"text": "Collecting loot in a procedurally-generated dungeon in Torchlight III", "expected_label": "rpg"},
    {"text": "Training Pokémon to become a master in Pokémon Sword and Shield", "expected_label": "rpg"},
    {"text": "Seeking revenge in a dark fantasy setting in Bloodborne", "expected_label": "rpg"},
    {"text": "Defending my kingdom from evil in Trials of Mana", "expected_label": "rpg"},
    {"text": "Becoming the chosen savior of the universe in Xenoblade Chronicles 2", "expected_label": "rpg"},
    {"text": "Forging legendary weapons in Kingdoms of Amalur", "expected_label": "rpg"},
    {"text": "Embarking on a dangerous journey in The Surge 2", "expected_label": "rpg"},
    {"text": "Reclaiming my throne in Nioh 2", "expected_label": "rpg"},
    {"text": "Battling gods and demons in Shin Megami Tensei III: Nocturne", "expected_label": "rpg"},
    {"text": "Restoring peace to the land in Legend of Mana", "expected_label": "rpg"},
    {"text": "Learning the secrets of an ancient world in Horizon Forbidden West", "expected_label": "rpg"},
    {"text": "Creating potions and charms in Atelier Ryza 2", "expected_label": "rpg"},
    {"text": "Fighting fierce warriors in Final Fantasy XVI", "expected_label": "rpg"},
    {"text": "Embarking on an epic journey in Dragon Age II", "expected_label": "rpg"},
    {"text": "Exploring the deep forests of Eorzea in Final Fantasy XIV", "expected_label": "rpg"},
    {"text": "Taking on a great evil in Phantasy Star Online 2", "expected_label": "rpg"},
    {"text": "Battling through corrupted lands in Code Vein", "expected_label": "rpg"},
    {"text": "Leading an army to victory in Fire Emblem: Path of Radiance", "expected_label": "rpg"},
    {"text": "Defending against demonic threats in Dragon's Dogma", "expected_label": "rpg"},
    {"text": "Exploring an alien planet in Star Ocean: The Last Hope", "expected_label": "rpg"},
    {"text": "Protecting a kingdom from dark forces in The Last Remnant", "expected_label": "rpg"},
    {"text": "Engaging in turn-based battles in Persona 3", "expected_label": "rpg"},
    {"text": "Gathering allies in Tales of Symphonia", "expected_label": "rpg"},
    {"text": "Fighting powerful bosses in Elden Ring", "expected_label": "rpg"},
    {"text": "Recruiting characters with unique skills in Suikoden II", "expected_label": "rpg"},
    {"text": "Making choices that change the story in Vampyr", "expected_label": "rpg"},
    {"text": "Defeating the dark lord in Eternal Sonata", "expected_label": "rpg"},
    {"text": "Exploring the mystical lands of Erion in Odin Sphere", "expected_label": "rpg"},
    {"text": "Protecting my kingdom in Dragon Quest Builders", "expected_label": "rpg"},
    {"text": "Exploring deep dungeons in Wizardry: Labyrinth of Lost Souls", "expected_label": "rpg"},
    {"text": "Navigating a magical post-apocalyptic world in Fallout Tactics", "expected_label": "rpg"},
    {"text": "Becoming the ultimate hero in Heroes of Might and Magic V", "expected_label": "rpg"},
    {"text": "Uncovering the secrets of an underwater city in BioShock", "expected_label": "rpg"},
    {"text": "Saving my home world in Ni no Kuni: Cross Worlds", "expected_label": "rpg"},
    {"text": "Exploring the fantasy lands in Pathfinder: Wrath of the Righteous", "expected_label": "rpg"},
    {"text": "Forging alliances in the vast world of Horizon Zero Dawn", "expected_label": "rpg"},
    {"text": "Fighting terrifying monsters in Tales of Zestiria", "expected_label": "rpg"},
    {"text": "Hunting powerful dragons in Capcom's Monster Hunter Stories", "expected_label": "rpg"},
    {"text": "Raising an army to fight evil in Langrisser I & II", "expected_label": "rpg"},
    {"text": "Exploring the secrets of a lost civilization in Ys IX: Monstrum Nox", "expected_label": "rpg"},
    {"text": "Managing my estate while battling dark forces in Darkest Dungeon II", "expected_label": "rpg"},
    {"text": "Uncovering conspiracies in the steampunk world of SteamWorld Quest", "expected_label": "rpg"},
    {"text": "Becoming a champion of legend in Dragon's Crown Pro", "expected_label": "rpg"},
    {"text": "Navigating a fractured world in Bravely Default II", "expected_label": "rpg"},
    {"text": "Engaging in political intrigue in Suikoden V", "expected_label": "rpg"},
    {"text": "Defending humanity from dark forces in Champions of Norrath", "expected_label": "rpg"},
    {"text": "Building and defending my village in Two Worlds II", "expected_label": "rpg"},
    {"text": "Seeking revenge for my people in Shadow Hearts", "expected_label": "rpg"},
    {"text": "Managing a team of explorers in Legends of Amberland", "expected_label": "rpg"},
    {"text": "Resurrecting the lost souls of heroes in Labyrinth of Refrain", "expected_label": "rpg"},
    {"text": "Exploring a sprawling metropolis in CyberConnect2's Fugue on the Battlefield", "expected_label": "rpg"},
    {"text": "Battling through a storm-ravaged world in Stormblood (Final Fantasy XIV expansion)", "expected_label": "rpg"},
    {"text": "Exploring dark caverns in Grim Dawn", "expected_label": "rpg"},
    {"text": "Restoring order to the galaxy in Knights of the Old Republic II", "expected_label": "rpg"},
    {"text": "Solving complex puzzles in The Temple of Elemental Evil", "expected_label": "rpg"},
    {"text": "Navigating time travel and saving timelines in Radiant Historia: Perfect Chronology", "expected_label": "rpg"},
    {"text": "Saving the digital world in Digimon Story: Cyber Sleuth", "expected_label": "rpg"},
    {"text": "Exploring a mysterious island in Blue Reflection", "expected_label": "rpg"},
    {"text": "Building alliances in the fantasy world of Nioh", "expected_label": "rpg"},
    {"text": "Navigating a morally complex storyline in The Witcher 3", "expected_label": "rpg"},
    {"text": "Rescuing villagers from a deadly plague in Dragon Age: Inquisition", "expected_label": "rpg"},
    {"text": "Managing character relationships in Mass Effect 3", "expected_label": "rpg"},
    {"text": "Exploring an open world filled with secrets in Elden Ring", "expected_label": "rpg"},
    {"text": "Forging alliances to prevent war in Baldur's Gate III", "expected_label": "rpg"},
    {"text": "Mastering the power of the Force in Star Wars: Knights of the Old Republic", "expected_label": "rpg"},
    {"text": "Saving my soul from the dark in Dark Souls III", "expected_label": "rpg"},
    {"text": "Fighting my way through hordes of monsters in Dragon Quest XI", "expected_label": "rpg"},
    {"text": "Exploring a world inspired by Norse mythology in God of War: Ragnarok", "expected_label": "rpg"},
    {"text": "Training to become a Pokémon Champion in Pokémon Scarlet and Violet", "expected_label": "rpg"},
    {"text": "Protecting the magical land of Faerûn in Baldur's Gate II", "expected_label": "rpg"},
    {"text": "Solving a mystery while traveling through time in Chrono Trigger", "expected_label": "rpg"},
    {"text": "Fighting dragons and demons in Tales of Berseria", "expected_label": "rpg"},
    {"text": "Defending against Viking invasions in Assassin's Creed: Valhalla", "expected_label": "rpg"},
    {"text": "Combining my magic abilities to battle monsters in Dragon's Dogma", "expected_label": "rpg"},
    {"text": "Building relationships with NPCs in Persona 4", "expected_label": "rpg"},
    {"text": "Fighting enemies and making decisions that shape the world in Fallout: New Vegas", "expected_label": "rpg"},
    {"text": "Saving a magical world in Octopath Traveler II", "expected_label": "rpg"},
    {"text": "Fighting in strategic battles in Fire Emblem: Three Houses", "expected_label": "rpg"},
    {"text": "Training and battling Digimon in Digimon World", "expected_label": "rpg"},
    {"text": "Exploring the magical world of Azeroth in World of Warcraft", "expected_label": "rpg"},
    {"text": "Navigating multiple storylines in Radiata Stories", "expected_label": "rpg"},
    {"text": "Defending against dark wizards in Ni no Kuni: Cross Worlds", "expected_label": "rpg"},
    {"text": "Creating a village while completing quests in Dragon Quest Builders 2", "expected_label": "rpg"},
    {"text": "Traveling across a galaxy far, far away in Star Wars: The Old Republic", "expected_label": "rpg"},
    {"text": "Saving my kingdom from ruin in Final Fantasy IX", "expected_label": "rpg"},
    {"text": "Mastering different combat classes in Xenoblade Chronicles X", "expected_label": "rpg"},
    {"text": "Exploring medieval lands in Kingdom Come: Deliverance", "expected_label": "rpg"},
    {"text": "Saving the universe in Phantasy Star IV", "expected_label": "rpg"},
    {"text": "Rescuing allies in a post-apocalyptic world in Wasteland 3", "expected_label": "rpg"},
    {"text": "Building alliances in the dark world of Tyranny", "expected_label": "rpg"},
    {"text": "Exploring a kingdom overrun by darkness in Ys VI: The Ark of Napishtim", "expected_label": "rpg"},
    {"text": "Exploring a vast cyberpunk city in Shadowrun: Dragonfall", "expected_label": "rpg"},
    {"text": "Saving my people in Star Ocean: Integrity and Faithlessness", "expected_label": "rpg"},
    {"text": "Solving mysteries in a world of magic in Thief of Thieves", "expected_label": "rpg"},
    {"text": "Engaging in turn-based battles in Octopath Traveler II", "expected_label": "rpg"},
    {"text": "Learning the ancient language of runes in Lost Kingdoms", "expected_label": "rpg"},
    {"text": "Navigating the politics of a divided kingdom in Tactics Ogre: Reborn", "expected_label": "rpg"},
    {"text": "Exploring an ancient world filled with mysteries in Bravely Second: End Layer", "expected_label": "rpg"},
    {"text": "Solving puzzles and defeating enemies in The Legend of Heroes: Trails of Azure", "expected_label": "rpg"},
    {"text": "Exploring different realms in Tales of Xillia", "expected_label": "rpg"},
    {"text": "Defending against dark magic in Vagrant Story", "expected_label": "rpg"},
    {"text": "Exploring a magical city in White Knight Chronicles", "expected_label": "rpg"},
    {"text": "Becoming a hero in Champions of Norrath", "expected_label": "rpg"},
    {"text": "Building a community in the wilderness in Kenshi", "expected_label": "rpg"},
    {"text": "Traveling to another dimension in CrossCode", "expected_label": "rpg"},
    {"text": "Battling in a medieval fantasy setting in Kingdoms of Amalur: Re-Reckoning", "expected_label": "rpg"},
    {"text": "Saving a magical land from darkness in Blue Reflection: Second Light", "expected_label": "rpg"},
    {"text": "Mastering ancient combat styles in Nioh", "expected_label": "rpg"},
    {"text": "Solving mysteries in the dark lands of Indivisible", "expected_label": "rpg"},
    {"text": "Battling other players in a medieval setting in Gloria Victis", "expected_label": "rpg"},
    {"text": "Navigating the dangers of the Shattered Isles in Dauntless", "expected_label": "rpg"},
    {"text": "Becoming a magical creature in Mutant Year Zero", "expected_label": "rpg"},
    {"text": "Saving the elves in the forest of Ljosalfheimr in Ragnarok Odyssey", "expected_label": "rpg"},
    {"text": "Fulfilling prophecies in Divinity: Original Sin 2", "expected_label": "rpg"},
    {"text": "Exploring a ruined world in Horizon Zero Dawn", "expected_label": "rpg"},
    {"text": "Exploring alien technology in Mass Effect: Andromeda", "expected_label": "rpg"},
    {"text": "Learning about the lost civilization of Atlantis in Assassin's Creed: Odyssey", "expected_label": "rpg"},
    {"text": "Joining guilds to earn rewards in The Elder Scrolls III: Morrowind", "expected_label": "rpg"},
    {"text": "Rescuing villagers and rebuilding settlements in Fable II", "expected_label": "rpg"},
    {"text": "Building a party of diverse heroes in Pathfinder: Kingmaker", "expected_label": "rpg"},
    {"text": "Exploring a post-apocalyptic future in Fallout 3", "expected_label": "rpg"},
    {"text": "Solving puzzles and fighting foes in the Labyrinth in Persona 5 Strikers", "expected_label": "rpg"},
    {"text": "Exploring the high fantasy world of Tamriel in The Elder Scrolls V: Skyrim", "expected_label": "rpg"},
    {"text": "Learning alchemy to craft potions in Atelier Rorona", "expected_label": "rpg"},
    {"text": "Helping villagers with tasks in Ni no Kuni: Revenant Kingdom", "expected_label": "rpg"},
    {"text": "Journeying across the continent in Dragon Quest VIII", "expected_label": "rpg"},
    {"text": "Navigating time loops in The Forgotten City", "expected_label": "rpg"},
    {"text": "Creating my own character in Dragon Ball Z: Kakarot", "expected_label": "rpg"},
    {"text": "Fighting monsters with my squad in Phantasy Star Online", "expected_label": "rpg"},
    {"text": "Recruiting party members in The Legend of Heroes: Trails of Cold Steel", "expected_label": "rpg"},
    {"text": "Battling demons and monsters in Shin Megami Tensei IV", "expected_label": "rpg"},
    {"text": "Exploring dark dungeons in Neverwinter Nights", "expected_label": "rpg"},
    {"text": "Finding my lost sister in Atelier Lulua", "expected_label": "rpg"},
    {"text": "Forging a blade to take down a dragon in Dragon Slayer", "expected_label": "rpg"},
    {"text": "Exploring a steampunk world in SteamWorld Heist", "expected_label": "rpg"},
    {"text": "Navigating the war-torn lands of Gliea in Valkyria Chronicles", "expected_label": "rpg"},
    {"text": "Taking on mythical enemies in Valkyrie Profile", "expected_label": "rpg"},
    {"text": "Traveling through time to rescue a lost world in Blue Dragon", "expected_label": "rpg"},
    {"text": "Fighting to save a cursed city in Dark Souls Remastered", "expected_label": "rpg"},
    {"text": "Embarking on an adventure across space in Rogue Galaxy", "expected_label": "rpg"},
    {"text": "Exploring the secrets of the ocean in Endless Ocean", "expected_label": "rpg"},
    {"text": "Engaging in epic boss fights in Xenoblade Chronicles 3", "expected_label": "rpg"},
    {"text": "Discovering lost artifacts in Arc the Lad", "expected_label": "rpg"},
    {"text": "Becoming the ruler of an ancient city in Pillars of Eternity", "expected_label": "rpg"},
    {"text": "Forging alliances with powerful warriors in Mount & Blade II: Bannerlord", "expected_label": "rpg"},
    {"text": "Rescuing the citizens of Albion in Fable III", "expected_label": "rpg"},
    {"text": "Engaging in political conflicts in Ogre Battle 64", "expected_label": "rpg"},
    {"text": "Navigating a dystopian world in Children of Morta", "expected_label": "rpg"},
    {"text": "Uncovering hidden secrets in Cosmic Star Heroine", "expected_label": "rpg"},
    {"text": "Seeking revenge for my fallen comrades in Tales of Arise", "expected_label": "rpg"},
    {"text": "Saving my world from the forces of darkness in Final Fantasy Crystal Chronicles", "expected_label": "rpg"},
    {"text": "Exploring the magical land of Lemuria in Child of Light", "expected_label": "rpg"},
    {"text": "Exploring dangerous islands in Ys IX: Monstrum Nox", "expected_label": "rpg"},
    {"text": "Exploring the wild lands of Skyrim", "expected_label": "rpg"},
    {"text": "Choosing dialogue options to influence the story in The Witcher 3", "expected_label": "rpg"},
    {"text": "Building my character and leveling up in Final Fantasy XV", "expected_label": "rpg"},
    {"text": "Traveling across the multiverse in Octopath Traveler", "expected_label": "rpg"},
    {"text": "Joining the Grey Wardens to stop the Blight in Dragon Age: Origins", "expected_label": "rpg"},
    {"text": "Forming alliances with kings and wizards in Baldur's Gate", "expected_label": "rpg"},
    {"text": "Saving the world from an ancient evil in Legend of Heroes", "expected_label": "rpg"},
    {"text": "Venturing into the dark dungeons in Darkest Dungeon", "expected_label": "rpg"},
    {"text": "Mastering the arts of combat in Dark Souls III", "expected_label": "rpg"},
    {"text": "Fighting my way through hordes of enemies in Xenoblade Chronicles", "expected_label": "rpg"},
    {"text": "Exploring the vast kingdom of Hyrule in Zelda: Breath of the Wild", "expected_label": "rpg"},
    {"text": "Developing relationships with my party members in Persona 5", "expected_label": "rpg"},
    {"text": "Navigating political plots and conflicts in Fire Emblem: Three Houses", "expected_label": "rpg"},
    {"text": "Saving my village from a curse in Tales of Berseria", "expected_label": "rpg"},
    {"text": "Collecting legendary weapons to fight an evil lord in Chrono Trigger", "expected_label": "rpg"},
    {"text": "Exploring the world of Ivalice in Final Fantasy XII", "expected_label": "rpg"},
    {"text": "Solving ancient puzzles in Breath of Fire III", "expected_label": "rpg"},
    {"text": "Joining a secret guild in Divinity: Original Sin II", "expected_label": "rpg"},
    {"text": "Mastering the different job classes in Bravely Default", "expected_label": "rpg"},
    {"text": "Exploring a post-apocalyptic wasteland in Fallout: New Vegas", "expected_label": "rpg"},
    {"text": "Engaging in combat with mystical creatures in Dragon's Dogma", "expected_label": "rpg"},
    {"text": "Revisiting my past to change the future in Radiant Historia", "expected_label": "rpg"},
    {"text": "Rescuing villagers from monsters in Ni no Kuni II: Revenant Kingdom", "expected_label": "rpg"},
    {"text": "Exploring a futuristic world in Phantasy Star Online 2", "expected_label": "rpg"},
    {"text": "Fighting hordes of demons in Shin Megami Tensei III: Nocturne", "expected_label": "rpg"},
    {"text": "Leading a rebellion against an oppressive empire in Suikoden V", "expected_label": "rpg"},
    {"text": "Helping spirits find peace in Atelier Ryza", "expected_label": "rpg"},
    {"text": "Saving a kingdom under threat in Ys IX: Monstrum Nox", "expected_label": "rpg"},
    {"text": "Engaging in tactical battles with monsters in Disgaea: Hour of Darkness", "expected_label": "rpg"},
    {"text": "Building my village and defending it from attacks in Dark Cloud", "expected_label": "rpg"},
    {"text": "Solving puzzles to uncover the past in Golden Sun: The Lost Age", "expected_label": "rpg"},
    {"text": "Recruiting legendary warriors to fight evil in Fire Emblem: Awakening", "expected_label": "rpg"},
    {"text": "Restoring the balance of magic in Tales of Graces f", "expected_label": "rpg"},
    {"text": "Leading an army against dark forces in Shining Force II", "expected_label": "rpg"},
    {"text": "Navigating the dangerous world of magic in Enchanted Arms", "expected_label": "rpg"},
    {"text": "Exploring underwater realms in Aquaria", "expected_label": "rpg"},
    {"text": "Traveling between dimensions in Legend of Dragoon", "expected_label": "rpg"},
    {"text": "Finding lost relics in Arc the Lad II", "expected_label": "rpg"},
    {"text": "Restoring my clan's honor in Sekiro: Shadows Die Twice", "expected_label": "rpg"},
    {"text": "Fighting for survival in an apocalyptic world in Horizon Zero Dawn", "expected_label": "rpg"},
    {"text": "Recruiting heroes to fight against the shadows in Wild Arms", "expected_label": "rpg"},
    {"text": "Exploring a dark, haunting world in Bloodborne", "expected_label": "rpg"},
    {"text": "Battling fierce enemies in The Last Remnant", "expected_label": "rpg"},
    {"text": "Joining a magical academy in Atelier Firis", "expected_label": "rpg"},
    {"text": "Choosing my faction in a war-torn world in The Banner Saga", "expected_label": "rpg"},
    {"text": "Solving mysteries in a cursed city in Vampyr", "expected_label": "rpg"},
    {"text": "Embarking on a grand adventure in Rogue Galaxy", "expected_label": "rpg"},
    {"text": "Forging alliances in The Technomancer", "expected_label": "rpg"},
    {"text": "Exploring a mythical forest in Secret of Mana", "expected_label": "rpg"},
    {"text": "Training my character in the ways of magic in Risen 3", "expected_label": "rpg"},
    {"text": "Defeating powerful creatures to save the kingdom in Trials of Mana", "expected_label": "rpg"},
    {"text": "Fighting for freedom against an empire in Valkyria Chronicles", "expected_label": "rpg"},
    {"text": "Engaging in magical duels in The Legend of Heroes: Trails of Cold Steel III", "expected_label": "rpg"},
    {"text": "Restoring balance in the kingdom of Eos in Final Fantasy XV", "expected_label": "rpg"},
    {"text": "Defeating evil overlords in Fairy Tail RPG", "expected_label": "rpg"},
    {"text": "Exploring a haunted mansion in The House in Fata Morgana", "expected_label": "rpg"},
    {"text": "Crafting magical items to help my village in Atelier Sophie", "expected_label": "rpg"},
    {"text": "Battling giant colossi in Dragon's Crown Pro", "expected_label": "rpg"},
    {"text": "Rescuing heroes trapped in time in Eternal Sonata", "expected_label": "rpg"},
    {"text": "Exploring a desolate future in Xenoblade Chronicles X", "expected_label": "rpg"},
    {"text": "Building my own empire in SpellForce 3", "expected_label": "rpg"},
    {"text": "Navigating the multiverse in CrossCode", "expected_label": "rpg"},
    {"text": "Fighting against ancient gods in Shin Megami Tensei: Strange Journey", "expected_label": "rpg"},
    {"text": "Saving the world from chaos in Alundra", "expected_label": "rpg"},
    {"text": "Uncovering secrets of an ancient order in Vagrant Story", "expected_label": "rpg"},
    {"text": "Exploring the remnants of a fallen civilization in NieR: Automata", "expected_label": "rpg"},
    {"text": "Traveling to the astral realm in Atelier Lulua", "expected_label": "rpg"},
    {"text": "Fighting dark creatures in Tokyo Xanadu", "expected_label": "rpg"},
    {"text": "Rescuing captured allies in The Witch and the Hundred Knight", "expected_label": "rpg"},
    {"text": "Solving time-travel mysteries in Radiant Historia: Perfect Chronology", "expected_label": "rpg"},
    {"text": "Navigating the mysterious lands of Bastion", "expected_label": "rpg"},
    {"text": "Saving the world from an alien invasion in Cosmic Star Heroine", "expected_label": "rpg"},
    {"text": "Exploring a sunken city in Darkest Dungeon 2", "expected_label": "rpg"},
    {"text": "Forging powerful weapons in The Surge", "expected_label": "rpg"},
    {"text": "Mastering martial arts to defeat enemies in Yakuza: Like a Dragon", "expected_label": "rpg"},
    {"text": "Exploring the celestial realms in Grandia III", "expected_label": "rpg"},
    {"text": "Defeating monsters using ancient relics in Revenant Saga", "expected_label": "rpg"},
    {"text": "Navigating a city torn by war in The Last Story", "expected_label": "rpg"},
    {"text": "Fighting supernatural beings in Dragon Quest Monsters", "expected_label": "rpg"},
    {"text": "Rescuing my sister from a dark force in Tales of Xillia", "expected_label": "rpg"},
    {"text": "Restoring life to a barren world in The Alliance Alive", "expected_label": "rpg"},
    {"text": "Leading my clan against rival factions in Conan Exiles", "expected_label": "rpg"},
    {"text": "Defending a magical realm from an ancient threat in Arcanum: Of Steamworks and Magick Obscura", "expected_label": "rpg"},
    {"text": "Building my own airship in Skies of Arcadia Legends", "expected_label": "rpg"},
    {"text": "Exploring the magical city of Spira in Final Fantasy X", "expected_label": "rpg"},
    {"text": "Joining a guild to explore dungeons in Etrian Odyssey Nexus", "expected_label": "rpg"},
    {"text": "Solving mysteries to uncover my lost past in Legend of Legaia 2", "expected_label": "rpg"},
    {"text": "Defeating a powerful demon lord in White Knight Chronicles", "expected_label": "rpg"},
    {"text": "Exploring an alternate version of Japan in Muramasa: The Demon Blade", "expected_label": "rpg"},
    {"text": "Restoring peace to the land of Alfheim in Tales of Phantasia", "expected_label": "rpg"},
    {"text": "Exploring ancient ruins in Dragon Age: Origins", "expected_label": "rpg"},
    {"text": "Crafting powerful spells in The Elder Scrolls IV: Oblivion", "expected_label": "rpg"},
    {"text": "Building my own kingdom in Mount & Blade: Warband", "expected_label": "rpg"},
    {"text": "Forming a fellowship to save the realm in Divinity: Original Sin", "expected_label": "rpg"},
    {"text": "Mastering swordplay in Kingdoms of Amalur: Reckoning", "expected_label": "rpg"},
    {"text": "Engaging in turn-based combat in Final Fantasy Tactics", "expected_label": "rpg"},
    {"text": "Choosing my character's destiny in Dragon's Dogma: Dark Arisen", "expected_label": "rpg"},
    {"text": "Leading my guild to victory in Guild Wars 2", "expected_label": "rpg"},
    {"text": "Negotiating peace treaties in The Witcher 2: Assassins of Kings", "expected_label": "rpg"},
    {"text": "Fighting monsters in open-world Japan in Nioh 2", "expected_label": "rpg"},
    {"text": "Exploring ancient temples in Tales of Symphonia", "expected_label": "rpg"},
    {"text": "Fulfilling royal quests in Dragon Quest IX: Sentinels of the Starry Skies", "expected_label": "rpg"},
    {"text": "Crafting weapons and armor in Monster Hunter Stories", "expected_label": "rpg"},
    {"text": "Navigating dark dungeons with friends in Torchlight II", "expected_label": "rpg"},
    {"text": "Fighting off mythical creatures in The Legend of Heroes: Trails in the Sky", "expected_label": "rpg"},
    {"text": "Traveling to the underworld in Pillars of Eternity II: Deadfire", "expected_label": "rpg"},
    {"text": "Saving a town under siege in Dragon Age: Awakening", "expected_label": "rpg"},
    {"text": "Collecting magical items in Ni no Kuni: Wrath of the White Witch", "expected_label": "rpg"},
    {"text": "Joining factions and deciding their fates in Fallout 4", "expected_label": "rpg"},
    {"text": "Crafting potions and managing inventory in The Witcher", "expected_label": "rpg"},
    {"text": "Restoring balance to the world in Secret of Mana", "expected_label": "rpg"},
    {"text": "Traveling across vast deserts in The Elder Scrolls Online", "expected_label": "rpg"},
    {"text": "Forging alliances with powerful dragons in Fire Emblem Awakening", "expected_label": "rpg"},
    {"text": "Discovering lost relics in Dragon's Crown", "expected_label": "rpg"},
    {"text": "Recruiting allies to battle demonic forces in Baldur's Gate: Dark Alliance", "expected_label": "rpg"},
    {"text": "Managing resources and building towns in Final Fantasy Crystal Chronicles", "expected_label": "rpg"},
    {"text": "Fighting my way through hordes of demons in Diablo II", "expected_label": "rpg"},
    {"text": "Solving ancient mysteries in Xenogears", "expected_label": "rpg"},
    {"text": "Rescuing kidnapped villagers in Tales of Zestiria", "expected_label": "rpg"},
    {"text": "Uncovering the secrets of a haunted castle in Vampire: The Masquerade - Bloodlines", "expected_label": "rpg"},
    {"text": "Helping rebels rise against the empire in Star Wars: Knights of the Old Republic II", "expected_label": "rpg"},
    {"text": "Traveling through space to find a new home in Star Ocean: Till the End of Time", "expected_label": "rpg"},
    {"text": "Exploring mythological realms in Titan Quest", "expected_label": "rpg"},
    {"text": "Choosing whether to be a hero or villain in Fable: The Lost Chapters", "expected_label": "rpg"},
    {"text": "Developing relationships with companions in Mass Effect 2", "expected_label": "rpg"},
    {"text": "Defending against an otherworldly threat in Shin Megami Tensei V", "expected_label": "rpg"},
    {"text": "Fighting corrupted spirits in The Legend of Dragoon", "expected_label": "rpg"},
    {"text": "Exploring an alternate universe in Xenoblade Chronicles 2", "expected_label": "rpg"},
    {"text": "Recruiting powerful champions in Heroes of Might and Magic", "expected_label": "rpg"},
    {"text": "Navigating the political complexities of a divided city in Neverwinter Nights 2", "expected_label": "rpg"},
    {"text": "Fighting to save a magical academy in Fire Emblem Fates", "expected_label": "rpg"},
    {"text": "Mastering ancient martial arts in Jade Empire", "expected_label": "rpg"},
    {"text": "Defending a kingdom from an evil sorcerer in Golden Sun", "expected_label": "rpg"},
    {"text": "Exploring a cyberpunk dystopia in Cyberpunk 2077", "expected_label": "rpg"},
    {"text": "Completing side quests to help villagers in Trials of Mana", "expected_label": "rpg"},
    {"text": "Engaging in tactical battles in Disgaea 5: Alliance of Vengeance", "expected_label": "rpg"},
    {"text": "Exploring ancient ruins for lost treasures in Ys VIII: Lacrimosa of Dana", "expected_label": "rpg"},
    {"text": "Choosing the fate of the world in Dragon Age II", "expected_label": "rpg"},
    {"text": "Crafting spells to overcome enemies in Lufia II: Rise of the Sinistrals", "expected_label": "rpg"},
    {"text": "Defending a hidden village from invaders in SaGa Frontier", "expected_label": "rpg"},
    {"text": "Engaging in epic turn-based battles in Blue Dragon", "expected_label": "rpg"},
    {"text": "Making moral decisions to shape my character in Alpha Protocol", "expected_label": "rpg"},
    {"text": "Traveling to different worlds through portals in Radiant Historia", "expected_label": "rpg"},
    {"text": "Building a ship to sail the oceans in Skies of Arcadia", "expected_label": "rpg"},
    {"text": "Exploring a dark fantasy world in Dark Souls II", "expected_label": "rpg"},
    {"text": "Navigating a maze-like castle in Dragon Quest V", "expected_label": "rpg"},
    {"text": "Learning ancient secrets in The Last Remnant", "expected_label": "rpg"},
    {"text": "Uncovering the truth behind conspiracies in The Technomancer", "expected_label": "rpg"},
    {"text": "Forming an adventuring guild in Etrian Odyssey", "expected_label": "rpg"},
    {"text": "Navigating the afterlife in Grim Dawn", "expected_label": "rpg"},
    {"text": "Fighting evil forces across different dimensions in Tales of Eternia", "expected_label": "rpg"},
    {"text": "Rescuing my friends in Eternal Sonata", "expected_label": "rpg"},
    {"text": "Solving puzzles to uncover ancient knowledge in Lost Sphear", "expected_label": "rpg"},
    {"text": "Navigating the realms of life and death in Astria Ascending", "expected_label": "rpg"},
    {"text": "Exploring a forbidden kingdom in Dragon Quest Builders", "expected_label": "rpg"},
    {"text": "Fighting a cult trying to summon a dark power in Valkyria Revolution", "expected_label": "rpg"},
    {"text": "Saving my family from a dark curse in Ar Tonelico: Melody of Elemia", "expected_label": "rpg"},
    {"text": "Battling in ancient coliseums in Grandia", "expected_label": "rpg"},
    {"text": "Exploring an alternate history in Resonance of Fate", "expected_label": "rpg"},
    {"text": "Mastering elemental powers in Secret of Evermore", "expected_label": "rpg"},
    {"text": "Saving the world from giant mechanical beasts in Xenogears", "expected_label": "rpg"},
    {"text": "Battling corrupted knights in Tales of Destiny", "expected_label": "rpg"},
    {"text": "Exploring a mysterious island in Legend of Legaia", "expected_label": "rpg"},
    {"text": "Navigating political intrigue in Suikoden III", "expected_label": "rpg"},
    {"text": "Discovering the magic of runes in Lufia: The Legend Returns", "expected_label": "rpg"},
    {"text": "Creating a powerful spellbook in The Legend of Heroes: Trails of Cold Steel IV", "expected_label": "rpg"},
    {"text": "Navigating the dreams of different characters in Dreamfall Chapters", "expected_label": "rpg"},
    {"text": "Forging powerful alliances in The Surge 2", "expected_label": "rpg"},
    {"text": "Exploring an ancient desert city in Tales of the Abyss", "expected_label": "rpg"},
    {"text": "Saving the magical realm of Fa'Diel in Legend of Mana", "expected_label": "rpg"},
    {"text": "Defending a futuristic world from an alien invasion in Cosmic Fantasy", "expected_label": "rpg"},
    {"text": "Choosing my own path as a hero or villain in Two Worlds", "expected_label": "rpg"},
    {"text": "Exploring the depths of space in Rogue Galaxy", "expected_label": "rpg"},
    {"text": "Rebuilding a broken world in Arc the Lad III", "expected_label": "rpg"},
    {"text": "Rescuing people from an eternal sleep in Threads of Fate", "expected_label": "rpg"},
    {"text": "Defending the world from evil with my companions in Phantasy Star III", "expected_label": "rpg"},
    {"text": "Solving time-related puzzles in Chrono Cross", "expected_label": "rpg"},
    {"text": "Mastering dark powers to protect the kingdom in Dark Rose Valkyrie", "expected_label": "rpg"},
    {"text": "Exploring lost civilizations in Final Fantasy X-2", "expected_label": "rpg"},
    {"text": "Saving the kingdom of Elibe in Fire Emblem: The Blazing Blade", "expected_label": "rpg"},
    {"text": "Recruiting heroes to battle evil in Record of Agarest War", "expected_label": "rpg"},
    {"text": "Defeating an ancient dragon to save my people in Breath of Fire IV", "expected_label": "rpg"},
    {"text": "Navigating a post-apocalyptic fantasy world in Fallout Tactics", "expected_label": "rpg"},
    {"text": "Mastering magic to fight an evil sorceress in Grandia II", "expected_label": "rpg"},
    {"text": "Embarking on a journey through the magical lands of Elder Scrolls: Morrowind", "expected_label": "rpg"},
    {"text": "Fighting alongside my allies in the kingdom of Fódlan in Fire Emblem Warriors", "expected_label": "rpg"},
    {"text": "Gathering mythical creatures to fight in Ni no Kuni: Wrath of the White Witch", "expected_label": "rpg"},
    {"text": "Uncovering lost magic in a dystopian future in Shadowrun Returns", "expected_label": "rpg"},
    {"text": "Saving the kingdom from dark forces in Dragon Quest XI: Echoes of an Elusive Age",  "expected_label": "rpg"},
    {"text": "Reuniting the lost heroes to defeat the ancient evil in Suikoden II", "expected_label": "rpg"},
    {"text": "Exploring the continent of Azeroth in World of Warcraft", "expected_label": "rpg"},
    {"text": "Forging new alliances in Pillars of Eternity", "expected_label": "rpg"},
    {"text": "Building my settlement from scratch in Rune Factory 4", "expected_label": "rpg"},
    {"text": "Fighting off demons in the streets of Tokyo in Tokyo Mirage Sessions #FE", "expected_label": "rpg"},
    {"text": "Exploring the desert wastelands in Fallout 3", "expected_label": "rpg"},
    {"text": "Solving intricate puzzles in The Legend of Zelda: Twilight Princess", "expected_label": "rpg"},
    {"text": "Training my heroes to battle evil forces in Disgaea 5", "expected_label": "rpg"},
    {"text": "Embarking on a space adventure in Mass Effect 2", "expected_label": "rpg"},
    {"text": "Saving the village from a powerful sorcerer in Breath of Fire IV", "expected_label": "rpg"},
    {"text": "Journeying through magical realms in Grandia II", "expected_label": "rpg"},
    {"text": "Forging new alliances and betraying old friends in The Outer Worlds", "expected_label": "rpg"},
    {"text": "Battling through hordes of monsters in Dragon Quest Builders", "expected_label": "rpg"},
    {"text": "Becoming a hero and saving Albion in Fable III", "expected_label": "rpg"},
    {"text": "Conquering evil spirits in Lost Odyssey", "expected_label": "rpg"},
    {"text": "Fighting through dungeons in Sacred 2: Fallen Angel", "expected_label": "rpg"},
    {"text": "Leading my army against the Blight in Dragon Age II", "expected_label": "rpg"},
    {"text": "Navigating the underworld in Shin Megami Tensei IV", "expected_label": "rpg"},
    {"text": "Saving an alternate dimension in Chrono Cross", "expected_label": "rpg"},
    {"text": "Developing bonds with teammates in Persona 4 Golden", "expected_label": "rpg"},
    {"text": "Building a settlement and recruiting warriors in Dark Cloud 2", "expected_label": "rpg"},
    {"text": "Mastering swordsmanship in Kingdom Come: Deliverance", "expected_label": "rpg"},
    {"text": "Restoring balance to the forest in Ori and the Blind Forest", "expected_label": "rpg"},
    {"text": "Becoming a mage to battle the undead in Arx Fatalis", "expected_label": "rpg"},
    {"text": "Exploring the vast open world of Vvardenfell in Elder Scrolls III: Morrowind", "expected_label": "rpg"},
    {"text": "Joining the Night's Watch in Game of Thrones: A Telltale Games Series", "expected_label": "rpg"},
    {"text": "Journeying through a post-apocalyptic future in NieR Replicant", "expected_label": "rpg"},
    {"text": "Fighting the Lords of Cinder in Dark Souls III", "expected_label": "rpg"},
    {"text": "Mastering the arts of diplomacy in Tyranny", "expected_label": "rpg"},
    {"text": "Building an army to fight the demonic invasion in Neverwinter Nights", "expected_label": "rpg"},
    {"text": "Exploring a land of floating islands in Bastion", "expected_label": "rpg"},
    {"text": "Completing epic quests across the lands of Rivellon in Divinity: Original Sin", "expected_label": "rpg"},
    {"text": "Fighting my way through a crumbling world in Final Fantasy IX", "expected_label": "rpg"},
    {"text": "Forging alliances and saving the world in Golden Sun", "expected_label": "rpg"},
    {"text": "Training dragons to fight against enemy tribes in How to Train Your Dragon", "expected_label": "rpg"},
    {"text": "Saving the realms of Tamriel from an ancient threat in Elder Scrolls IV: Oblivion",  "expected_label": "rpg"},
    {"text": "Exploring a magical garden in Atelier Shallie", "expected_label": "rpg"},
    {"text": "Leading an expedition into an unknown world in Xenogears", "expected_label": "rpg"},
    {"text": "Embarking on a pirate adventure in Skies of Arcadia", "expected_label": "rpg"},
    {"text": "Navigating a haunted kingdom in Shadow Hearts", "expected_label": "rpg"},
    {"text": "Joining the ranks of the Knights of the Old Republic in Star Wars: KOTOR", "expected_label": "rpg"},
    {"text": "Rebuilding a devastated kingdom in Eiyuden Chronicle", "expected_label": "rpg"},
    {"text": "Fighting off dark cultists in Pathfinder: Kingmaker", "expected_label": "rpg"},
    {"text": "Exploring the dreamlike lands of Ni no Kuni II", "expected_label": "rpg"},
    {"text": "Learning alchemy to solve puzzles in Atelier Escha & Logy", "expected_label": "rpg"},
    {"text": "Battling massive gods in God Eater 3", "expected_label": "rpg"},
    {"text": "Exploring mysterious ruins in Secret of Mana", "expected_label": "rpg"},
    {"text": "Saving a world in turmoil in The Legend of Heroes: Trails in the Sky", "expected_label": "rpg"},
    {"text": "Defeating a powerful demon invasion in Devil Survivor 2", "expected_label": "rpg"},
    {"text": "Embarking on a time-traveling adventure in Xenoblade Chronicles 2", "expected_label": "rpg"},
    {"text": "Crafting powerful items to protect my town in Atelier Ryza 2", "expected_label": "rpg"},
    {"text": "Taking down a sinister force in Lost Sphear", "expected_label": "rpg"},
    {"text": "Recruiting legendary heroes in The Legend of Dragoon", "expected_label": "rpg"},
    {"text": "Saving the universe from destruction in Star Ocean: Till the End of Time", "expected_label": "rpg"},
    {"text": "Mastering arcane spells to defeat dark forces in Baldur's Gate II", "expected_label": "rpg"},
    {"text": "Solving mysterious events in Persona Q2: New Cinema Labyrinth", "expected_label": "rpg"},
    {"text": "Leading a rebellion against a tyrannical government in Xenogears", "expected_label": "rpg"},
    {"text": "Exploring a whimsical land in The Legend of Mana", "expected_label": "rpg"},
    {"text": "Training as a witcher to fight monsters in The Witcher 2: Assassins of Kings", "expected_label": "rpg"},
    {"text": "Saving a cursed village in Ni no Kuni: Cross Worlds", "expected_label": "rpg"},
    {"text": "Exploring the dark corners of the past in Resonance of Fate", "expected_label": "rpg"},
    {"text": "Defending against an alien invasion in Anachronox", "expected_label": "rpg"},
    {"text": "Fighting for freedom in Dragon Quest VIII", "expected_label": "rpg"},
    {"text": "Exploring an unknown dimension in Blue Dragon", "expected_label": "rpg"},
    {"text": "Training my magic skills in Spellforce 2", "expected_label": "rpg"},
    {"text": "Rescuing legendary creatures in Tales of Symphonia", "expected_label": "rpg"},
    {"text": "Restoring hope to a dying world in Atelier Lydie & Suelle", "expected_label": "rpg"},
    {"text": "Navigating a galaxy in chaos in Star Ocean: The Last Hope", "expected_label": "rpg"},
    {"text": "Battling demonic creatures in Ys Seven", "expected_label": "rpg"},
    {"text": "Restoring the magical balance in Lunar: Silver Star Story Complete", "expected_label": "rpg"},
    {"text": "Fighting for honor in a feudal Japanese setting in Way of the Samurai", "expected_label": "rpg"},
    {"text": "Rescuing villagers from dark forces in Breath of Fire V: Dragon Quarter", "expected_label": "rpg"},
    {"text": "Embarking on a journey through a mystical land in Saga Frontier 2", "expected_label": "rpg"},
    {"text": "Saving a world on the brink of chaos in Grandia III", "expected_label": "rpg"},
    {"text": "Exploring haunted lands in Folklore", "expected_label": "rpg"},
    {"text": "Forging alliances with other species in Mass Effect 3", "expected_label": "rpg"},
    {"text": "Rebuilding the world after a great calamity in Atelier Ayesha", "expected_label": "rpg"},
    {"text": "Restoring my family's honor in Jade Empire", "expected_label": "rpg"},
    {"text": "Exploring the mysteries of the deep ocean in Aquanox", "expected_label": "rpg"},
    {"text": "Fighting against a clockwork apocalypse in SteamWorld Quest", "expected_label": "rpg"},
    {"text": "Building an adventurer's guild in Atelier Meruru", "expected_label": "rpg"},
    {"text": "Traveling through time to avert disasters in Radiata Stories", "expected_label": "rpg"},
    {"text": "Defending my village against monsters in Summoner", "expected_label": "rpg"},
    {"text": "Exploring a haunted cathedral in Gothic", "expected_label": "rpg"},
    {"text": "Uncovering the secrets of a lost civilization in Ar Tonelico", "expected_label": "rpg"},
    {"text": "Rescuing the magical creatures in Fairy Fencer F", "expected_label": "rpg"},
    {"text": "Exploring a world of steampunk wonders in Legend of Heroes: Trails to Azure", "expected_label": "rpg"},
    {"text": "Embarking on an epic journey in The Witcher 2: Assassins of Kings", "expected_label": "rpg"},
    {"text": "Building my kingdom in Ni no Kuni II: Revenant Kingdom", "expected_label": "rpg"},
    {"text": "Training to be a hero in Dragon Quest VIII: Journey of the Cursed King", "expected_label": "rpg"},
    {"text": "Exploring the vast lands of Hyrule in The Legend of Zelda: Breath of the Wild", "expected_label": "rpg"},
    {"text": "Recruiting allies to save the world in Final Fantasy VI", "expected_label": "rpg"},
    {"text": "Fighting mystical beasts in Xenoblade Chronicles X", "expected_label": "rpg"},
    {"text": "Exploring a cyberpunk city in Shadowrun: Dragonfall", "expected_label": "rpg"},
    {"text": "Uncovering hidden magic in the depths of Ehb in Dungeon Siege III", "expected_label": "rpg"},
    {"text": "Restoring lost memories in Tales of Arise", "expected_label": "rpg"},
    {"text": "Completing trials to gain power in Kingdom Hearts II", "expected_label": "rpg"},
    {"text": "Saving a town from dark magic in Atelier Firis", "expected_label": "rpg"},
    {"text": "Exploring a dystopian future in Fallout: New Vegas", "expected_label": "rpg"},
    {"text": "Leading an army against ancient evil in Fire Emblem: Path of Radiance", "expected_label": "rpg"},
    {"text": "Journeying through the magical world of Ni no Kuni: Wrath of the White Witch", "expected_label": "rpg"},
    {"text": "Exploring the ancient ruins of Ishgard in Final Fantasy XIV", "expected_label": "rpg"},
    {"text": "Fighting monsters in a haunted realm in Dark Souls Remastered", "expected_label": "rpg"},
    {"text": "Learning spells in a magical academy in Trails of Cold Steel", "expected_label": "rpg"},
    {"text": "Exploring mystical lands with a party of adventurers in Grandia III", "expected_label": "rpg"},
    {"text": "Fighting my way through a world of Norse mythology in Odin Sphere", "expected_label": "rpg"},
    {"text": "Solving intricate puzzles in The Legend of Zelda: Skyward Sword", "expected_label": "rpg"},
    {"text": "Fighting through hordes of enemies in Diablo II", "expected_label": "rpg"},
    {"text": "Gathering magical allies in Dragon's Dogma: Dark Arisen", "expected_label": "rpg"},
    {"text": "Exploring the lands of Rivellon in Divinity: Original Sin 2", "expected_label": "rpg"},
    {"text": "Building my town and recruiting villagers in Rune Factory 5", "expected_label": "rpg"},
    {"text": "Forging alliances with mythical creatures in Ni no Kuni: Cross Worlds", "expected_label": "rpg"},
    {"text": "Fighting gods to save the realm in Valkyrie Profile", "expected_label": "rpg"},
    {"text": "Completing quests to save a lost kingdom in Ys VIII: Lacrimosa of Dana", "expected_label": "rpg"},
    {"text": "Rescuing villagers from darkness in Atelier Lulua: The Scion of Arland", "expected_label": "rpg"},
    {"text": "Exploring the depths of the underworld in Shin Megami Tensei V", "expected_label": "rpg"},
    {"text": "Saving an alternate reality in Persona 5 Strikers", "expected_label": "rpg"},
    {"text": "Becoming a legendary witcher in The Witcher III: Wild Hunt", "expected_label": "rpg"},
    {"text": "Leading my squad against dark forces in Fire Emblem Engage", "expected_label": "rpg"},
    {"text": "Restoring balance to the universe in Phantasy Star IV", "expected_label": "rpg"},
    {"text": "Recruiting heroes to fight in the great war in Suikoden III", "expected_label": "rpg"},
    {"text": "Fighting ancient deities in Final Fantasy XIII", "expected_label": "rpg"},
    {"text": "Exploring a lost world in Blue Reflection Second Light", "expected_label": "rpg"},
    {"text": "Fighting a dark cult in Tales of Zestiria", "expected_label": "rpg"},
    {"text": "Training to become a legendary warrior in Monster Hunter Stories", "expected_label": "rpg"},
    {"text": "Battling through a grim fantasy world in Demon’s Souls", "expected_label": "rpg"},
    {"text": "Rebuilding my village after the apocalypse in Fallout 4", "expected_label": "rpg"},
    {"text": "Exploring enchanted lands in Atelier Rorona: The Alchemist of Arland", "expected_label": "rpg"},
    {"text": "Journeying through space to stop an invasion in Star Ocean: Integrity and Faithlessness", "expected_label": "rpg"},
    {"text": "Fighting to protect humanity in Xenogears", "expected_label": "rpg"},
    {"text": "Saving the kingdom from destruction in Dragon Quest Heroes", "expected_label": "rpg"},
    {"text": "Exploring a mysterious castle in Eternal Sonata", "expected_label": "rpg"},
    {"text": "Rescuing my sister from an evil sorceress in Lost Kingdoms", "expected_label": "rpg"},
    {"text": "Fighting through dungeons to recover ancient relics in The Legend of Heroes: Trails of Cold Steel III", "expected_label": "rpg"},
    {"text": "Exploring the magical world of Lucis in Final Fantasy XV", "expected_label": "rpg"},
    {"text": "Mastering the craft of alchemy in Atelier Shallie: Alchemists of the Dusk Sea", "expected_label": "rpg"},
    {"text": "Traveling through time to save the future in Chrono Trigger", "expected_label": "rpg"},
    {"text": "Recruiting heroes to battle in the resistance in The Legend of Dragoon", "expected_label": "rpg"},
    {"text": "Navigating a world on the brink of extinction in Tales of Graces F", "expected_label": "rpg"},
    {"text": "Exploring a dark, gothic city in Bloodborne", "expected_label": "rpg"},
    {"text": "Building a team of legends in Dragon Quest IX: Sentinels of the Starry Skies", "expected_label": "rpg"},
    {"text": "Saving a mystical world from destruction in The Last Remnant", "expected_label": "rpg"},
    {"text": "Embarking on a journey of redemption in The Outer Worlds", "expected_label": "rpg"},
    {"text": "Exploring a sprawling open world in Skyrim", "expected_label": "rpg"},
    {"text": "Forging new alliances to protect the world in Tales of Vesperia", "expected_label": "rpg"},
    {"text": "Fighting off an invasion of demonic creatures in Devil Survivor", "expected_label": "rpg"},
    {"text": "Becoming a legend in the land of Ivalice in Final Fantasy Tactics", "expected_label": "rpg"},
    {"text": "Saving an alternate universe in Chrono Cross", "expected_label": "rpg"},
    {"text": "Defending a magical kingdom in Atelier Sophie: The Alchemist of the Mysterious Book", "expected_label": "rpg"},
    {"text": "Exploring an open world filled with mythical creatures in Horizon Zero Dawn", "expected_label": "rpg"},
    {"text": "Embarking on a pirate adventure in One Piece Odyssey", "expected_label": "rpg"},
    {"text": "Forging new friendships in Dragon Quest Builders 2", "expected_label": "rpg"},
    {"text": "Reuniting lost souls in Soul Nomad & the World Eaters", "expected_label": "rpg"},
    {"text": "Exploring the realms of Yggdrasil in Etrian Odyssey Nexus", "expected_label": "rpg"},
    {"text": "Saving the world from an alien invasion in Xenoblade Chronicles 3", "expected_label": "rpg"},
    {"text": "Mastering magical powers to defeat evil forces in Arc Rise Fantasia", "expected_label": "rpg"},
    {"text": "Building my own house in My Time at Portia", "expected_label": "rpg"},
    {"text": "Fighting my way through ancient lands in Nioh", "expected_label": "rpg"},
    {"text": "Rescuing mythical beings in The Lost Child", "expected_label": "rpg"},
    {"text": "Rebuilding a fallen city in Atelier Lydie & Suelle: The Alchemists and the Mysterious Paintings", "expected_label": "rpg"},
    {"text": "Solving puzzles and saving the world in Ar Nosurge: Ode to an Unborn Star", "expected_label": "rpg"},
    {"text": "Defending against dark forces in Legend of Legaia", "expected_label": "rpg"},
    {"text": "Restoring peace to the realm of Avalonia in Dragon Quest Swords", "expected_label": "rpg"},
    {"text": "Exploring an ancient library in Bravely Default II", "expected_label": "rpg"},
    {"text": "Embarking on a mythical quest in The Legend of Heroes: Trails of Cold Steel IV", "expected_label": "rpg"},
    {"text": "Gathering resources to craft powerful artifacts in Atelier Totori", "expected_label": "rpg"},
    {"text": "Fighting against chaos in Ys IX: Monstrum Nox", "expected_label": "rpg"},
    {"text": "Mastering the arcane arts in Baldur's Gate III", "expected_label": "rpg"},
    {"text": "Exploring a magical island in Grandia", "expected_label": "rpg"},
    {"text": "Battling giant monsters in Monster Hunter World", "expected_label": "rpg"},
    {"text": "Traveling across the lands to forge new alliances in Suikoden V", "expected_label": "rpg"},
    {"text": "Saving a small village from an ancient curse in Tales of Phantasia", "expected_label": "rpg"},
    {"text": "Exploring the futuristic city of New Los Angeles in Xenoblade Chronicles X", "expected_label": "rpg"},
    {"text": "Leading a rebellion against tyranny in Sakura Wars", "expected_label": "rpg"},
    {"text": "Uncovering the secrets of the Great Crystal in Final Fantasy XII", "expected_label": "rpg"},
    {"text": "Training to be a hero in Trials of Mana", "expected_label": "rpg"},
    {"text": "Forging new paths through an enchanted world in Blue Dragon", "expected_label": "rpg"},
    {"text": "Fighting against an otherworldly force in Infinite Undiscovery", "expected_label": "rpg"},
    {"text": "Restoring harmony to the world in Atelier Iris 2", "expected_label": "rpg"},
    {"text": "Exploring mystical lands in Radiant Historia", "expected_label": "rpg"},
    {"text": "Training to become the savior of the world in Tales of the Abyss", "expected_label": "rpg"},
    {"text": "Exploring an expansive world filled with adventure in Horizon Forbidden West", "expected_label": "rpg"},
    {"text": "Mastering dark magic in Octopath Traveler", "expected_label": "rpg"},
    {"text": "Saving a kingdom on the brink of collapse in Disgaea 6", "expected_label": "rpg"},
    {"text": "Exploring the heavens in Skies of Arcadia Legends", "expected_label": "rpg"},
    {"text": "Fighting to save the kingdom in Dragon Quest XI: Echoes of an Elusive Age", "expected_label": "rpg"},
    {"text": "Exploring a mythical island in Xenoblade Chronicles Definitive Edition", "expected_label": "rpg"},
    {"text": "Learning ancient spells in Divinity: Original Sin", "expected_label": "rpg"},
    {"text": "Defending a magical world in Tales of Symphonia", "expected_label": "rpg"},
    {"text": "Rebuilding society after the apocalypse in Fallout: New California", "expected_label": "rpg"},
    {"text": "Unraveling the secrets of an ancient temple in Breath of Fire III", "expected_label": "rpg"},
    {"text": "Mastering swordsmanship in Tales of Arise", "expected_label": "rpg"},
    {"text": "Exploring an alien world in Mass Effect: Andromeda", "expected_label": "rpg"},
    {"text": "Saving my friends from an evil emperor in Suikoden II", "expected_label": "rpg"},
    {"text": "Battling mythological creatures in Shin Megami Tensei Nocturne", "expected_label": "rpg"},
    {"text": "Solving magical mysteries in Atelier Meruru: The Apprentice of Arland", "expected_label": "rpg"},
    {"text": "Traveling through time and dimensions in Chrono Cross", "expected_label": "rpg"},
    {"text": "Exploring a vibrant world filled with dragons in Dragon's Dogma", "expected_label": "rpg"},
    {"text": "Forging new alliances with clans in Skyrim", "expected_label": "rpg"},
    {"text": "Journeying across space in Star Ocean: The Last Hope", "expected_label": "rpg"},
    {"text": "Defeating dark forces in Ys VII: Lacrimosa of Dana", "expected_label": "rpg"},
    {"text": "Fighting to restore peace in Tales of Zestiria", "expected_label": "rpg"},
    {"text": "Recruiting legendary heroes in Fire Emblem: Three Houses", "expected_label": "rpg"},
    {"text": "Gathering mystical ingredients in Atelier Ryza: Ever Darkness & the Secret Hideout", "expected_label": "rpg"},
    {"text": "Learning to be a hero in The Legend of Heroes: Trails in the Sky", "expected_label": "rpg"},
    {"text": "Restoring order to a chaotic world in Final Fantasy VII", "expected_label": "rpg"},
    {"text": "Fighting demon lords in Persona 4", "expected_label": "rpg"},
    {"text": "Saving a magical village in Blue Reflection", "expected_label": "rpg"},
    {"text": "Exploring a forgotten kingdom in Final Fantasy IX", "expected_label": "rpg"},
    {"text": "Finding a legendary artifact in Ni no Kuni: Wrath of the White Witch", "expected_label": "rpg"},
    {"text": "Training to become a powerful warrior in Dragon Quest III", "expected_label": "rpg"},
    {"text": "Exploring enchanted islands in The Legend of Zelda: Wind Waker", "expected_label": "rpg"},
    {"text": "Building a thriving town in Rune Factory Frontier", "expected_label": "rpg"},
    {"text": "Fighting ancient evils in Xenoblade Chronicles X", "expected_label": "rpg"},
    {"text": "Reclaiming a throne in Kingdom Come: Deliverance", "expected_label": "rpg"},
    {"text": "Fighting to lift a curse in Radiata Stories", "expected_label": "rpg"},
    {"text": "Traveling to mythical lands in Grandia II", "expected_label": "rpg"},
    {"text": "Uncovering hidden conspiracies in Fallout: New Vegas", "expected_label": "rpg"},
    {"text": "Becoming a knight in Dark Souls III", "expected_label": "rpg"},
    {"text": "Fighting magical beings in The Legend of Heroes: Trails of Cold Steel IV", "expected_label": "rpg"},
    {"text": "Restoring a broken world in Octopath Traveler II", "expected_label": "rpg"},
    {"text": "Learning alchemy to save my friends in Atelier Totori: The Adventurer of Arland",  "expected_label": "rpg"},
    {"text": "Exploring underwater realms in Final Fantasy X", "expected_label": "rpg"},
    {"text": "Defending a village from monsters in Tales of Destiny", "expected_label": "rpg"},
    {"text": "Embarking on a dangerous journey to save a sibling in Tales of Innocence", "expected_label": "rpg"},
    {"text": "Discovering hidden powers in Persona 3 FES", "expected_label": "rpg"},
    {"text": "Exploring new worlds in Star Ocean: First Departure", "expected_label": "rpg"},
    {"text": "Journeying to the otherworld in Lost Odyssey", "expected_label": "rpg"},
    {"text": "Gathering legendary crystals in Bravely Default", "expected_label": "rpg"},
    {"text": "Traveling across magical lands in Tales of Xillia", "expected_label": "rpg"},
    {"text": "Fighting to restore the timeline in Radiant Historia: Perfect Chronology", "expected_label": "rpg"},
    {"text": "Learning powerful skills in Final Fantasy IV", "expected_label": "rpg"},
    {"text": "Exploring a cursed tower in Tales of Berseria", "expected_label": "rpg"},
    {"text": "Fighting to save the world from an ancient curse in Grandia", "expected_label": "rpg"},
    {"text": "Mastering powerful magic in Arc the Lad: Twilight of the Spirits", "expected_label": "rpg"},
    {"text": "Exploring an ancient kingdom in Secret of Mana", "expected_label": "rpg"},
    {"text": "Fighting my way through an army of evil spirits in Dragon Quest IV", "expected_label": "rpg"},
    {"text": "Uncovering lost memories in Legend of Legaia", "expected_label": "rpg"},
    {"text": "Traveling across the lands to save humanity in Valkyria Chronicles", "expected_label": "rpg"},
    {"text": "Journeying through mystical realms in Final Fantasy VIII", "expected_label": "rpg"},
    {"text": "Fighting to protect the sacred tree in Mana Khemia: Alchemists of Al-Revis", "expected_label": "rpg"},
    {"text": "Recruiting heroes to save the kingdom in Dragon Quest V", "expected_label": "rpg"},
    {"text": "Exploring a magical city in Atelier Shallie", "expected_label": "rpg"},
    {"text": "Fighting through enchanted lands in Ys Origin", "expected_label": "rpg"},
    {"text": "Learning ancient spells in Tales of Eternia", "expected_label": "rpg"},
    {"text": "Saving my people from dark forces in Xenogears", "expected_label": "rpg"},
    {"text": "Traveling through time to prevent a catastrophe in Chrono Trigger", "expected_label": "rpg"},
    {"text": "Building alliances to protect a kingdom in Suikoden IV", "expected_label": "rpg"},
    {"text": "Fighting dark spirits in The Legend of Heroes: Trails from Zero", "expected_label": "rpg"},
    {"text": "Exploring an alien-infested colony in Phantasy Star Online", "expected_label": "rpg"},
    {"text": "Traveling to mythical regions in Ni no Kuni II", "expected_label": "rpg"},
    {"text": "Saving my friends from an evil sorcerer in Atelier Escha & Logy", "expected_label": "rpg"},
    {"text": "Fighting monsters and exploring dungeons in Dark Cloud", "expected_label": "rpg"},
    {"text": "Restoring peace to a magical world in Eternal Sonata", "expected_label": "rpg"},
    {"text": "Exploring the ancient ruins in Xenoblade Chronicles 2", "expected_label": "rpg"},
    {"text": "Rescuing villagers from an evil cult in Tales of Symphonia: Dawn of the New World",  "expected_label": "rpg"},
    {"text": "Exploring the realms of mythology in Golden Sun", "expected_label": "rpg"},
    {"text": "Fighting against a powerful dragon in Breath of Fire IV", "expected_label": "rpg"},
    {"text": "Recruiting friends to battle dark forces in Fire Emblem Warriors", "expected_label": "rpg"},
    {"text": "Learning alchemy to solve mysteries in Atelier Lydie & Suelle", "expected_label": "rpg"},
    {"text": "Restoring order to the universe in Phantasy Star IV", "expected_label": "rpg"},
    {"text": "Fighting to become a legend in Final Fantasy Crystal Chronicles", "expected_label": "rpg"},
    {"text": "Traveling through enchanted lands in Tales of Destiny II", "expected_label": "rpg"},
    {"text": "Saving a world on the brink of extinction in Star Ocean: Till the End of Time", "expected_label": "rpg"},
    {"text": "Exploring the mythical lands of Fa'Diel in Legend of Mana", "expected_label": "rpg"},
    {"text": "Learning to become a hero in Radiant Historia", "expected_label": "rpg"},
    {"text": "Fighting monsters to save the realm in Ni no Kuni: Revenant Kingdom", "expected_label": "rpg"},
    {"text": "Exploring a mystical world filled with mythical creatures in Horizon Zero Dawn", "expected_label": "rpg"},
    {"text": "Saving the villagers from an ancient curse in Atelier Firis", "expected_label": "rpg"},
    {"text": "Recruiting powerful warriors in Fire Emblem Fates", "expected_label": "rpg"},
    {"text": "Exploring enchanted dungeons in Ys: Memories of Celceta", "expected_label": "rpg"},
    {"text": "Battling in a grand adventure in Dragon Quest Builders", "expected_label": "rpg"},
    {"text": "Exploring a haunted mansion in Blue Reflection", "expected_label": "rpg"},
    {"text": "Restoring peace to the shattered world in Grandia III", "expected_label": "rpg"},
    {"text": "Becoming a legendary hero in Dragon Quest II", "expected_label": "rpg"},
    {"text": "Traveling to distant planets in Phantasy Star Universe", "expected_label": "rpg"},
    {"text": "Exploring magical forests in Atelier Lulua", "expected_label": "rpg"},
    {"text": "Fighting legendary beasts in The Legend of Heroes: Trails of Cold Steel II", "expected_label": "rpg"},
    {"text": "Restoring hope to the world in Ni no Kuni: Wrath of the White Witch Remastered", "expected_label": "rpg"},
    {"text": "Fighting mystical creatures in Final Fantasy XIII", "expected_label": "rpg"},
    {"text": "Journeying through the Nine Realms in God of War: Ragnarok", "expected_label": "rpg"},
    {"text": "Becoming a warrior of light in Final Fantasy XIV", "expected_label": "rpg"},
    {"text": "Exploring the open world of Elden Ring", "expected_label": "rpg"},
    {"text": "Fighting to unite the kingdom in Fire Emblem Engage", "expected_label": "rpg"},
    {"text": "Gathering a team of heroes in Octopath Traveler", "expected_label": "rpg"},
    {"text": "Exploring dungeons in Dragon Quest Builders 2", "expected_label": "rpg"},
    {"text": "Traveling across the galaxy in Starfield", "expected_label": "rpg"},
    {"text": "Becoming a werewolf in The Elder Scrolls Online", "expected_label": "rpg"},
    {"text": "Embarking on a quest to rescue a sibling in Genshin Impact", "expected_label": "rpg"},
    {"text": "Fighting ancient monsters in Monster Hunter: World", "expected_label": "rpg"},
    {"text": "Restoring an ancient kingdom in GreedFall", "expected_label": "rpg"},
    {"text": "Learning powerful spells in Baldur's Gate III", "expected_label": "rpg"},
    {"text": "Defending against dark forces in Tales of Vesperia", "expected_label": "rpg"},
    {"text": "Solving puzzles and defeating evil in Ni no Kuni II: Revenant Kingdom", "expected_label": "rpg"},
    {"text": "Exploring the mystical lands of Hyrule in Zelda: Breath of the Wild", "expected_label": "rpg"},
    {"text": "Saving the world from chaos in Dark Souls II", "expected_label": "rpg"},
    {"text": "Building relationships in Persona 5 Royal", "expected_label": "rpg"},
    {"text": "Fighting through time in Radiant Historia", "expected_label": "rpg"},
    {"text": "Gathering mystical herbs in Atelier Ayesha", "expected_label": "rpg"},
    {"text": "Exploring the vast desert in Final Fantasy XV", "expected_label": "rpg"},
    {"text": "Uncovering the mysteries of an ancient temple in Ys IX", "expected_label": "rpg"},
    {"text": "Defending against invaders in Xenoblade Chronicles 3", "expected_label": "rpg"},
    {"text": "Training to become a powerful summoner in Final Fantasy X", "expected_label": "rpg"},
    {"text": "Restoring the balance of nature in Child of Light", "expected_label": "rpg"},
    {"text": "Defending a small village from monsters in The Witcher 2", "expected_label": "rpg"},
    {"text": "Saving the princess in Trials of Mana", "expected_label": "rpg"},
    {"text": "Finding legendary items in Divinity: Original Sin II", "expected_label": "rpg"},
    {"text": "Rebuilding a war-torn country in Suikoden III", "expected_label": "rpg"},
    {"text": "Exploring alien worlds in Mass Effect 3", "expected_label": "rpg"},
    {"text": "Traveling to mystical realms in Final Fantasy Tactics", "expected_label": "rpg"},
    {"text": "Becoming a rogue mage in Dragon Age: Origins", "expected_label": "rpg"},
    {"text": "Battling to save the kingdom of Alexandria in Final Fantasy IX", "expected_label": "rpg"},
    {"text": "Exploring a dark and mysterious city in Bloodborne", "expected_label": "rpg"},
    {"text": "Mastering elemental magic in Blue Dragon", "expected_label": "rpg"},
    {"text": "Saving the world from a dark force in Arc Rise Fantasia", "expected_label": "rpg"},
    {"text": "Rescuing a lost soul in Shadow Hearts", "expected_label": "rpg"},
    {"text": "Restoring the timeline in Legend of Legaia 2", "expected_label": "rpg"},
    {"text": "Exploring a magical forest in Eternal Sonata", "expected_label": "rpg"},
    {"text": "Learning new skills to protect my village in Rune Factory 4", "expected_label": "rpg"},
    {"text": "Fighting against powerful demons in Tales of Phantasia", "expected_label": "rpg"},
    {"text": "Training to become a wizard in Final Fantasy III", "expected_label": "rpg"},
    {"text": "Traveling across a shattered continent in Xenoblade Chronicles", "expected_label": "rpg"},
    {"text": "Saving the world from an apocalyptic event in Final Fantasy XII", "expected_label": "rpg"},
    {"text": "Exploring mysterious dungeons in The Legend of Heroes: Trails of Cold Steel III", "expected_label": "rpg"},
    {"text": "Becoming a hero in Legend of Dragoon", "expected_label": "rpg"},
    {"text": "Learning the art of magic in Dragon Quest VI", "expected_label": "rpg"},
    {"text": "Fighting an army of darkness in Fire Emblem: Path of Radiance", "expected_label": "rpg"},
    {"text": "Discovering new powers in Chrono Trigger", "expected_label": "rpg"},
    {"text": "Gathering ancient relics in Star Ocean: Integrity and Faithlessness", "expected_label": "rpg"},
    {"text": "Training to be a master swordsman in Lost Odyssey", "expected_label": "rpg"},
    {"text": "Restoring order to a chaotic world in Ni no Kuni", "expected_label": "rpg"},
    {"text": "Traveling to distant lands in Tales of the Abyss", "expected_label": "rpg"},
    {"text": "Building a kingdom in Dragon Quest VII", "expected_label": "rpg"},
    {"text": "Exploring magical caves in Atelier Iris", "expected_label": "rpg"},
    {"text": "Fighting against dark knights in Final Fantasy V", "expected_label": "rpg"},
    {"text": "Exploring mythical islands in The Legend of Zelda: Phantom Hourglass", "expected_label": "rpg"},
    {"text": "Restoring peace to the land in Dragon Quest VIII", "expected_label": "rpg"},
    {"text": "Saving a lost friend in Atelier Lydie & Suelle", "expected_label": "rpg"},
    {"text": "Becoming a legendary swordsman in Ys VIII", "expected_label": "rpg"},
    {"text": "Rescuing the kingdom from an evil sorcerer in Tales of Graces", "expected_label": "rpg"},
    {"text": "Mastering new alchemy techniques in Atelier Sophie", "expected_label": "rpg"},
    {"text": "Restoring a shattered timeline in Radiant Historia", "expected_label": "rpg"},
    {"text": "Exploring the enchanted city of Altissia in Final Fantasy XV", "expected_label": "rpg"},
    {"text": "Fighting to become a hero in Blue Reflection Second Light", "expected_label": "rpg"},
    {"text": "Defending against evil forces in Suikoden V", "expected_label": "rpg"},
    {"text": "Learning ancient magic in Tales of Xillia 2", "expected_label": "rpg"},
    {"text": "Restoring the balance of power in Ni no Kuni II", "expected_label": "rpg"},
    {"text": "Fighting legendary dragons in The Elder Scrolls V: Skyrim", "expected_label": "rpg"},
    {"text": "Exploring dungeons to uncover ancient secrets in Ys Seven", "expected_label": "rpg"},
    {"text": "Saving a princess from a dark fate in Final Fantasy IV", "expected_label": "rpg"},
    {"text": "Exploring magical temples in Dragon Quest Heroes", "expected_label": "rpg"},
    {"text": "Restoring a broken kingdom in Tales of Legendia", "expected_label": "rpg"},
    {"text": "Fighting to become a guardian in Final Fantasy X-2", "expected_label": "rpg"},
    {"text": "Learning to master powerful spells in Atelier Escha & Logy", "expected_label": "rpg"},
    {"text": "Exploring an enchanted world in Eternal Sonata", "expected_label": "rpg"},
    {"text": "Defeating dark sorcerers in The Legend of Heroes: Trails in the Sky Second Chapter", "expected_label": "rpg"},
    {"text": "Rescuing lost souls in Shadow Hearts: Covenant", "expected_label": "rpg"},
    {"text": "Saving an entire continent from ruin in Fire Emblem Awakening", "expected_label": "rpg"},
    {"text": "Restoring hope to a dying world in Final Fantasy XIII-2", "expected_label": "rpg"},
    {"text": "Learning the ways of magic in Atelier Shallie", "expected_label": "rpg"},
    {"text": "Building friendships to save the world in Persona 4 Golden", "expected_label": "rpg"},
    {"text": "Journeying through mystical realms in Grandia III", "expected_label": "rpg"},
    {"text": "Fighting dark forces in Dark Souls III", "expected_label": "rpg"},
    {"text": "Exploring lost ruins in Xenoblade Chronicles 2", "expected_label": "rpg"},
    {"text": "Fighting in legendary battles in Dragon Quest XI", "expected_label": "rpg"},
    {"text": "Restoring the world to order in Tales of Zestiria", "expected_label": "rpg"},
    {"text": "Saving magical creatures in Ni no Kuni: Wrath of the White Witch", "expected_label": "rpg"},
    {"text": "Exploring enchanted forests in Atelier Firis", "expected_label": "rpg"},
    {"text": "Learning the secrets of ancient runes in Ys IX", "expected_label": "rpg"},
    {"text": "Battling dark creatures in The Legend of Zelda: Twilight Princess", "expected_label": "rpg"},
    {"text": "Uncovering the mysteries of a ruined kingdom in Dark Cloud 2", "expected_label": "rpg"},
    {"text": "Restoring hope to a broken land in Atelier Meruru", "expected_label": "rpg"},
    {"text": "Defending a magical village in Legend of Mana", "expected_label": "rpg"},
    {"text": "Rescuing an ancient city in Final Fantasy Crystal Chronicles", "expected_label": "rpg"},
    {"text": "Exploring a war-torn world in Valkyria Chronicles", "expected_label": "rpg"},
    {"text": "Learning the ancient ways of the knights in Final Fantasy II", "expected_label": "rpg"},
    {"text": "Restoring magic to the world in Tales of Vesperia", "expected_label": "rpg"},
    {"text": "Fighting mythical beings in Xenogears", "expected_label": "rpg"},
    {"text": "Embarking on a quest to find the Dragon Balls in Dragon Ball Z: Kakarot", "expected_label": "rpg"},
    {"text": "Restoring the world from chaos in Chrono Cross", "expected_label": "rpg"},
    {"text": "Exploring a mysterious island in Atelier Ryza", "expected_label": "rpg"},
    {"text": "Defending humanity against invading gods in Shin Megami Tensei V", "expected_label": "rpg"},
    {"text": "Recruiting powerful allies in Fire Emblem: Three Houses", "expected_label": "rpg"},
    {"text": "Learning magic to save your home in Radiata Stories", "expected_label": "rpg"},
    {"text": "Fighting powerful foes in Nioh 2", "expected_label": "rpg"},
    {"text": "Becoming a royal knight in Final Fantasy XII: The Zodiac Age", "expected_label": "rpg"},
    {"text": "Fighting to free an enslaved people in Tales of Arise", "expected_label": "rpg"},
    {"text": "Exploring ancient tombs in Shadow of the Tomb Raider", "expected_label": "rpg"},
    {"text": "Uncovering dark secrets in Vampire: The Masquerade - Bloodlines", "expected_label": "rpg"},
    {"text": "Restoring the land from darkness in The Legend of Heroes: Trails of Azure", "expected_label": "rpg"},
    {"text": "Protecting a kingdom from monsters in Trials of Mana", "expected_label": "rpg"},
    {"text": "Becoming a hero in Golden Sun: Dark Dawn", "expected_label": "rpg"},
    {"text": "Fighting evil forces in Bravely Default II", "expected_label": "rpg"},
    {"text": "Gathering magical creatures in Monster Crown", "expected_label": "rpg"},
    {"text": "Building a home in Rune Factory 5", "expected_label": "rpg"},
    {"text": "Exploring the lands of Erdrea in Dragon Quest XI S", "expected_label": "rpg"},
    {"text": "Unraveling the mysteries of the Shattering in Elden Ring", "expected_label": "rpg"},
    {"text": "Leading armies to battle in Valkyria Chronicles 4", "expected_label": "rpg"},
    {"text": "Learning the secrets of the abyss in Hollow Knight", "expected_label": "rpg"},
    {"text": "Exploring the mythical floating islands in Sky: Children of the Light", "expected_label": "rpg"},
    {"text": "Unraveling a cosmic conspiracy in Xenoblade Chronicles X", "expected_label": "rpg"},
    {"text": "Mastering martial arts to defeat evil in Yakuza: Like a Dragon", "expected_label": "rpg"},
    {"text": "Restoring the power of the Crystals in Final Fantasy III", "expected_label": "rpg"},
    {"text": "Uncovering an ancient evil in Octopath Traveler II", "expected_label": "rpg"},
    {"text": "Defending the kingdom of Midland in Berserk and the Band of the Hawk", "expected_label": "rpg"},
    {"text": "Exploring the lands of Torna in Xenoblade Chronicles 2", "expected_label": "rpg"},
    {"text": "Building relationships in Blue Reflection", "expected_label": "rpg"},
    {"text": "Fighting corrupted monsters in Ni no Kuni II", "expected_label": "rpg"},
    {"text": "Learning powerful sword techniques in Tales of Berseria", "expected_label": "rpg"},
    {"text": "Restoring a war-torn kingdom in Disgaea 6", "expected_label": "rpg"},
    {"text": "Becoming a legendary Hunter in Monster Hunter Rise", "expected_label": "rpg"},
    {"text": "Exploring a vibrant fantasy world in CrossCode", "expected_label": "rpg"},
    {"text": "Learning to control the power of magic in Atelier Firis", "expected_label": "rpg"},
    {"text": "Defending against invading robots in The Surge 2", "expected_label": "rpg"},
    {"text": "Building alliances in Suikoden II", "expected_label": "rpg"},
    {"text": "Learning about the history of an ancient people in Persona 3", "expected_label": "rpg"},
    {"text": "Fighting demons to save your family in Scarlet Nexus", "expected_label": "rpg"},
    {"text": "Exploring a mysterious land in Grandia II", "expected_label": "rpg"},
    {"text": "Training to become a powerful alchemist in Atelier Shallie", "expected_label": "rpg"},
    {"text": "Rescuing captured villagers in Dark Cloud", "expected_label": "rpg"},
    {"text": "Fighting to become the ultimate hero in Fire Emblem Heroes", "expected_label": "rpg"},
    {"text": "Saving the world from a dark future in Blue Dragon", "expected_label": "rpg"},
    {"text": "Fighting demons and exploring the underworld in Diablo III", "expected_label": "rpg"},
    {"text": "Customizing your party and engaging in tactical battles in Octopath Traveler", "expected_label": "rpg"},
    {"text": "Solving puzzles and navigating dungeons in Persona 5", "expected_label": "rpg"},
    {"text": "Exploring enchanted forests and battling mythical creatures in The Elder Scrolls V: Skyrim", "expected_label": "rpg"},
    {"text": "Choosing your path as a Witcher in The Witcher 3: Wild Hunt", "expected_label": "rpg"},
    {"text": "Saving the world from an apocalyptic prophecy in Chrono Trigger", "expected_label": "rpg"},
    {"text": "Leading a band of adventurers on a quest to reclaim their kingdom in Pillars of Eternity", "expected_label": "rpg"},
    {"text": "Engaging in strategic turn-based combat in Fire Emblem: Three Houses", "expected_label": "rpg"},
    {"text": "Building your settlement and exploring the New World in Pathfinder: Kingmaker", "expected_label": "rpg"},
    {"text": "Building alliances and fighting dragons in Dragon Age: Origins", "expected_label": "rpg"},
    {"text": "Embarking on a journey to save the galaxy in Mass Effect", "expected_label": "rpg"},
    {"text": "Creating and customizing a unique hero in Divinity: Original Sin 2", "expected_label": "rpg"},
    {"text": "Navigating a futuristic dystopia in Cyberpunk 2077", "expected_label": "rpg"},
    {"text": "Restoring peace to the kingdom by reclaiming the throne in Dragon Quest XI", "expected_label": "rpg"},
    {"text": "Battling dark forces to protect the realm in Dark Souls", "expected_label": "rpg"},
    {"text": "Exploring an open world filled with danger and treasure in The Legend of Zelda: Breath of the Wild", "expected_label": "rpg"},
    {"text": "Exploring ancient ruins and unlocking powerful magic in Baldur's Gate", "expected_label": "rpg"},
    {"text": "Unlocking hidden powers and defeating ancient evils in Xenoblade Chronicles", "expected_label": "rpg"},
    {"text": "Leveling up and crafting legendary gear in Final Fantasy XIV", "expected_label": "rpg"},
    {"text": "Solving the mysteries of the Wasteland in Fallout: New Vegas", "expected_label": "rpg"},
    {"text": "Solving mysteries in a haunted mansion in Bloodborne", "expected_label": "rpg"},
    {"text": "Exploring a mystical underwater realm in BioShock", "expected_label": "rpg"},
    {"text": "Navigating political tensions and ancient prophecies in The Outer Worlds", "expected_label": "rpg"},
    {"text": "Traveling through dimensions to stop a cataclysm in Kingdom Hearts III", "expected_label": "rpg"},
    {"text": "Fighting alongside mythical creatures in Shin Megami Tensei", "expected_label": "rpg"},
    {"text": "Uncovering ancient secrets in a vast desert landscape in GreedFall", "expected_label": "rpg"},
    {"text": "Embarking on a quest to retrieve a sacred relic in Sacred 2", "expected_label": "rpg"},
    {"text": "Mastering alchemy to create powerful potions in Atelier Ryza", "expected_label": "rpg"},
    {"text": "Exploring the rich lore of Eorzea in Final Fantasy XIV", "expected_label": "rpg"},
    {"text": "Fighting to reclaim your kingdom in The Banner Saga", "expected_label": "rpg"},
    {"text": "Building a team of heroes to defend the world in Tales of Arise", "expected_label": "rpg"},
    {"text": "Conquering the cursed lands of Lordran in Dark Souls II", "expected_label": "rpg"},
    {"text": "Saving a magical forest from corruption in Ori and the Blind Forest", "expected_label": "rpg"},
    {"text": "Traveling to distant worlds to uncover ancient truths in Star Ocean", "expected_label": "rpg"},
    {"text": "Harnessing elemental powers to defeat enemies in Genshin Impact", "expected_label": "rpg"},
    {"text": "Exploring a post-apocalyptic cityscape in NieR: Automata", "expected_label": "rpg"},
    {"text": "Leading a rebellion against an oppressive empire in Valkyria Chronicles", "expected_label": "rpg"},
    {"text": "Restoring balance to a fractured timeline in Final Fantasy XIII", "expected_label": "rpg"},
    {"text": "Discovering hidden villages in a war-torn land in Suikoden", "expected_label": "rpg"},
    {"text": "Exploring a steampunk world filled with intrigue in Arcanum", "expected_label": "rpg"},
    {"text": "Exploring a post-apocalyptic cityscape in NieR: Automata", "expected_label": "rpg"},
    {"text": "Fighting alongside mythical creatures in Shin Megami Tensei", "expected_label": "rpg"},
    {"text": "Exploring a mystical underwater realm in BioShock", "expected_label": "rpg"},
    {"text": "Leading a rebellion against an oppressive empire in Valkyria Chronicles", "expected_label": "rpg"},
    {"text": "Solving mysteries in a haunted mansion in Bloodborne", "expected_label": "rpg"},
    {"text": "Conquering the cursed lands of Lordran in Dark Souls II", "expected_label": "rpg"},
    {"text": "Building a team of heroes to defend the world in Tales of Arise", "expected_label": "rpg"},
    {"text": "Embarking on a quest to retrieve a sacred relic in Sacred 2", "expected_label": "rpg"},
    {"text": "Fighting to reclaim your kingdom in The Banner Saga", "expected_label": "rpg"},
    {"text": "Mastering alchemy to create powerful potions in Atelier Ryza", "expected_label": "rpg"},
    {"text": "Exploring the rich lore of Eorzea in Final Fantasy XIV", "expected_label": "rpg"},
    {"text": "Harnessing elemental powers to defeat enemies in Genshin Impact", "expected_label": "rpg"},
    {"text": "Discovering hidden villages in a war-torn land in Suikoden", "expected_label": "rpg"},
    {"text": "Uncovering ancient secrets in a vast desert landscape in GreedFall", "expected_label": "rpg"},
    {"text": "Traveling to distant worlds to uncover ancient truths in Star Ocean", "expected_label": "rpg"},
    {"text": "Exploring a steampunk world filled with intrigue in Arcanum", "expected_label": "rpg"},
    {"text": "Navigating political tensions and ancient prophecies in The Outer Worlds", "expected_label": "rpg"},
    {"text": "Saving a magical forest from corruption in Ori and the Blind Forest", "expected_label": "rpg"},
    {"text": "Traveling through dimensions to stop a cataclysm in Kingdom Hearts III", "expected_label": "rpg"},
    {"text": "Restoring balance to a fractured timeline in Final Fantasy XIII", "expected_label": "rpg"},
    {"text": "Exploring a mystical underwater realm in BioShock", "expected_label": "rpg"},
    {"text": "Mastering alchemy to create powerful potions in Atelier Ryza", "expected_label": "rpg"},
    {"text": "Uncovering ancient secrets in a vast desert landscape in GreedFall", "expected_label": "rpg"},
    {"text": "Harnessing elemental powers to defeat enemies in Genshin Impact", "expected_label": "rpg"},
    {"text": "Restoring balance to a fractured timeline in Final Fantasy XIII", "expected_label": "rpg"},
    {"text": "Saving a magical forest from corruption in Ori and the Blind Forest", "expected_label": "rpg"},
    {"text": "Exploring a post-apocalyptic cityscape in NieR: Automata", "expected_label": "rpg"},
    {"text": "Exploring the rich lore of Eorzea in Final Fantasy XIV", "expected_label": "rpg"},
    {"text": "Building a team of heroes to defend the world in Tales of Arise", "expected_label": "rpg"},
    {"text": "Conquering the cursed lands of Lordran in Dark Souls II", "expected_label": "rpg"},
    {"text": "Embarking on a quest to retrieve a sacred relic in Sacred 2", "expected_label": "rpg"},
    {"text": "Fighting alongside mythical creatures in Shin Megami Tensei", "expected_label": "rpg"},
    {"text": "Discovering hidden villages in a war-torn land in Suikoden", "expected_label": "rpg"},
    {"text": "Navigating political tensions and ancient prophecies in The Outer Worlds", "expected_label": "rpg"},
    {"text": "Leading a rebellion against an oppressive empire in Valkyria Chronicles", "expected_label": "rpg"},
    {"text": "Traveling to distant worlds to uncover ancient truths in Star Ocean", "expected_label": "rpg"},
    {"text": "Exploring a steampunk world filled with intrigue in Arcanum", "expected_label": "rpg"},
    {"text": "Solving mysteries in a haunted mansion in Bloodborne", "expected_label": "rpg"},
    {"text": "Traveling through dimensions to stop a cataclysm in Kingdom Hearts III", "expected_label": "rpg"},
    {"text": "Fighting to reclaim your kingdom in The Banner Saga", "expected_label": "rpg"},
    {"text": "Traveling through dimensions to stop a cataclysm in Kingdom Hearts III", "expected_label": "rpg"},
    {"text": "Mastering alchemy to create powerful potions in Atelier Ryza", "expected_label": "rpg"},
    {"text": "Conquering the cursed lands of Lordran in Dark Souls II", "expected_label": "rpg"},
    {"text": "Building a team of heroes to defend the world in Tales of Arise", "expected_label": "rpg"},
    {"text": "Embarking on a quest to retrieve a sacred relic in Sacred 2", "expected_label": "rpg"},
    {"text": "Leading a rebellion against an oppressive empire in Valkyria Chronicles", "expected_label": "rpg"},
    {"text": "Saving a magical forest from corruption in Ori and the Blind Forest", "expected_label": "rpg"},
    {"text": "Exploring a post-apocalyptic cityscape in NieR: Automata", "expected_label": "rpg"},
    {"text": "Exploring a steampunk world filled with intrigue in Arcanum", "expected_label": "rpg"},
    {"text": "Exploring a mystical underwater realm in BioShock", "expected_label": "rpg"},
    {"text": "Navigating political tensions and ancient prophecies in The Outer Worlds", "expected_label": "rpg"},
    {"text": "Solving mysteries in a haunted mansion in Bloodborne", "expected_label": "rpg"},
    {"text": "Harnessing elemental powers to defeat enemies in Genshin Impact", "expected_label": "rpg"},
    {"text": "Discovering hidden villages in a war-torn land in Suikoden", "expected_label": "rpg"},
    {"text": "Traveling to distant worlds to uncover ancient truths in Star Ocean", "expected_label": "rpg"},
]