strategy_data = [
    {"text": "Managing a medieval kingdom in Crusader Kings III", "expected_label": "strategy"},
    {"text": "Commanding armies in epic battles in Total War: Three Kingdoms", "expected_label": "strategy"},
    {"text": "Building and expanding an interstellar empire in Stellaris", "expected_label": "strategy"},
    {"text": "Defending your base against waves of enemies in They Are Billions", "expected_label": "strategy"},
    {"text": "Creating a thriving civilization from scratch in Age of Empires IV", "expected_label": "strategy"},
    {"text": "Developing a sprawling city in Cities: Skylines", "expected_label": "strategy"},
    {"text": "Conquering Europe during the Napoleonic Wars in Total War: Napoleon", "expected_label": "strategy"},
    {"text": "Managing resources and units in a galactic war in StarCraft II", "expected_label": "strategy"},
    {"text": "Leading your nation to victory in Sid Meier's Civilization VI", "expected_label": "strategy"},
    {"text": "Controlling the battlefield in Company of Heroes 2", "expected_label": "strategy"},
    {"text": "Fighting against an alien invasion in XCOM 2", "expected_label": "strategy"},
    {"text": "Navigating political intrigue in Europa Universalis IV", "expected_label": "strategy"},
    {"text": "Controlling the battlefield in Command & Conquer: Generals", "expected_label": "strategy"},
    {"text": "Developing your base and units in Command & Conquer: Red Alert 3", "expected_label": "strategy"},
    {"text": "Managing a growing economy in Anno 1800", "expected_label": "strategy"},
    {"text": "Developing strategic alliances in Galactic Civilizations III", "expected_label": "strategy"},
    {"text": "Planning attacks in real-time combat in Supreme Commander", "expected_label": "strategy"},
    {"text": "Managing feudal Japan in Shogun: Total War", "expected_label": "strategy"},
    {"text": "Developing settlements in Tropico 6", "expected_label": "strategy"},
    {"text": "Protecting your towers in Defense Grid 2", "expected_label": "strategy"},
    {"text": "Expanding an empire in Rise of Nations", "expected_label": "strategy"},
    {"text": "Building a war economy in Stronghold Crusader", "expected_label": "strategy"},
    {"text": "Managing crops and trade in Banished", "expected_label": "strategy"},
    {"text": "Defending humanity against kaiju in Into the Breach", "expected_label": "strategy"},
    {"text": "Building and managing your own empire in Master of Orion", "expected_label": "strategy"},
    {"text": "Planning and executing tactical operations in Jagged Alliance 2", "expected_label": "strategy"},
    {"text": "Managing and growing a mining colony in Surviving Mars", "expected_label": "strategy"},
    {"text": "Defending your castle against waves of enemies in Stronghold", "expected_label": "strategy"},
    {"text": "Balancing resources and developing infrastructure in Frostpunk", "expected_label": "strategy"},
    {"text": "Fighting as different factions in the Warhammer universe in Total War: Warhammer II", "expected_label": "strategy"},
    {"text": "Conquering neighboring tribes in Northgard", "expected_label": "strategy"},
    {"text": "Expanding your territory in Endless Legend", "expected_label": "strategy"},
    {"text": "Controlling massive armies in Halo Wars 2", "expected_label": "strategy"},
    {"text": "Creating and defending settlements in RimWorld", "expected_label": "strategy"},
    {"text": "Building a railway network in Railway Empire", "expected_label": "strategy"},
    {"text": "Managing a global business in Industry Giant II", "expected_label": "strategy"},
    {"text": "Expanding across the solar system in Offworld Trading Company", "expected_label": "strategy"},
    {"text": "Mastering tactics in Fire Emblem: Awakening", "expected_label": "strategy"},
    {"text": "Building an efficient colony in Factorio", "expected_label": "strategy"},
    {"text": "Controlling resources to expand your power in Sins of a Solar Empire", "expected_label": "strategy"},
    {"text": "Balancing diplomacy and warfare in Total War: Attila", "expected_label": "strategy"},
    {"text": "Planning military strategies in Blitzkrieg 2", "expected_label": "strategy"},
    {"text": "Fighting strategic battles in Age of Mythology", "expected_label": "strategy"},
    {"text": "Guiding your civilization to greatness in Sid Meier's Civilization V", "expected_label": "strategy"},
    {"text": "Commanding space fleets in Battlefleet Gothic: Armada", "expected_label": "strategy"},
    {"text": "Managing all aspects of an empire in Endless Space 2", "expected_label": "strategy"},
    {"text": "Building a power grid in Power Grid", "expected_label": "strategy"},
    {"text": "Surviving in an ice-covered world in Frostpunk", "expected_label": "strategy"},
    {"text": "Strategizing naval warfare in Naval War: Arctic Circle", "expected_label": "strategy"},
    {"text": "Managing your kingdom in The Settlers: Rise of an Empire", "expected_label": "strategy"},
    {"text": "Creating a successful empire in Tropico 5", "expected_label": "strategy"},
    {"text": "Leading armies to victory in Romance of the Three Kingdoms XIII", "expected_label": "strategy"},
    {"text": "Navigating trade and exploration in Port Royale 4", "expected_label": "strategy"},
    {"text": "Building an empire in Empire Earth II", "expected_label": "strategy"},
    {"text": "Defending against waves of enemies in Orcs Must Die! 3", "expected_label": "strategy"},
    {"text": "Building and defending a city in Pharaoh", "expected_label": "strategy"},
    {"text": "Expanding your base in Homeworld: Deserts of Kharak", "expected_label": "strategy"},
    {"text": "Building a railroad empire in Railroad Tycoon 3", "expected_label": "strategy"},
    {"text": "Defending your kingdom against invaders in Majesty 2", "expected_label": "strategy"},
    {"text": "Leading troops to battle in Stronghold: Warlords", "expected_label": "strategy"},
    {"text": "Planning city layout in SimCity 3000", "expected_label": "strategy"},
    {"text": "Conquering galaxies in Distant Worlds: Universe", "expected_label": "strategy"},
    {"text": "Commanding an intergalactic empire in Star Wars: Empire at War", "expected_label": "strategy"},
    {"text": "Protecting humanity from extinction in XCOM: Enemy Unknown", "expected_label": "strategy"},
    {"text": "Managing workers and resources in Anno 1404", "expected_label": "strategy"},
    {"text": "Defending your colony from alien threats in Surviving the Aftermath", "expected_label": "strategy"},
    {"text": "Building a profitable city in Tropico 4", "expected_label": "strategy"},
    {"text": "Defending magical towers in Kingdom Rush", "expected_label": "strategy"},
    {"text": "Conquering cities in Endless Legend", "expected_label": "strategy"},
    {"text": "Building and managing a growing medieval city in Banished", "expected_label": "strategy"},
    {"text": "Creating a space colony in Space Colony HD", "expected_label": "strategy"},
    {"text": "Managing an advanced society in Aven Colony", "expected_label": "strategy"},
    {"text": "Expanding an empire with magic in Age of Wonders III", "expected_label": "strategy"},
    {"text": "Managing territory expansion in Victoria II", "expected_label": "strategy"},
    {"text": "Mastering naval battles in Ultimate Admiral: Age of Sail", "expected_label": "strategy"},
    {"text": "Surviving in a zombie-infested world in Rebuild 3", "expected_label": "strategy"},
    {"text": "Defending against fantasy monsters in Wargroove", "expected_label": "strategy"},
    {"text": "Creating an efficient underground factory in Oxygen Not Included", "expected_label": "strategy"},
    {"text": "Fighting for planetary dominance in Warhammer 40,000: Gladius", "expected_label": "strategy"},
    {"text": "Managing a dwarven city in Hammerting", "expected_label": "strategy"},
    {"text": "Expanding across ancient lands in Age of Empires II: Definitive Edition", "expected_label": "strategy"},
    {"text": "Commanding orc armies in Battle for Middle-earth", "expected_label": "strategy"},
    {"text": "Exploring distant galaxies in Stellaris: Nemesis", "expected_label": "strategy"},
    {"text": "Building a base on an alien planet in Planetbase", "expected_label": "strategy"},
    {"text": "Managing interstellar politics in Galactic Civilizations II", "expected_label": "strategy"},
    {"text": "Expanding influence in the medieval world in Imperator: Rome", "expected_label": "strategy"},
    {"text": "Defending against tower climbers in Bloons Tower Defense 6", "expected_label": "strategy"},
    {"text": "Commanding battleships in World of Warships", "expected_label": "strategy"},
    {"text": "Navigating nuclear diplomacy in DEFCON", "expected_label": "strategy"},
    {"text": "Building a transport network in Transport Fever 2", "expected_label": "strategy"},
    {"text": "Fighting galactic empires in Sins of a Solar Empire: Rebellion", "expected_label": "strategy"},
    {"text": "Surviving a nuclear wasteland in Sheltered", "expected_label": "strategy"},
    {"text": "Establishing a growing colony on Mars in Terraformers", "expected_label": "strategy"},
    {"text": "Planning troop movements in Stronghold: Crusader II", "expected_label": "strategy"},
    {"text": "Conquering the ancient world in Total War: Rome II", "expected_label": "strategy"},
    {"text": "Managing complex space stations in Space Haven", "expected_label": "strategy"},
    {"text": "Conquering historical civilizations in Rise of Nations", "expected_label": "strategy"},
    {"text": "Planning elaborate defenses in Stronghold Legends", "expected_label": "strategy"},
    {"text": "Developing your civilization in Age of Empires III", "expected_label": "strategy"},
    {"text": "Commanding medieval armies in Age of Wonders: Planetfall", "expected_label": "strategy"},
    {"text": "Building an efficient colony in RimWorld", "expected_label": "strategy"},
    {"text": "Leading a group of survivors in Frostpunk", "expected_label": "strategy"},
    {"text": "Conquering new territories in Endless Space", "expected_label": "strategy"},
    {"text": "Developing a city in Anno 2205", "expected_label": "strategy"},
    {"text": "Managing an empire in the ancient world in Total War: Troy", "expected_label": "strategy"},
    {"text": "Building and defending a kingdom in Kingdoms Reborn", "expected_label": "strategy"},
    {"text": "Planning resource management in Emperor: Rise of the Middle Kingdom", "expected_label": "strategy"},
    {"text": "Strategizing your army's movements in Command & Conquer 4", "expected_label": "strategy"},
    {"text": "Developing settlements in a fantasy world in SpellForce 3", "expected_label": "strategy"},
    {"text": "Constructing buildings to strengthen your empire in Age of Wonders: Shadow Magic", "expected_label": "strategy"},
    {"text": "Fighting space wars in Homeworld Remastered", "expected_label": "strategy"},
    {"text": "Managing the growth of your village in The Settlers III", "expected_label": "strategy"},
    {"text": "Building a thriving metropolis in SimCity 4", "expected_label": "strategy"},
    {"text": "Establishing a powerful realm in Stronghold 2", "expected_label": "strategy"},
    {"text": "Strategizing interstellar exploration in Galactic Civilizations IV", "expected_label": "strategy"},
    {"text": "Defending against robotic invaders in They Are Billions", "expected_label": "strategy"},
    {"text": "Building alliances in political intrigue in Hearts of Iron IV", "expected_label": "strategy"},
    {"text": "Fighting monsters to expand your kingdom in Battle Realms", "expected_label": "strategy"},
    {"text": "Crafting new cities in Pharaoh: Cleopatra", "expected_label": "strategy"},
    {"text": "Controlling powerful armies in the 19th century in Victoria 3", "expected_label": "strategy"},
    {"text": "Creating a trade network in Patrician IV", "expected_label": "strategy"},
    {"text": "Managing sea voyages and battles in Port Royale 3", "expected_label": "strategy"},
    {"text": "Expanding colonies in an icy apocalypse in Frostpunk: The Last Autumn", "expected_label": "strategy"},
    {"text": "Establishing an economy in a new settlement in Tropico 3", "expected_label": "strategy"},
    {"text": "Commanding troops in the Vietnam War in Men of War: Vietnam", "expected_label": "strategy"},
    {"text": "Exploring new lands while managing resources in Northgard", "expected_label": "strategy"},
    {"text": "Protecting your people from environmental collapse in Surviving the Aftermath", "expected_label": "strategy"},
    {"text": "Building a new world in Aven Colony", "expected_label": "strategy"},
    {"text": "Developing a base and commanding armies in Dark Colony", "expected_label": "strategy"},
    {"text": "Building a new colony on alien planets in Outpost 2", "expected_label": "strategy"},
    {"text": "Leading an alien empire in Sid Meier's Alpha Centauri", "expected_label": "strategy"},
    {"text": "Defending the homeland in Homeworld: Cataclysm", "expected_label": "strategy"},
    {"text": "Balancing growth and exploration in Emperor: Battle for Dune", "expected_label": "strategy"},
    {"text": "Developing advanced civilizations in Civilization: Beyond Earth", "expected_label": "strategy"},
    {"text": "Creating a thriving colony in Surviving Mars: Green Planet", "expected_label": "strategy"},
    {"text": "Strategically managing water resources in Imagine Earth", "expected_label": "strategy"},
    {"text": "Defending the underworld in Dungeon Keeper 2", "expected_label": "strategy"},
    {"text": "Conquering the stars in Space Empires V", "expected_label": "strategy"},
    {"text": "Controlling industrial power in Anno 1800", "expected_label": "strategy"},
    {"text": "Mastering city-building in Banished", "expected_label": "strategy"},
    {"text": "Developing rural areas in SimFarm", "expected_label": "strategy"},
    {"text": "Creating intricate trade routes in Port Royale 2", "expected_label": "strategy"},
    {"text": "Defending against the undead in Rebuild: Gangs of Deadsville", "expected_label": "strategy"},
    {"text": "Mastering resource allocation in King Arthur: The Role-Playing Wargame", "expected_label": "strategy"},
    {"text": "Conquering the galaxy in Imperium Galactica II", "expected_label": "strategy"},
    {"text": "Expanding into uncharted regions in Star Ruler 2", "expected_label": "strategy"},
    {"text": "Developing tactical operations in Blitzkrieg", "expected_label": "strategy"},
    {"text": "Conquering islands in The Settlers: Heritage of Kings", "expected_label": "strategy"},
    {"text": "Defending against an alien onslaught in Alien Nations", "expected_label": "strategy"},
    {"text": "Leading a samurai army in Kessen III", "expected_label": "strategy"},
    {"text": "Navigating global diplomacy in Shadow President", "expected_label": "strategy"},
    {"text": "Constructing epic buildings in Caesar IV", "expected_label": "strategy"},
    {"text": "Controlling vast regions in Supreme Ruler 2020", "expected_label": "strategy"},
    {"text": "Managing a space colony on Mars in Sol 0: Mars Colonization", "expected_label": "strategy"},
    {"text": "Defending against hordes of demons in Hell Architect", "expected_label": "strategy"},
    {"text": "Building a medieval empire in Grand Ages: Medieval", "expected_label": "strategy"},
    {"text": "Balancing economic growth in Capitalism Plus", "expected_label": "strategy"},
    {"text": "Surviving in the tundra of Planetbase", "expected_label": "strategy"},
    {"text": "Managing a corporate empire in Offworld Trading Company", "expected_label": "strategy"},
    {"text": "Commanding troops in Commandos 3", "expected_label": "strategy"},
    {"text": "Building a water park in RollerCoaster Tycoon 3: Soaked!", "expected_label": "strategy"},
    {"text": "Fighting against hostile empires in Supreme Commander: Forged Alliance", "expected_label": "strategy"},
    {"text": "Conquering different civilizations in Age of Wonders: Planetfall", "expected_label": "strategy"},
    {"text": "Creating interplanetary trade networks in AI War 2", "expected_label": "strategy"},
    {"text": "Developing new species in Spore: Galactic Adventures", "expected_label": "strategy"},
    {"text": "Building a grand dynasty in Romance of the Three Kingdoms XIV", "expected_label": "strategy"},
    {"text": "Constructing futuristic bases in Planetary Annihilation", "expected_label": "strategy"},
    {"text": "Defending against a massive invasion in FortressCraft Evolved!", "expected_label": "strategy"},
    {"text": "Managing resources during World War II in Order of Battle: Pacific", "expected_label": "strategy"},
    {"text": "Controlling a galactic federation in The Last Federation", "expected_label": "strategy"},
    {"text": "Building a future city in Anno 2070", "expected_label": "strategy"},
    {"text": "Fighting tactical battles in Star Wars: Galactic Battlegrounds", "expected_label": "strategy"},
    {"text": "Planning city layout and production in Tropico 6", "expected_label": "strategy"},
    {"text": "Strategizing intergalactic warfare in Master of Orion: Conquer the Stars", "expected_label": "strategy"},
    {"text": "Conquering medieval kingdoms in Total War Saga: Thrones of Britannia", "expected_label": "strategy"},
    {"text": "Surviving in a harsh world in Surviving the Aftermath", "expected_label": "strategy"},
    {"text": "Commanding fleets in interstellar wars in Distant Worlds 2", "expected_label": "strategy"},
    {"text": "Developing a community in a resource-scarce environment in RimWorld", "expected_label": "strategy"},
    {"text": "Managing resources in a frozen world in Frostpunk", "expected_label": "strategy"},
    {"text": "Expanding a kingdom in Majesty: The Fantasy Kingdom Sim", "expected_label": "strategy"},
    {"text": "Mastering combat strategy in Warhammer 40,000: Dawn of War II", "expected_label": "strategy"},
    {"text": "Establishing a thriving city in Tropico", "expected_label": "strategy"},
    {"text": "Controlling an alien race in Sins of a Solar Empire", "expected_label": "strategy"},
    {"text": "Commanding battles in a dystopian world in Grey Goo", "expected_label": "strategy"},
    {"text": "Managing a post-apocalyptic society in Sheltered 2", "expected_label": "strategy"},
    {"text": "Navigating an ancient political landscape in Imperator: Rome", "expected_label": "strategy"},
    {"text": "Fighting for control in the galaxy in Homeworld 3", "expected_label": "strategy"},
    {"text": "Building and defending cities in Ancient Egypt in Pharaoh", "expected_label": "strategy"},
    {"text": "Establishing a thriving economy in Anno 1404", "expected_label": "strategy"},
    {"text": "Commanding fleets in intergalactic wars in Battlefleet Gothic Armada 2", "expected_label": "strategy"},
    {"text": "Developing a new home on a strange world in Planetbase", "expected_label": "strategy"},
    {"text": "Constructing a futuristic colony in Surviving Mars", "expected_label": "strategy"},
    {"text": "Navigating alliances in Total War: Medieval II", "expected_label": "strategy"}
]
