horror_data = [
    {"text": "Exploring a haunted mansion in Resident Evil", "expected_label": "horror"},
    {"text": "Surviving the terror of Silent Hill's eerie atmosphere", "expected_label": "horror"},
    {"text": "Hiding from deadly monsters in Amnesia: The Dark Descent", "expected_label": "horror"},
    {"text": "Fighting back against zombies in Left 4 Dead", "expected_label": "horror"},
    {"text": "Escaping the clutches of The Entity in Dead by Daylight", "expected_label": "horror"},
    {"text": "Uncovering the secrets of a cursed town in Alan Wake", "expected_label": "horror"},
    {"text": "Running from terrifying animatronics in Five Nights at Freddy's", "expected_label": "horror"},
    {"text": "Battling nightmarish creatures in Bloodborne", "expected_label": "horror"},
    {"text": "Solving puzzles while avoiding horrors in The Evil Within", "expected_label": "horror"},
    {"text": "Surviving a dystopian underwater city in BioShock", "expected_label": "horror"},
    {"text": "Escaping an alien predator in Alien: Isolation", "expected_label": "horror"},
    {"text": "Exploring a cursed family estate in Outlast", "expected_label": "horror"},
    {"text": "Fighting off hordes of infected in Dying Light", "expected_label": "horror"},
    {"text": "Surviving in the wilderness while being hunted in The Forest", "expected_label": "horror"},
    {"text": "Escaping supernatural horrors in Layers of Fear", "expected_label": "horror"},
    {"text": "Investigating paranormal activities in Phasmophobia", "expected_label": "horror"},
    {"text": "Fighting through hellish landscapes in Doom 3", "expected_label": "horror"},
    {"text": "Exploring a haunted ship in Man of Medan", "expected_label": "horror"},
    {"text": "Surviving psychological terror in Soma", "expected_label": "horror"},
    {"text": "Fighting against vampires in Redfall", "expected_label": "horror"},
    {"text": "Exploring a haunted mansion in Resident Evil", "expected_label": "horror"},
    {"text": "Surviving the terror of Silent Hill's eerie atmosphere", "expected_label": "horror"},
    {"text": "Hiding from deadly monsters in Amnesia: The Dark Descent", "expected_label": "horror"},
    {"text": "Fighting back against zombies in Left 4 Dead", "expected_label": "horror"},
    {"text": "Escaping the clutches of The Entity in Dead by Daylight", "expected_label": "horror"},
    {"text": "Uncovering the secrets of a cursed town in Alan Wake", "expected_label": "horror"},
    {"text": "Running from terrifying animatronics in Five Nights at Freddy's", "expected_label": "horror"},
    {"text": "Battling nightmarish creatures in Bloodborne", "expected_label": "horror"},
    {"text": "Solving puzzles while avoiding horrors in The Evil Within", "expected_label": "horror"},
    {"text": "Surviving a dystopian underwater city in BioShock", "expected_label": "horror"},
    {"text": "Escaping an alien predator in Alien: Isolation", "expected_label": "horror"},
    {"text": "Exploring a cursed family estate in Outlast", "expected_label": "horror"},
    {"text": "Fighting off hordes of infected in Dying Light", "expected_label": "horror"},
    {"text": "Surviving in the wilderness while being hunted in The Forest", "expected_label": "horror"},
    {"text": "Escaping supernatural horrors in Layers of Fear", "expected_label": "horror"},
    {"text": "Investigating paranormal activities in Phasmophobia", "expected_label": "horror"},
    {"text": "Fighting through hellish landscapes in Doom 3", "expected_label": "horror"},
    {"text": "Exploring a haunted ship in Man of Medan", "expected_label": "horror"},
    {"text": "Surviving psychological terror in Soma", "expected_label": "horror"},
    {"text": "Fighting against vampires in Redfall", "expected_label": "horror"},
    {"text": "Escaping a cursed monastery filled with restless spirits in Shadows of the Abbey", "expected_label": "horror"},
    {"text": "Surviving the horrors of a sentient AI in Abandoned Protocols", "expected_label": "horror"},
    {"text": "Exploring an endless labyrinth of shifting walls in The Infinite Maze", "expected_label": "horror"},
    {"text": "Uncovering ancient rituals in a forgotten desert temple in Sands of Fear", "expected_label": "horror"},
    {"text": "Trapped in a haunted amusement park with no escape in Nightmare Carousel", "expected_label": "horror"},
    {"text": "Fleeing from a bloodthirsty monster in a collapsing subway system in Deep Tunnels", "expected_label": "horror"},
    {"text": "Surviving the terror of mutant experiments in Biohorror Facility", "expected_label": "horror"},
    {"text": "Exploring a cursed lighthouse during a raging storm in The Beacon of Dread", "expected_label": "horror"},
    {"text": "Avoiding traps set by a vengeful ghost in Whispering Corridors", "expected_label": "horror"},
    {"text": "Facing an ancient evil lurking beneath a remote island in The Depths Below", "expected_label": "horror"},
    {"text": "Escaping a mansion filled with deadly puzzles in Mansion of the Forgotten", "expected_label": "horror"},
    {"text": "Surviving the horrors of a post-apocalyptic city in Silent Streets", "expected_label": "horror"},
    {"text": "Exploring a haunted forest that changes as you wander in Eternal Woods", "expected_label": "horror"},
    {"text": "Investigating a series of paranormal disappearances in Ghost Town Mysteries", "expected_label": "horror"},
    {"text": "Fighting off hordes of shadowy creatures in Midnight Siege", "expected_label": "horror"},
    {"text": "Uncovering a cursed artifact in a remote archaeological site in Relic of Terror", "expected_label": "horror"},
    {"text": "Avoiding the gaze of a malevolent entity in Hall of Mirrors", "expected_label": "horror"},
    {"text": "Surviving a haunted winter lodge with no communication in Frostbite Horror", "expected_label": "horror"},
    {"text": "Exploring an abandoned carnival filled with malevolent clowns in Circus of Nightmares", "expected_label": "horror"},
    {"text": "Solving cryptic clues to escape a cursed train in Phantom Express", "expected_label": "horror"},
    {"text": "Unraveling the mystery of a haunted orphanage in Orphans of the Void", "expected_label": "horror"},
    {"text": "Exploring an ancient crypt guarded by vengeful spirits in Tomb of the Lost", "expected_label": "horror"},
    {"text": "Surviving the horrors of a cursed swamp in Swamp of Despair", "expected_label": "horror"},
    {"text": "Avoiding the wrath of a shadowy figure in The Stalker", "expected_label": "horror"},
    {"text": "Escaping a decaying space station overrun by alien parasites in Parasite Horizon", "expected_label": "horror"},
    {"text": "Fleeing from monstrous beings in a frozen wasteland in Arctic Terror", "expected_label": "horror"},
    {"text": "Investigating a series of eerie disappearances in a coastal village in Shadows by the Shore", "expected_label": "horror"},
    {"text": "Surviving a night trapped in an abandoned prison in Cells of Dread", "expected_label": "horror"},
    {"text": "Uncovering ancient curses in a forgotten jungle temple in The Vines of Fear", "expected_label": "horror"},
    {"text": "Fighting off creatures in a post-apocalyptic metro system in Below the Surface", "expected_label": "horror"},
    {"text": "Hiding from an invisible predator in The Watcher's Realm", "expected_label": "horror"},
    {"text": "Exploring a ghost ship lost at sea in The Eternal Drift", "expected_label": "horror"},
    {"text": "Unraveling a dark experiment gone wrong in Project Nightmare", "expected_label": "horror"},
    {"text": "Surviving the psychological terrors of a forgotten asylum in Fractured Minds", "expected_label": "horror"},
    {"text": "Escaping a haunted graveyard under the light of a blood moon in Crimson Graves", "expected_label": "horror"},
    {"text": "Avoiding monstrous horrors in the depths of an abandoned mine in The Abyss Below", "expected_label": "horror"},
    {"text": "Solving the mystery of a cursed painting in The Artist's Torment", "expected_label": "horror"},
    {"text": "Exploring a mansion frozen in time in Echoes of the Past", "expected_label": "horror"},
    {"text": "Facing nightmares that come alive in Dreamcatcher", "expected_label": "horror"},
    {"text": "Uncovering the truth about an ancient evil beneath a cathedral in The Hollow Sanctum", "expected_label": "horror"},
    {"text": "Unraveling the mystery of a cursed theater in Curtains of Dread", "expected_label": "horror"},
    {"text": "Fighting against shapeshifting entities in Mirrors of Fear", "expected_label": "horror"},
    {"text": "Escaping an otherworldly labyrinth in The Endless Corridors", "expected_label": "horror"},
    {"text": "Surviving the wrath of a spectral conductor in Ghost Train", "expected_label": "horror"},
    {"text": "Investigating strange occurrences in a moonlit forest in Whispers of the Pines", "expected_label": "horror"},
    {"text": "Avoiding detection by malevolent dolls in The Toymaker's Curse", "expected_label": "horror"},
    {"text": "Exploring a derelict asylum haunted by memories of the past in Shadows of Sanity", "expected_label": "horror"},
    {"text": "Facing terror in an abandoned circus in Carnival of the Damned", "expected_label": "horror"},
    {"text": "Hiding from a relentless stalker in The Hollowed Night", "expected_label": "horror"},
    {"text": "Exploring a haunted train station lost in time in Echoes on the Rails", "expected_label": "horror"},
    {"text": "Unraveling a mystery in a snowy mountain village in Frostbound Horror", "expected_label": "horror"},
    {"text": "Surviving the horrors of a cursed playground in Children's Shadows", "expected_label": "horror"},
    {"text": "Escaping a sunken city filled with aquatic monstrosities in Abyssal Ruins", "expected_label": "horror"},
    {"text": "Investigating a haunted photography studio in Frames of Terror", "expected_label": "horror"},
    {"text": "Surviving the horrors of a collapsing multiverse in Fractured Dimensions", "expected_label": "horror"},
    {"text": "Avoiding a cursed scarecrow in Fields of Silence", "expected_label": "horror"},
    {"text": "Fighting the embodiment of fear in the dreamworld in Night Terrors", "expected_label": "horror"},
    {"text": "Uncovering the truth behind cursed rituals in Rituals of the Forgotten", "expected_label": "horror"},
    {"text": "Escaping a sentient forest determined to trap its victims in Roots of the Damned", "expected_label": "horror"},
    {"text": "Surviving a night in a haunted fishing village in Tides of Fear", "expected_label": "horror"},
    {"text": "Uncovering dark secrets in a cursed monastery in Shadows of the Cross", "expected_label": "horror"},
    {"text": "Escaping from a ghostly warden in The Prison of Souls", "expected_label": "horror"},
    {"text": "Investigating a forgotten sanatorium hidden deep in the mountains in Silent Asylum", "expected_label": "horror"},
    {"text": "Facing ancient evils unearthed in a remote desert in Sandstorm of the Damned", "expected_label": "horror"},
    {"text": "Surviving a night of terror in a haunted school in Lessons of Fear", "expected_label": "horror"},
    {"text": "Fighting shadowy creatures in an abandoned cathedral in Hollow Sanctuary", "expected_label": "horror"},
    {"text": "Escaping a sentient mansion bent on devouring its guests in The Living House", "expected_label": "horror"},
    {"text": "Unraveling the mystery of a cursed mirror in Reflections of the Abyss", "expected_label": "horror"},
    {"text": "Surviving a frozen tundra plagued by spectral wolves in Frosted Wraiths", "expected_label": "horror"},
    {"text": "Exploring a forgotten city beneath the sea in The Drowned Empire", "expected_label": "horror"},
    {"text": "Avoiding the gaze of a malevolent painting in The Watchful Canvas", "expected_label": "horror"},
    {"text": "Facing unspeakable horrors in a derelict spaceship in Void's Embrace", "expected_label": "horror"},
    {"text": "Hiding from creatures that hunt by sound in Silent Predators", "expected_label": "horror"},
    {"text": "Solving the mystery of a cursed library in Pages of the Forgotten", "expected_label": "horror"},
    {"text": "Escaping the grasp of an ancient sea creature in The Kraken's Wrath", "expected_label": "horror"},
    {"text": "Surviving an endless maze filled with deadly traps in Labyrinth of Shadows", "expected_label": "horror"},
    {"text": "Fighting against a plague of undead in The Blackened Plague", "expected_label": "horror"},
    {"text": "Exploring a cursed carnival in Midnight Fairground", "expected_label": "horror"},
    {"text": "Uncovering horrors lurking in the misty docks of Port of Shadows", "expected_label": "horror"},
    {"text": "Escaping a deadly crypt haunted by restless spirits in Gravekeeper's Curse", "expected_label": "horror"},
    {"text": "Surviving the horrors of Resident Evil in its terrifying world.", "expected_label": "horror"},
    {"text": "Exploring the chilling environment of Silent Hill.", "expected_label": "horror"},
    {"text": "Uncovering dark secrets in Amnesia: The Dark Descent.", "expected_label": "horror"},
    {"text": "Hiding from unspeakable terror in Dead by Daylight.", "expected_label": "horror"},
    {"text": "Facing supernatural threats in Outlast.", "expected_label": "horror"},
    {"text": "Investigating a haunted locale in Five Nights at Freddy's.", "expected_label": "horror"},
    {"text": "Surviving the nightmarish creatures of The Evil Within.", "expected_label": "horror"},
    {"text": "Escaping deadly encounters in Alien: Isolation.", "expected_label": "horror"},
    {"text": "Discovering the twisted story behind Dying Light.", "expected_label": "horror"},
    {"text": "Fighting for survival in the eerie world of The Forest.", "expected_label": "horror"},
    {"text": "Exploring the haunted corridors in Layers of Fear.", "expected_label": "horror"},
    {"text": "Surviving paranormal investigations in Phasmophobia.", "expected_label": "horror"},
    {"text": "Unraveling psychological mysteries in Soma.", "expected_label": "horror"},
    {"text": "Fighting grotesque monsters in Bloodborne.", "expected_label": "horror"},
    {"text": "Escaping supernatural threats aboard the Man of Medan.", "expected_label": "horror"},
    {"text": "Facing moral dilemmas in Until Dawn.", "expected_label": "horror"},
    {"text": "Investigating eldritch horrors in Call of Cthulhu.", "expected_label": "horror"},
    {"text": "Running from a faceless nightmare in Slender: The Eight Pages.", "expected_label": "horror"},
    {"text": "Exploring a cursed forest in Darkwood.", "expected_label": "horror"},
    {"text": "Hiding from childhood fears in Little Nightmares.", "expected_label": "horror"},
    {"text": "Surviving the ghostly apparitions of Visage.", "expected_label": "horror"},
    {"text": "Facing otherworldly terror in P.T.", "expected_label": "horror"},
    {"text": "Capturing spirits with a camera in Fatal Frame.", "expected_label": "horror"},
    {"text": "Resisting madness in Eternal Darkness: Sanity's Requiem.", "expected_label": "horror"},
    {"text": "Solving crimes while battling fear in Condemned: Criminal Origins.", "expected_label": "horror"},
    {"text": "Fighting necromorphs in Dead Space.", "expected_label": "horror"},
    {"text": "Uncovering the darkness within in Alan Wake.", "expected_label": "horror"},
    {"text": "Surviving the tunnels in Metro 2033.", "expected_label": "horror"},
    {"text": "Investigating haunting technology in Observer.", "expected_label": "horror"},
    {"text": "Battling eerie forces in Hunt: Showdown.", "expected_label": "horror"},
    {"text": "Making critical choices in The Quarry.", "expected_label": "horror"},
    {"text": "Exploring cursed ruins in The Dark Pictures Anthology: House of Ashes.", "expected_label": "horror"},
    {"text": "Facing alien horrors in Prey.", "expected_label": "horror"},
    {"text": "Exploring the depths of a haunted ocean in Narcosis.", "expected_label": "horror"},
    {"text": "Uncovering familial curses in Black Mirror.", "expected_label": "horror"},
    {"text": "Fighting off gory nightmares in Agony.", "expected_label": "horror"},
    {"text": "Surviving a deadly hunting game in The Texas Chain Saw Massacre.", "expected_label": "horror"},
    {"text": "Battling demonic forces in Devil Daggers.", "expected_label": "horror"},
    {"text": "Exploring the haunted grounds of White Day: A Labyrinth Named School.", "expected_label": "horror"},
    {"text": "Facing cursed rituals in Maid of Sker.", "expected_label": "horror"},
    {"text": "Running from cursed memories in Detention.", "expected_label": "horror"},
    {"text": "Escaping the horrors of a nuclear wasteland in Stalker: Shadow of Chernobyl.", "expected_label": "horror"},
    {"text": "Solving the mystery of a ghost ship in Returnal.", "expected_label": "horror"},
    {"text": "Defending against swarms of zombies in World War Z.", "expected_label": "horror"},
    {"text": "Exploring supernatural depths in Subnautica: Below Zero.", "expected_label": "horror"},
    {"text": "Uncovering haunted family secrets in What Remains of Edith Finch.", "expected_label": "horror"},
    {"text": "Solving paranormal mysteries in Oxenfree.", "expected_label": "horror"},
    {"text": "Surviving supernatural threats in Alan Wake 2.", "expected_label": "horror"},
    {"text": "Exploring a cursed amusement park in The Park.", "expected_label": "horror"},
    {"text": "Facing your fears in The Medium.", "expected_label": "horror"},
    {"text": "Fighting supernatural forces in Control: AWE.", "expected_label": "horror"},
    {"text": "Surviving psychological terror in Hellblade: Senua's Sacrifice.", "expected_label": "horror"},
    {"text": "Unraveling dark secrets in Pathologic 2.", "expected_label": "horror"},
    {"text": "Defending against ghostly invaders in Luigi's Mansion 3.", "expected_label": "horror"},
    {"text": "Escaping haunted hotels in Dark Fall: The Journal.", "expected_label": "horror"},
    {"text": "Exploring a world of nightmares in Dreams in the Witch House.", "expected_label": "horror"},
    {"text": "Surviving cursed mansions in Eternal Threads.", "expected_label": "horror"},
    {"text": "Facing cursed enemies in Dark Souls.", "expected_label": "horror"},
    {"text": "Exploring haunted towns in Siren: Blood Curse.", "expected_label": "horror"},
    {"text": "Uncovering the horrors of an evil AI in Observation.", "expected_label": "horror"},
    {"text": "Exploring haunted crypts in Monstrum.", "expected_label": "horror"},
    {"text": "Escaping ghostly threats in Pacify.", "expected_label": "horror"},
    {"text": "Defending humanity from cursed relics in Malum.", "expected_label": "horror"},
    {"text": "Surviving supernatural forces in The Sinking City.", "expected_label": "horror"},
    {"text": "Exploring haunted swamps in Witch Hunt.", "expected_label": "horror"},
    {"text": "Uncovering cursed stories in Stories Untold.", "expected_label": "horror"},
    {"text": "Solving twisted puzzles in The Room: Old Sins.", "expected_label": "horror"},
    {"text": "Exploring a nightmare realm in Tormented Souls.", "expected_label": "horror"},
    {"text": "Escaping a cursed lighthouse in Fear the Light.", "expected_label": "horror"},
    {"text": "Facing ancient evils in Lovecraft's Untold Stories.", "expected_label": "horror"},
    {"text": "Defending against demonic invasions in Doom 3.", "expected_label": "horror"},
    {"text": "Exploring cursed islands in Sunless Sea.", "expected_label": "horror"},
    {"text": "Surviving a haunted library in White Night.", "expected_label": "horror"},
    {"text": "Escaping ghostly apparitions in Knock-Knock.", "expected_label": "horror"},
    {"text": "Facing supernatural threats in The Dark Occult.", "expected_label": "horror"},
    {"text": "Exploring cursed tunnels in Lost in Vivo.", "expected_label": "horror"},
    {"text": "Solving a haunted mystery in The Painscreek Killings.", "expected_label": "horror"},
    {"text": "Fighting supernatural beings in Ghostwire: Tokyo.", "expected_label": "horror"},
    {"text": "Unraveling psychological terror in Inscryption.", "expected_label": "horror"},
    {"text": "Facing your fears in Don't Knock Twice.", "expected_label": "horror"},
    {"text": "Exploring ghostly depths in The Beast Inside.", "expected_label": "horror"},
    {"text": "Surviving haunted museums in Haunt Chaser.", "expected_label": "horror"},
    {"text": "Fighting evil entities in Devotion.", "expected_label": "horror"},
    {"text": "Exploring cursed spaceships in Dead Effect 2.", "expected_label": "horror"},
    {"text": "Escaping terrifying AI in Routine.", "expected_label": "horror"},
    {"text": "Unraveling dark mysteries in The Cat Lady.", "expected_label": "horror"},
    {"text": "Surviving cursed forests in Blair Witch.", "expected_label": "horror"},
    {"text": "Exploring haunted boats in The Boatman's Song.", "expected_label": "horror"},
    {"text": "Defending against swarms of cursed creatures in The Blackout Club.", "expected_label": "horror"},
    {"text": "Uncovering supernatural conspiracies in The Council.", "expected_label": "horror"},
    {"text": "Exploring haunted corridors in Resident Evil 2 Remake.", "expected_label": "horror"},
    {"text": "Uncovering the mysteries of the fog in Silent Hill 2.", "expected_label": "horror"},
    {"text": "Surviving the terror of Amnesia: Rebirth.", "expected_label": "horror"},
    {"text": "Fleeing relentless killers in Dead by Daylight.", "expected_label": "horror"},
    {"text": "Escaping the twisted experiments in Outlast 2.", "expected_label": "horror"},
    {"text": "Facing animatronic horrors in Five Nights at Freddy's: Sister Location.", "expected_label": "horror"},
    {"text": "Unraveling supernatural mysteries in The Evil Within 2.", "expected_label": "horror"},
    {"text": "Surviving an alien predator in Alien: Isolation.", "expected_label": "horror"},
    {"text": "Exploring a quarantined city in Dying Light 2: Stay Human.", "expected_label": "horror"},
    {"text": "Building defenses against cannibal tribes in The Forest.", "expected_label": "horror"},
    {"text": "Walking through psychological horrors in Layers of Fear 2.", "expected_label": "horror"},
    {"text": "Investigating paranormal activities in Phasmophobia.", "expected_label": "horror"},
    {"text": "Facing underwater dread in Soma.", "expected_label": "horror"},
    {"text": "Battling grotesque creatures in Bloodborne.", "expected_label": "horror"},
    {"text": "Uncovering maritime horror in The Dark Pictures Anthology: Man of Medan.", "expected_label": "horror"},
    {"text": "Making life-or-death decisions in Until Dawn.", "expected_label": "horror"},
    {"text": "Investigating eldritch horrors in Call of Cthulhu: Dark Corners of the Earth.", "expected_label": "horror"},
    {"text": "Evading a faceless terror in Slender: The Arrival.", "expected_label": "horror"},
    {"text": "Surviving the cursed woods in Darkwood.", "expected_label": "horror"},
    {"text": "Escaping nightmare creatures in Little Nightmares 2.", "expected_label": "horror"},
    {"text": "Investigating ghostly occurrences in Visage.", "expected_label": "horror"},
    {"text": "Exploring a haunted demo in P.T.", "expected_label": "horror"},
    {"text": "Capturing supernatural entities in Fatal Frame: Maiden of Black Water.", "expected_label": "horror"},
    {"text": "Battling insanity in Eternal Darkness: Sanity's Requiem.", "expected_label": "horror"},
    {"text": "Solving crimes amidst fear in Condemned 2: Bloodshot.", "expected_label": "horror"},
    {"text": "Fighting necromorphs in Dead Space 2.", "expected_label": "horror"},
    {"text": "Uncovering the darkness in Alan Wake: American Nightmare.", "expected_label": "horror"},
    {"text": "Surviving mutant-infested tunnels in Metro: Last Light.", "expected_label": "horror"},
    {"text": "Exploring haunting cyber worlds in Observer: System Redux.", "expected_label": "horror"},
    {"text": "Facing terrifying enemies in Hunt: Showdown.", "expected_label": "horror"},
    {"text": "Making tough choices in The Quarry.", "expected_label": "horror"},
    {"text": "Surviving horrific rituals in The Dark Pictures Anthology: House of Ashes.", "expected_label": "horror"},
    {"text": "Escaping horrifying clutches in Prey: Mooncrash.", "expected_label": "horror"},
    {"text": "Exploring underwater terror in Narcosis.", "expected_label": "horror"},
    {"text": "Uncovering sinister family secrets in Black Mirror.", "expected_label": "horror"},
    {"text": "Fighting twisted nightmares in Agony Unrated.", "expected_label": "horror"},
    {"text": "Surviving slashers in The Texas Chain Saw Massacre Game.", "expected_label": "horror"},
    {"text": "Fending off endless terror in Devil Daggers.", "expected_label": "horror"},
    {"text": "Exploring cursed schools in White Day: A Labyrinth Named School.", "expected_label": "horror"},
    {"text": "Surviving folk horror in Maid of Sker.", "expected_label": "horror"},
    {"text": "Escaping a haunted village in Detention.", "expected_label": "horror"},
    {"text": "Fighting irradiated horrors in Stalker: Call of Pripyat.", "expected_label": "horror"},
    {"text": "Solving ghost ship mysteries in Returnal.", "expected_label": "horror"},
    {"text": "Fending off hordes of zombies in World War Z: Aftermath.", "expected_label": "horror"},
    {"text": "Diving into icy waters of fear in Subnautica: Below Zero.", "expected_label": "horror"},
    {"text": "Uncovering the truth in haunted family homes in What Remains of Edith Finch.", "expected_label": "horror"},
    {"text": "Solving eerie riddles in Oxenfree 2: Lost Signals.", "expected_label": "horror"},
    {"text": "Surviving the darkness of Alan Wake 2.", "expected_label": "horror"},
    {"text": "Exploring abandoned attractions in The Park.", "expected_label": "horror"},
    {"text": "Unraveling spiritual enigmas in The Medium.", "expected_label": "horror"},
    {"text": "Fighting otherworldly threats in Control: Ultimate Edition.", "expected_label": "horror"},
    {"text": "Facing hallucinations in Hellblade: Senua's Sacrifice.", "expected_label": "horror"},
    {"text": "Struggling with sickness and fear in Pathologic Classic HD.", "expected_label": "horror"},
    {"text": "Exploring haunted mansions in Luigi's Mansion: Dark Moon.", "expected_label": "horror"},
    {"text": "Solving terrifying puzzles in Dark Fall: Lost Souls.", "expected_label": "horror"},
    {"text": "Walking the dreams of terror in Dreams in the Witch House.", "expected_label": "horror"},
    {"text": "Surviving intertwined timelines in Eternal Threads.", "expected_label": "horror"},
    {"text": "Facing your inner fears in Dark Souls 3.", "expected_label": "horror"},
    {"text": "Exploring cursed villages in Siren: New Translation.", "expected_label": "horror"},
    {"text": "Uncovering AI horrors in Observation.", "expected_label": "horror"},
    {"text": "Running from unknown forces in Monstrum 2.", "expected_label": "horror"},
    {"text": "Escaping malicious spirits in Pacify.", "expected_label": "horror"},
    {"text": "Facing demonic threats in Malum: Dark Terrors.", "expected_label": "horror"},
    {"text": "Surviving an underwater apocalypse in The Sinking City: Sunken Dreams.", "expected_label": "horror"},
    {"text": "Exploring haunted marshlands in Witch Hunt: Ghostly Pursuit.", "expected_label": "horror"},
    {"text": "Revealing shocking truths in Stories Untold.", "expected_label": "horror"},
    {"text": "Solving sinister enigmas in The Room Two.", "expected_label": "horror"},
    {"text": "Uncovering twisted tales in Tormented Souls.", "expected_label": "horror"},
    {"text": "Escaping cursed beacons in Fear the Light: Redemption.", "expected_label": "horror"},
    {"text": "Fighting ancient nightmares in Lovecraft's Untold Stories 2.", "expected_label": "horror"},
    {"text": "Surviving demonic invasions in Doom Eternal.", "expected_label": "horror"},
    {"text": "Navigating the underworld in Sunless Sea: Zubmariner.", "expected_label": "horror"},
    {"text": "Hiding from madness in White Night.", "expected_label": "horror"},
    {"text": "Escaping paranoia in Knock-Knock.", "expected_label": "horror"},
    {"text": "Battling demonic presences in The Dark Occult.", "expected_label": "horror"},
    {"text": "Crawling through cursed tunnels in Lost in Vivo.", "expected_label": "horror"},
    {"text": "Investigating grisly crimes in The Painscreek Killings.", "expected_label": "horror"},
    {"text": "Fighting supernatural forces in Ghostwire: Tokyo: Prelude.", "expected_label": "horror"},
    {"text": "Facing your darkest fears in Inscryption.", "expected_label": "horror"},
    {"text": "Uncovering spiritual legends in Don't Knock Twice.", "expected_label": "horror"},
    {"text": "Exploring haunted memories in The Beast Inside.", "expected_label": "horror"},
    {"text": "Surviving cursed museums in Haunt Chaser: Artifacts.", "expected_label": "horror"},
    {"text": "Fighting against haunted echoes in Devotion.", "expected_label": "horror"},
    {"text": "Exploring terrifying wreckages in Dead Effect.", "expected_label": "horror"},
    {"text": "Unraveling alien conspiracies in Routine.", "expected_label": "horror"},
    {"text": "Surviving psychological terror in The Cat Lady.", "expected_label": "horror"},
    {"text": "Exploring cursed woods in Blair Witch: Definitive Edition.", "expected_label": "horror"},
    {"text": "Sailing through haunted waters in The Boatman's Song.", "expected_label": "horror"},
    {"text": "Uncovering truths in The Blackout Club: Shadows of Fear.", "expected_label": "horror"},
    {"text": "Fighting cursed foes in The Council: Chapter 5.", "expected_label": "horror"},
    {"text": "Exploring haunted police stations in Resident Evil 2.", "expected_label": "horror"},
    {"text": "Surviving the nightmarish village in Resident Evil 4.", "expected_label": "horror"},
    {"text": "Fighting monstrous experiments in Resident Evil 5.", "expected_label": "horror"},
    {"text": "Uncovering bioterror secrets in Resident Evil 6.", "expected_label": "horror"},
    {"text": "Surviving a nightmarish plantation in Resident Evil 7: Biohazard.", "expected_label": "horror"},
    {"text": "Facing vampiric horrors in Resident Evil Village.", "expected_label": "horror"},
    {"text": "Exploring the chilling streets of Silent Hill 3.", "expected_label": "horror"},
    {"text": "Unraveling supernatural mysteries in Silent Hill: Origins.", "expected_label": "horror"},
    {"text": "Battling psychological terrors in Silent Hill: Shattered Memories.", "expected_label": "horror"},
    {"text": "Fleeing from cosmic horrors in Amnesia: A Machine for Pigs.", "expected_label": "horror"},
    {"text": "Surviving a desolate wilderness in Amnesia: Rebirth.", "expected_label": "horror"},
    {"text": "Escaping killer maniacs in Dead by Daylight: Stranger Things DLC.", "expected_label": "horror"},
    {"text": "Evading ghosts and specters in Dead by Daylight: Ghost Face.", "expected_label": "horror"},
    {"text": "Surviving occult rituals in Outlast: Whistleblower.", "expected_label": "horror"},
    {"text": "Exploring haunted houses in Outlast Trials.", "expected_label": "horror"},
    {"text": "Hiding from killer animatronics in Five Nights at Freddy's: Security Breach.", "expected_label": "horror"},
    {"text": "Investigating ghostly disturbances in Five Nights at Freddy's VR: Help Wanted.", "expected_label": "horror"},
    {"text": "Surviving supernatural forces in The Evil Within: The Assignment.", "expected_label": "horror"},
    {"text": "Battling terrifying creatures in The Evil Within: The Consequence.", "expected_label": "horror"},
    {"text": "Uncovering alien horrors in Alien: Blackout.", "expected_label": "horror"},
    {"text": "Surviving a quarantine zone in Dying Light: The Following.", "expected_label": "horror"},
    {"text": "Fighting for survival in The Forest: Sons of the Forest.", "expected_label": "horror"},
    {"text": "Walking through psychological horrors in Layers of Fear: Inheritance.", "expected_label": "horror"},
    {"text": "Investigating eerie mansions in Layers of Fear VR.", "expected_label": "horror"},
    {"text": "Solving ghostly puzzles in Phasmophobia: Apocalypse Update.", "expected_label": "horror"},
    {"text": "Exploring underwater mysteries in Soma: Redux.", "expected_label": "horror"},
    {"text": "Battling grotesque beasts in Bloodborne: The Old Hunters.", "expected_label": "horror"},
    {"text": "Uncovering maritime nightmares in Man of Medan: Dark Waters.", "expected_label": "horror"},
    {"text": "Making critical decisions in Until Dawn: Rush of Blood.", "expected_label": "horror"},
    {"text": "Investigating eldritch stories in Call of Cthulhu: The Wasted Land.", "expected_label": "horror"},
    {"text": "Evading faceless terrors in Slender: The Arrival VR.", "expected_label": "horror"},
    {"text": "Exploring cursed forests in Darkwood: The Lost Path.", "expected_label": "horror"},
    {"text": "Uncovering nightmares in Little Nightmares: Secrets of the Maw.", "expected_label": "horror"},
    {"text": "Facing your fears in Visage: Chapter 4.", "expected_label": "horror"},
    {"text": "Surviving haunted realities in P.T.: Rebirth.", "expected_label": "horror"},
    {"text": "Capturing ghostly images in Fatal Frame: Crimson Butterfly.", "expected_label": "horror"},
    {"text": "Navigating insanity in Eternal Darkness: Director's Cut.", "expected_label": "horror"},
    {"text": "Solving macabre crimes in Condemned: Criminal Origins Remastered.", "expected_label": "horror"},
    {"text": "Fighting necromorphs in Dead Space: Extraction.", "expected_label": "horror"},
    {"text": "Uncovering the darkness in Alan Wake Remastered.", "expected_label": "horror"},
    {"text": "Escaping mutants in Metro Redux.", "expected_label": "horror"},
    {"text": "Exploring technological nightmares in Observer Redux.", "expected_label": "horror"},
    {"text": "Surviving swamp terrors in Hunt: Showdown - Night of the Swamp.", "expected_label": "horror"},
    {"text": "Making choices in The Quarry: Director's Cut.", "expected_label": "horror"},
    {"text": "Facing horrors in The Dark Pictures Anthology: Little Hope.", "expected_label": "horror"},
    {"text": "Unraveling sinister experiments in Prey: Rebirth.", "expected_label": "horror"},
    {"text": "Exploring the depths of fear in Narcosis VR.", "expected_label": "horror"},
    {"text": "Uncovering ancestral horrors in Black Mirror: The Red Legacy.", "expected_label": "horror"},
    {"text": "Fighting hellish nightmares in Agony VR.", "expected_label": "horror"},
    {"text": "Surviving slasher maniacs in The Texas Chain Saw Massacre: Nightfall.", "expected_label": "horror"},
    {"text": "Facing cursed apparitions in Devil Daggers: Spectral Edition.", "expected_label": "horror"},
    {"text": "Exploring haunted schools in White Day: Dark Secrets.", "expected_label": "horror"},
    {"text": "Escaping supernatural curses in Maid of Sker: Bloodlines.", "expected_label": "horror"},
    {"text": "Uncovering haunted paths in Detention: Shadows of the Past.", "expected_label": "horror"},
    {"text": "Battling radioactive mutants in Stalker: Heart of Chernobyl.", "expected_label": "horror"},
    {"text": "Uncovering ghostly truths in Returnal: Abyss.", "expected_label": "horror"},
    {"text": "Fending off zombies in World War Z: Endgame.", "expected_label": "horror"},
    {"text": "Exploring icy waters in Subnautica: Frozen Abyss.", "expected_label": "horror"},
    {"text": "Solving haunting mysteries in Edith Finch Remastered.", "expected_label": "horror"},
    {"text": "Investigating supernatural signals in Oxenfree: Resonance.", "expected_label": "horror"},
    {"text": "Surviving darkness in Alan Wake II: Nightmare Returns.", "expected_label": "horror"},
    {"text": "Exploring haunted amusement parks in The Park: Terror Trails.", "expected_label": "horror"},
    {"text": "Unraveling spiritual enigmas in The Medium: Duality.", "expected_label": "horror"},
    {"text": "Fighting evil forces in Control: Altered World Events.", "expected_label": "horror"},
    {"text": "Walking through twisted realms in Hellblade: The Lost Path.", "expected_label": "horror"},
    {"text": "Facing decay and sickness in Pathologic 2: The Plague.", "expected_label": "horror"},
    {"text": "Escaping ghostly mansions in Luigi's Mansion: Haunted Hall.", "expected_label": "horror"},
    {"text": "Solving cryptic puzzles in Dark Fall: Echoes of Fear.", "expected_label": "horror"},
    {"text": "Facing your worst fears in Eternal Threads: Fractured Realities.", "expected_label": "horror"},
    {"text": "Surviving cursed castles in Dark Souls: The Abyss.", "expected_label": "horror"},
    {"text": "Uncovering haunted myths in Siren: Cursed Origins.", "expected_label": "horror"},
    {"text": "Navigating AI terror in Observation: Digital Nightmare.", "expected_label": "horror"},
    {"text": "Fleeing monstrosities in Monstrum: Endless Nightmares.", "expected_label": "horror"},
    {"text": "Escaping malicious forces in Pacify: The Awakening.", "expected_label": "horror"},
    {"text": "Fighting demonic presences in Malum: The Haunting.", "expected_label": "horror"},
    {"text": "Surviving aquatic terrors in The Sinking City: Abyssal Depths.", "expected_label": "horror"},
    {"text": "Exploring ghostly swamps in Witch Hunt: Phantom Trails.", "expected_label": "horror"},
    {"text": "Solving cursed stories in Stories Untold: Forbidden Tales.", "expected_label": "horror"},
    {"text": "Investigating haunted locations in The Room VR: Dark Matter.", "expected_label": "horror"},
    {"text": "Facing tormenting spirits in Tormented Souls: Dark Chapters.", "expected_label": "horror"},
    {"text": "Surviving cursed lighthouses in Fear the Light: Shadows of the Past.", "expected_label": "horror"},
    {"text": "Uncovering ancient evils in Lovecraft's Untold Stories: Elder's Wrath.", "expected_label": "horror"},
    {"text": "Defending against demonic invaders in Doom: Eternal Nightmare.", "expected_label": "horror"},
    {"text": "Exploring cursed waters in Sunless Sea: The Abyss.", "expected_label": "horror"},
    {"text": "Hiding from terror in White Night: Midnight Frights.", "expected_label": "horror"},
    {"text": "Escaping paranoia in Knock-Knock: The Return.", "expected_label": "horror"},
    {"text": "Battling malevolent forces in The Dark Occult: Requiem.", "expected_label": "horror"},
    {"text": "Uncovering mysteries in Lost in Vivo: The Abyss.", "expected_label": "horror"},
    {"text": "Exploring haunted police stations in Resident Evil 2.", "expected_label": "horror"},
    {"text": "Surviving the nightmarish village in Resident Evil 4.", "expected_label": "horror"},
    {"text": "Fighting monstrous experiments in Resident Evil 5.", "expected_label": "horror"},
    {"text": "Uncovering bioterror secrets in Resident Evil 6.", "expected_label": "horror"},
    {"text": "Surviving a nightmarish plantation in Resident Evil 7: Biohazard.", "expected_label": "horror"},
    {"text": "Facing vampiric horrors in Resident Evil Village.", "expected_label": "horror"},
    {"text": "Exploring the chilling streets of Silent Hill 3.", "expected_label": "horror"},
    {"text": "Unraveling supernatural mysteries in Silent Hill: Origins.", "expected_label": "horror"},
    {"text": "Battling psychological terrors in Silent Hill: Shattered Memories.", "expected_label": "horror"},
    {"text": "Fleeing from cosmic horrors in Amnesia: A Machine for Pigs.", "expected_label": "horror"},
    {"text": "Surviving a desolate wilderness in Amnesia: Rebirth.", "expected_label": "horror"},
    {"text": "Escaping killer maniacs in Dead by Daylight: Stranger Things DLC.", "expected_label": "horror"},
    {"text": "Evading ghosts and specters in Dead by Daylight: Ghost Face.", "expected_label": "horror"},
    {"text": "Surviving occult rituals in Outlast: Whistleblower.", "expected_label": "horror"},
    {"text": "Exploring haunted houses in Outlast Trials.", "expected_label": "horror"},
    {"text": "Hiding from killer animatronics in Five Nights at Freddy's: Security Breach.", "expected_label": "horror"},
    {"text": "Investigating ghostly disturbances in Five Nights at Freddy's VR: Help Wanted.", "expected_label": "horror"},
    {"text": "Surviving supernatural forces in The Evil Within: The Assignment.", "expected_label": "horror"},
    {"text": "Battling terrifying creatures in The Evil Within: The Consequence.", "expected_label": "horror"},
    {"text": "Uncovering alien horrors in Alien: Blackout.", "expected_label": "horror"},
    {"text": "Surviving a quarantine zone in Dying Light: The Following.", "expected_label": "horror"},
    {"text": "Fighting for survival in The Forest: Sons of the Forest.", "expected_label": "horror"},
    {"text": "Walking through psychological horrors in Layers of Fear: Inheritance.", "expected_label": "horror"},
    {"text": "Investigating eerie mansions in Layers of Fear VR.", "expected_label": "horror"},
    {"text": "Solving ghostly puzzles in Phasmophobia: Apocalypse Update.", "expected_label": "horror"},
    {"text": "Exploring underwater mysteries in Soma: Redux.", "expected_label": "horror"},
    {"text": "Battling grotesque beasts in Bloodborne: The Old Hunters.", "expected_label": "horror"},
    {"text": "Uncovering maritime nightmares in Man of Medan: Dark Waters.", "expected_label": "horror"},
    {"text": "Making critical decisions in Until Dawn: Rush of Blood.", "expected_label": "horror"},
    {"text": "Investigating eldritch stories in Call of Cthulhu: The Wasted Land.", "expected_label": "horror"},
    {"text": "Evading faceless terrors in Slender: The Arrival VR.", "expected_label": "horror"},
    {"text": "Exploring cursed forests in Darkwood: The Lost Path.", "expected_label": "horror"},
    {"text": "Uncovering nightmares in Little Nightmares: Secrets of the Maw.", "expected_label": "horror"},
    {"text": "Facing your fears in Visage: Chapter 4.", "expected_label": "horror"},
    {"text": "Surviving haunted realities in P.T.: Rebirth.", "expected_label": "horror"},
    {"text": "Capturing ghostly images in Fatal Frame: Crimson Butterfly.", "expected_label": "horror"},
    {"text": "Navigating insanity in Eternal Darkness: Director's Cut.", "expected_label": "horror"},
    {"text": "Solving macabre crimes in Condemned: Criminal Origins Remastered.", "expected_label": "horror"},
    {"text": "Fighting necromorphs in Dead Space: Extraction.", "expected_label": "horror"},
    {"text": "Uncovering the darkness in Alan Wake Remastered.", "expected_label": "horror"},
    {"text": "Escaping mutants in Metro Redux.", "expected_label": "horror"},
    {"text": "Exploring technological nightmares in Observer Redux.", "expected_label": "horror"},
    {"text": "Surviving swamp terrors in Hunt: Showdown - Night of the Swamp.", "expected_label": "horror"},
    {"text": "Making choices in The Quarry: Director's Cut.", "expected_label": "horror"},
    {"text": "Facing horrors in The Dark Pictures Anthology: Little Hope.", "expected_label": "horror"},
    {"text": "Unraveling sinister experiments in Prey: Rebirth.", "expected_label": "horror"},
    {"text": "Exploring the depths of fear in Narcosis VR.", "expected_label": "horror"},
    {"text": "Uncovering ancestral horrors in Black Mirror: The Red Legacy.", "expected_label": "horror"},
    {"text": "Fighting hellish nightmares in Agony VR.", "expected_label": "horror"},
    {"text": "Surviving slasher maniacs in The Texas Chain Saw Massacre: Nightfall.", "expected_label": "horror"},
    {"text": "Facing cursed apparitions in Devil Daggers: Spectral Edition.", "expected_label": "horror"},
    {"text": "Exploring haunted schools in White Day: Dark Secrets.", "expected_label": "horror"},
    {"text": "Escaping supernatural curses in Maid of Sker: Bloodlines.", "expected_label": "horror"},
    {"text": "Uncovering haunted paths in Detention: Shadows of the Past.", "expected_label": "horror"},
    {"text": "Battling radioactive mutants in Stalker: Heart of Chernobyl.", "expected_label": "horror"},
    {"text": "Uncovering ghostly truths in Returnal: Abyss.", "expected_label": "horror"},
    {"text": "Fending off zombies in World War Z: Endgame.", "expected_label": "horror"},
    {"text": "Exploring icy waters in Subnautica: Frozen Abyss.", "expected_label": "horror"},
    {"text": "Solving haunting mysteries in Edith Finch Remastered.", "expected_label": "horror"},
    {"text": "Investigating supernatural signals in Oxenfree: Resonance.", "expected_label": "horror"},
    {"text": "Surviving darkness in Alan Wake II: Nightmare Returns.", "expected_label": "horror"},
    {"text": "Exploring haunted amusement parks in The Park: Terror Trails.", "expected_label": "horror"},
    {"text": "Unraveling spiritual enigmas in The Medium: Duality.", "expected_label": "horror"},
    {"text": "Fighting evil forces in Control: Altered World Events.", "expected_label": "horror"},
    {"text": "Walking through twisted realms in Hellblade: The Lost Path.", "expected_label": "horror"},
    {"text": "Facing decay and sickness in Pathologic 2: The Plague.", "expected_label": "horror"},
    {"text": "Escaping ghostly mansions in Luigi's Mansion: Haunted Hall.", "expected_label": "horror"},
    {"text": "Solving cryptic puzzles in Dark Fall: Echoes of Fear.", "expected_label": "horror"},
    {"text": "Facing your worst fears in Eternal Threads: Fractured Realities.", "expected_label": "horror"},
    {"text": "Surviving cursed castles in Dark Souls: The Abyss.", "expected_label": "horror"},
    {"text": "Uncovering haunted myths in Siren: Cursed Origins.", "expected_label": "horror"},
    {"text": "Navigating AI terror in Observation: Digital Nightmare.", "expected_label": "horror"},
    {"text": "Fleeing monstrosities in Monstrum: Endless Nightmares.", "expected_label": "horror"},
    {"text": "Escaping malicious forces in Pacify: The Awakening.", "expected_label": "horror"},
    {"text": "Fighting demonic presences in Malum: The Haunting.", "expected_label": "horror"},
    {"text": "Surviving aquatic terrors in The Sinking City: Abyssal Depths.", "expected_label": "horror"},
    {"text": "Exploring ghostly swamps in Witch Hunt: Phantom Trails.", "expected_label": "horror"},
    {"text": "Solving cursed stories in Stories Untold: Forbidden Tales.", "expected_label": "horror"},
    {"text": "Investigating haunted locations in The Room VR: Dark Matter.", "expected_label": "horror"},
    {"text": "Facing tormenting spirits in Tormented Souls: Dark Chapters.", "expected_label": "horror"},
    {"text": "Surviving cursed lighthouses in Fear the Light: Shadows of the Past.", "expected_label": "horror"},
    {"text": "Uncovering ancient evils in Lovecraft's Untold Stories: Elder's Wrath.", "expected_label": "horror"},
    {"text": "Defending against demonic invaders in Doom: Eternal Nightmare.", "expected_label": "horror"},
    {"text": "Exploring cursed waters in Sunless Sea: The Abyss.", "expected_label": "horror"},
    {"text": "Hiding from terror in White Night: Midnight Frights.", "expected_label": "horror"},
    {"text": "Escaping paranoia in Knock-Knock: The Return.", "expected_label": "horror"},
    {"text": "Battling malevolent forces in The Dark Occult: Requiem.", "expected_label": "horror"},
    {"text": "Uncovering mysteries in Lost in Vivo: The Abyss.", "expected_label": "horror"},
    {"text": "Exploring abandoned corridors in Resident Evil 3 Remake.", "expected_label": "horror"},
    {"text": "Fleeing from relentless bioweapons in Resident Evil 8: Shadows of Fear.", "expected_label": "horror"},
    {"text": "Surviving the horrors of Silent Hill 4: The Room.", "expected_label": "horror"},
    {"text": "Unraveling mysteries in Silent Hill: Downpour.", "expected_label": "horror"},
    {"text": "Facing psychological terror in Silent Hill: Homecoming.", "expected_label": "horror"},
    {"text": "Escaping the eerie depths in Amnesia: The Bunker.", "expected_label": "horror"},
    {"text": "Navigating terror in Dead by Daylight: Nightmare Edition.", "expected_label": "horror"},
    {"text": "Hiding from stalkers in Dead by Daylight: Shattered Realms.", "expected_label": "horror"},
    {"text": "Escaping an experimental asylum in Outlast Redux.", "expected_label": "horror"},
    {"text": "Fighting malevolent forces in Outlast 3.", "expected_label": "horror"},
    {"text": "Avoiding animatronics in Five Nights at Freddy's: The Curse.", "expected_label": "horror"},
    {"text": "Solving eerie puzzles in Five Nights at Freddy's AR: Special Delivery.", "expected_label": "horror"},
    {"text": "Unraveling nightmarish truths in The Evil Within VR.", "expected_label": "horror"},
    {"text": "Fighting grotesque monsters in The Evil Within 3.", "expected_label": "horror"},
    {"text": "Surviving intergalactic terror in Alien: Resurrection.", "expected_label": "horror"},
    {"text": "Navigating supernatural events in Dying Light: Blood Ties.", "expected_label": "horror"},
    {"text": "Exploring haunted islands in The Forest VR.", "expected_label": "horror"},
    {"text": "Unraveling psychological twists in Layers of Fear: Fractured Memories.", "expected_label": "horror"},
    {"text": "Solving cursed riddles in Layers of Fear VR: The Journey.", "expected_label": "horror"},
    {"text": "Facing paranormal forces in Phasmophobia: Lost Evidence.", "expected_label": "horror"},
    {"text": "Investigating underwater labs in Soma: Deep Waters.", "expected_label": "horror"},
    {"text": "Surviving hellish beasts in Bloodborne VR.", "expected_label": "horror"},
    {"text": "Uncovering maritime terror in Man of Medan: The Lost Crew.", "expected_label": "horror"},
    {"text": "Making tough survival choices in Until Dawn: Hidden Paths.", "expected_label": "horror"},
    {"text": "Exploring cursed myths in Call of Cthulhu: Shadows of Innsmouth.", "expected_label": "horror"},
    {"text": "Escaping unseen nightmares in Slender: Hidden Chapters.", "expected_label": "horror"},
    {"text": "Navigating haunted villages in Darkwood: Depths of Fear.", "expected_label": "horror"},
    {"text": "Facing your nightmares in Little Nightmares: The Final Chapter.", "expected_label": "horror"},
    {"text": "Uncovering ghostly tales in Visage: Phantom Echoes.", "expected_label": "horror"},
    {"text": "Escaping cursed realities in P.T.: The Haunting.", "expected_label": "horror"},
    {"text": "Capturing spectral entities in Fatal Frame: Spirit World.", "expected_label": "horror"},
    {"text": "Battling madness in Eternal Darkness: Shattered Sanity.", "expected_label": "horror"},
    {"text": "Solving horrifying cases in Condemned: The Final File.", "expected_label": "horror"},
    {"text": "Exploring the necromorph origins in Dead Space: Genesis.", "expected_label": "horror"},
    {"text": "Uncovering light and dark in Alan Wake 3.", "expected_label": "horror"},
    {"text": "Surviving a mutant apocalypse in Metro Exodus.", "expected_label": "horror"},
    {"text": "Facing a digital nightmare in Observer: Reawakened.", "expected_label": "horror"},
    {"text": "Escaping swamp horrors in Hunt: Showdown - Curse of the Bayou.", "expected_label": "horror"},
    {"text": "Exploring unsettling choices in The Quarry: Night Terrors.", "expected_label": "horror"},
    {"text": "Facing ancient terrors in The Dark Pictures Anthology: The Depths.", "expected_label": "horror"},
    {"text": "Evading horrors in Prey: Nightmare Reality.", "expected_label": "horror"},
    {"text": "Exploring submerged fears in Narcosis: Abyssal Crisis.", "expected_label": "horror"},
    {"text": "Uncovering cursed heritage in Black Mirror: Haunted Bloodlines.", "expected_label": "horror"},
    {"text": "Facing infernal nightmares in Agony: Inferno.", "expected_label": "horror"},
    {"text": "Surviving slasher nightmares in The Texas Chain Saw Massacre: Torment.", "expected_label": "horror"},
    {"text": "Battling spectral entities in Devil Daggers: Eternal Night.", "expected_label": "horror"},
    {"text": "Escaping haunting legends in White Day: Shadows of the Moon.", "expected_label": "horror"},
    {"text": "Uncovering sinister curses in Maid of Sker: Phantom Tales.", "expected_label": "horror"},
    {"text": "Exploring haunting stories in Detention: Forgotten Shadows.", "expected_label": "horror"},
    {"text": "Surviving radioactive horrors in Stalker: Dark Horizon.", "expected_label": "horror"},
    {"text": "Solving haunted mysteries in Returnal: The Abyss Awaits.", "expected_label": "horror"},
    {"text": "Fighting the undead in World War Z: Apocalypse Rising.", "expected_label": "horror"},
    {"text": "Diving into chilling depths in Subnautica: Abyssal Echoes.", "expected_label": "horror"},
    {"text": "Exploring family tragedies in What Remains of Edith Finch VR.", "expected_label": "horror"},
    {"text": "Investigating ghostly signals in Oxenfree: Lost Frequencies.", "expected_label": "horror"},
    {"text": "Facing sinister darkness in Alan Wake II: Fractured Night.", "expected_label": "horror"},
    {"text": "Unraveling haunted amusement parks in The Park: Lost Dreams.", "expected_label": "horror"},
    {"text": "Exploring dual realities in The Medium: Shattered Worlds.", "expected_label": "horror"},
    {"text": "Fighting supernatural foes in Control: Dark Reflections.", "expected_label": "horror"},
    {"text": "Walking cursed paths in Hellblade: Shadows of Sacrifice.", "expected_label": "horror"},
    {"text": "Facing decay in Pathologic 2: The Scarlet Plague.", "expected_label": "horror"},
    {"text": "Exploring haunted halls in Luigi's Mansion 3 VR.", "expected_label": "horror"},
    {"text": "Solving haunted cases in Dark Fall: Phantom Memories.", "expected_label": "horror"},
    {"text": "Uncovering sinister timelines in Eternal Threads: The Forgotten Paths.", "expected_label": "horror"},
    {"text": "Surviving cursed fortresses in Dark Souls: The Lost Realm.", "expected_label": "horror"},
    {"text": "Unraveling myths in Siren: Whispered Echoes.", "expected_label": "horror"},
    {"text": "Surviving AI terror in Observation: Fractured Logic.", "expected_label": "horror"},
    {"text": "Escaping endless horrors in Monstrum 3.", "expected_label": "horror"},
    {"text": "Fleeing malicious spirits in Pacify: Shadows Awaken.", "expected_label": "horror"},
    {"text": "Defending against demonic horrors in Malum: Eternal Fears.", "expected_label": "horror"},
    {"text": "Exploring cursed depths in The Sinking City: Forgotten Abyss.", "expected_label": "horror"},
    {"text": "Walking ghostly trails in Witch Hunt: Spirit Echoes.", "expected_label": "horror"},
    {"text": "Uncovering haunting tales in Stories Untold: Shattered Legends.", "expected_label": "horror"},
    {"text": "Investigating eerie puzzles in The Room VR: Haunted Matter.", "expected_label": "horror"},
    {"text": "Facing tormenting shadows in Tormented Souls: Fractured Realities.", "expected_label": "horror"},
    {"text": "Surviving cursed shores in Fear the Light: Echoes of the Past.", "expected_label": "horror"},
    {"text": "Unraveling ancient evils in Lovecraft's Untold Stories: The Forgotten Depths.", "expected_label": "horror"},
    {"text": "Battling demons in Doom Eternal: The Lost Horde.", "expected_label": "horror"},
    {"text": "Exploring eerie oceans in Sunless Sea: Abyssal Shores.", "expected_label": "horror"},
    {"text": "Hiding from malevolent entities in White Night: Echoes.", "expected_label": "horror"},
    {"text": "Escaping paranoia in Knock-Knock: The Final Haunting.", "expected_label": "horror"},
    {"text": "Fighting dark presences in The Dark Occult: Shattered Souls.", "expected_label": "horror"},
    {"text": "Navigating cursed tunnels in Lost in Vivo: Phantom Pathways.", "expected_label": "horror"},
    {"text": "Uncovering the secrets of the Spencer Mansion in Resident Evil.", "expected_label": "horror"},
    {"text": "Surviving the zombie outbreak in Resident Evil 3.", "expected_label": "horror"},
    {"text": "Exploring the foggy streets of Silent Hill 2.", "expected_label": "horror"},
    {"text": "Escaping a deranged cult in Silent Hill: Downpour.", "expected_label": "horror"},
    {"text": "Facing relentless horror in Silent Hill: Shattered Memories.", "expected_label": "horror"},
    {"text": "Hiding from a monster in Amnesia: The Dark Descent.", "expected_label": "horror"},
    {"text": "Navigating terrifying realities in Amnesia: Rebirth.", "expected_label": "horror"},
    {"text": "Escaping supernatural killers in Dead by Daylight: Ghost Face.", "expected_label": "horror"},
    {"text": "Fleeing from a vengeful spirit in Dead by Daylight: The Spirit.", "expected_label": "horror"},
    {"text": "Uncovering dark experiments in Outlast.", "expected_label": "horror"},
    {"text": "Surviving twisted trials in Outlast 2.", "expected_label": "horror"},
    {"text": "Facing animatronic terrors in Five Nights at Freddy's: Help Wanted.", "expected_label": "horror"},
    {"text": "Unraveling deadly mysteries in Five Nights at Freddy's: Security Breach.", "expected_label": "horror"},
    {"text": "Battling grotesque beasts in The Evil Within.", "expected_label": "horror"},
    {"text": "Exploring psychological terrors in The Evil Within 2.", "expected_label": "horror"},
    {"text": "Surviving a relentless alien in Alien: Isolation.", "expected_label": "horror"},
    {"text": "Fighting through a zombie apocalypse in Dying Light.", "expected_label": "horror"},
    {"text": "Exploring eerie forests in The Forest.", "expected_label": "horror"},
    {"text": "Walking through haunted memories in Layers of Fear.", "expected_label": "horror"},
    {"text": "Unraveling ghostly secrets in Layers of Fear 2.", "expected_label": "horror"},
    {"text": "Solving paranormal mysteries in Phasmophobia.", "expected_label": "horror"},
    {"text": "Exploring underwater nightmares in Soma.", "expected_label": "horror"},
    {"text": "Battling horrifying creatures in Bloodborne.", "expected_label": "horror"},
    {"text": "Facing chilling maritime horrors in Man of Medan.", "expected_label": "horror"},
    {"text": "Making life-or-death choices in Until Dawn.", "expected_label": "horror"},
    {"text": "Investigating ancient evils in Call of Cthulhu.", "expected_label": "horror"},
    {"text": "Escaping from a faceless terror in Slender: The Eight Pages.", "expected_label": "horror"},
    {"text": "Surviving a cursed forest in Darkwood.", "expected_label": "horror"},
    {"text": "Navigating nightmarish landscapes in Little Nightmares.", "expected_label": "horror"},
    {"text": "Uncovering haunting truths in Visage.", "expected_label": "horror"},
    {"text": "Exploring a cursed hallway in P.T.", "expected_label": "horror"},
    {"text": "Capturing spirits on film in Fatal Frame.", "expected_label": "horror"},
    {"text": "Resisting madness in Eternal Darkness: Sanity's Requiem.", "expected_label": "horror"},
    {"text": "Solving crimes amidst terror in Condemned: Criminal Origins.", "expected_label": "horror"},
    {"text": "Fighting necromorphs in Dead Space.", "expected_label": "horror"},
    {"text": "Uncovering chilling tales in Alan Wake.", "expected_label": "horror"},
    {"text": "Navigating mutant-filled tunnels in Metro 2033.", "expected_label": "horror"},
    {"text": "Investigating sinister technology in Observer.", "expected_label": "horror"},
    {"text": "Battling nightmarish foes in Hunt: Showdown.", "expected_label": "horror"},
    {"text": "Uncovering unsettling mysteries in The Quarry.", "expected_label": "horror"},
    {"text": "Exploring cursed ruins in House of Ashes.", "expected_label": "horror"},
    {"text": "Facing cosmic horror in Prey.", "expected_label": "horror"},
    {"text": "Exploring deep underwater in Narcosis.", "expected_label": "horror"},
    {"text": "Uncovering haunting family secrets in Black Mirror.", "expected_label": "horror"},
    {"text": "Surviving hellish nightmares in Agony.", "expected_label": "horror"},
    {"text": "Fending off slasher threats in The Texas Chain Saw Massacre.", "expected_label": "horror"},
    {"text": "Escaping cursed grounds in Devil Daggers.", "expected_label": "horror"},
    {"text": "Exploring haunted schools in White Day.", "expected_label": "horror"},
    {"text": "Uncovering dark rituals in Maid of Sker.", "expected_label": "horror"},
    {"text": "Escaping sinister forces in Detention.", "expected_label": "horror"},
    {"text": "Fighting irradiated monsters in Stalker: Shadow of Chernobyl.", "expected_label": "horror"},
    {"text": "Solving eerie puzzles in Returnal.", "expected_label": "horror"},
    {"text": "Fending off zombie swarms in World War Z.", "expected_label": "horror"},
    {"text": "Exploring icy seas in Subnautica: Below Zero.", "expected_label": "horror"},
    {"text": "Unraveling haunting tales in What Remains of Edith Finch.", "expected_label": "horror"},
    {"text": "Investigating supernatural signals in Oxenfree.", "expected_label": "horror"},
    {"text": "Facing dark memories in Alan Wake II.", "expected_label": "horror"},
    {"text": "Exploring haunted parks in The Park.", "expected_label": "horror"},
    {"text": "Unraveling spiritual enigmas in The Medium.", "expected_label": "horror"},
    {"text": "Facing paranormal events in Control.", "expected_label": "horror"},
    {"text": "Walking through distorted realities in Hellblade.", "expected_label": "horror"},
    {"text": "Surviving sickness and fear in Pathologic 2.", "expected_label": "horror"},
    {"text": "Exploring haunted mansions in Luigi's Mansion.", "expected_label": "horror"},
    {"text": "Solving twisted puzzles in Dark Fall.", "expected_label": "horror"},
    {"text": "Uncovering haunting timelines in Eternal Threads.", "expected_label": "horror"},
    {"text": "Surviving cursed fortresses in Dark Souls.", "expected_label": "horror"},
    {"text": "Unraveling sinister myths in Siren.", "expected_label": "horror"},
    {"text": "Navigating haunting AI in Observation.", "expected_label": "horror"},
    {"text": "Escaping monstrous foes in Monstrum.", "expected_label": "horror"},
    {"text": "Fleeing from evil spirits in Pacify.", "expected_label": "horror"},
    {"text": "Defending against demonic forces in Malum.", "expected_label": "horror"},
    {"text": "Exploring sunken horrors in The Sinking City.", "expected_label": "horror"},
    {"text": "Walking haunted trails in Witch Hunt.", "expected_label": "horror"},
    {"text": "Uncovering dark truths in Stories Untold.", "expected_label": "horror"},
    {"text": "Solving cursed enigmas in The Room.", "expected_label": "horror"},
    {"text": "Unraveling haunting fates in Tormented Souls.", "expected_label": "horror"},
    {"text": "Surviving cursed beacons in Fear the Light.", "expected_label": "horror"},
    {"text": "Uncovering eldritch horrors in Lovecraft's Untold Stories.", "expected_label": "horror"},
    {"text": "Fighting demonic invasions in Doom Eternal.", "expected_label": "horror"},
    {"text": "Exploring cursed oceans in Sunless Sea.", "expected_label": "horror"},
    {"text": "Hiding from spectral threats in White Night.", "expected_label": "horror"},
    {"text": "Escaping paranoia in Knock-Knock.", "expected_label": "horror"},
    {"text": "Battling evil spirits in The Dark Occult.", "expected_label": "horror"},
    {"text": "Exploring cursed tunnels in Lost in Vivo.", "expected_label": "horror"},
    {"text": "Investigating grisly murders in The Painscreek Killings.", "expected_label": "horror"},
    {"text": "Fighting paranormal beings in Ghostwire: Tokyo.", "expected_label": "horror"},
    {"text": "Facing sinister games in Inscryption.", "expected_label": "horror"},
    {"text": "Uncovering eerie legends in Don't Knock Twice.", "expected_label": "horror"},
    {"text": "Exploring ghostly estates in The Beast Inside.", "expected_label": "horror"},
    {"text": "Navigating cursed museums in Haunt Chaser.", "expected_label": "horror"},
    {"text": "Fighting haunted echoes in Devotion.", "expected_label": "horror"},
    {"text": "Exploring derelict spaceships in Dead Effect.", "expected_label": "horror"},
    {"text": "Escaping AI-driven terror in Routine.", "expected_label": "horror"},
    {"text": "Facing psychological dread in The Cat Lady.", "expected_label": "horror"},
    {"text": "Exploring cursed woods in Blair Witch.", "expected_label": "horror"},
    {"text": "Sailing haunted waters in The Boatman's Song.", "expected_label": "horror"},
    {"text": "Surviving sinister cults in The Blackout Club.", "expected_label": "horror"},
    {"text": "Fighting cursed entities in The Council.", "expected_label": "horror"},
    {"text": "Navigating a nightmarish police station in Resident Evil 2.", "expected_label": "horror"},
    {"text": "Escaping the horrors of Nemesis in Resident Evil 3 Remake.", "expected_label": "horror"},
    {"text": "Facing vampiric threats in Resident Evil Village.", "expected_label": "horror"},
    {"text": "Surviving a chilling cult in Silent Hill 3.", "expected_label": "horror"},
    {"text": "Exploring the cursed town of Silent Hill 4: The Room.", "expected_label": "horror"},
    {"text": "Escaping cosmic nightmares in Amnesia: The Bunker.", "expected_label": "horror"},
    {"text": "Hiding from unrelenting killers in Dead by Daylight: Halloween Chapter.", "expected_label": "horror"},
    {"text": "Facing demonic rituals in Outlast: Whistleblower.", "expected_label": "horror"},
    {"text": "Avoiding deadly animatronics in Five Nights at Freddy's VR.", "expected_label": "horror"},
    {"text": "Unraveling twisted realities in The Evil Within: The Executioner.", "expected_label": "horror"},
    {"text": "Surviving xenomorph attacks in Alien: Blackout.", "expected_label": "horror"},
    {"text": "Battling infected hordes in Dying Light 2: Stay Human.", "expected_label": "horror"},
    {"text": "Exploring terrifying caves in The Forest.", "expected_label": "horror"},
    {"text": "Walking through psychological horrors in Layers of Fear 2.", "expected_label": "horror"},
    {"text": "Solving spectral mysteries in Phasmophobia.", "expected_label": "horror"},
    {"text": "Uncovering underwater terror in Soma.", "expected_label": "horror"},
    {"text": "Fighting grotesque nightmares in Bloodborne.", "expected_label": "horror"},
    {"text": "Exploring eerie seas in Man of Medan.", "expected_label": "horror"},
    {"text": "Making fateful decisions in Until Dawn.", "expected_label": "horror"},
    {"text": "Investigating dark mythos in Call of Cthulhu.", "expected_label": "horror"},
    {"text": "Evading supernatural forces in Slender: The Arrival.", "expected_label": "horror"},
    {"text": "Surviving cursed landscapes in Darkwood.", "expected_label": "horror"},
    {"text": "Escaping nightmarish foes in Little Nightmares 2.", "expected_label": "horror"},
    {"text": "Exploring haunted manors in Visage.", "expected_label": "horror"},
    {"text": "Facing endless corridors in P.T.", "expected_label": "horror"},
    {"text": "Capturing haunted memories in Fatal Frame: Mask of the Lunar Eclipse.", "expected_label": "horror"},
    {"text": "Resisting madness in Eternal Darkness.", "expected_label": "horror"},
    {"text": "Solving grim cases in Condemned: Bloodshot.", "expected_label": "horror"},
    {"text": "Fighting necromorphs in Dead Space 2.", "expected_label": "horror"},
    {"text": "Uncovering light and shadow in Alan Wake Remastered.", "expected_label": "horror"},
    {"text": "Navigating mutant-infested tunnels in Metro Redux.", "expected_label": "horror"},
    {"text": "Exploring haunted technology in Observer: Redux.", "expected_label": "horror"},
    {"text": "Facing supernatural predators in Hunt: Showdown.", "expected_label": "horror"},
    {"text": "Making pivotal decisions in The Quarry.", "expected_label": "horror"},
    {"text": "Exploring cursed tombs in House of Ashes.", "expected_label": "horror"},
    {"text": "Unraveling alien conspiracies in Prey.", "expected_label": "horror"},
    {"text": "Exploring haunting depths in Narcosis.", "expected_label": "horror"},
    {"text": "Uncovering family horrors in Black Mirror.", "expected_label": "horror"},
    {"text": "Escaping twisted hellscapes in Agony.", "expected_label": "horror"},
    {"text": "Avoiding slasher killers in The Texas Chain Saw Massacre.", "expected_label": "horror"},
    {"text": "Facing demonic apparitions in Devil Daggers.", "expected_label": "horror"},
    {"text": "Uncovering school mysteries in White Day: A Labyrinth Named School.", "expected_label": "horror"},
    {"text": "Surviving folkloric curses in Maid of Sker.", "expected_label": "horror"},
    {"text": "Exploring haunted villages in Detention.", "expected_label": "horror"},
    {"text": "Fighting irradiated horrors in Stalker: Call of Pripyat.", "expected_label": "horror"},
    {"text": "Solving eerie shipwrecks in Returnal.", "expected_label": "horror"},
    {"text": "Defending against undead in World War Z.", "expected_label": "horror"},
    {"text": "Navigating icy waters in Subnautica: Below Zero.", "expected_label": "horror"},
    {"text": "Uncovering haunted family secrets in What Remains of Edith Finch.", "expected_label": "horror"},
    {"text": "Investigating supernatural signals in Oxenfree 2.", "expected_label": "horror"},
    {"text": "Facing inner darkness in Alan Wake 2.", "expected_label": "horror"},
    {"text": "Exploring haunted attractions in The Park.", "expected_label": "horror"},
    {"text": "Walking dual realities in The Medium.", "expected_label": "horror"},
    {"text": "Fighting paranormal threats in Control.", "expected_label": "horror"},
    {"text": "Facing your psyche in Hellblade: Senua's Sacrifice.", "expected_label": "horror"},
    {"text": "Surviving sickness and decay in Pathologic 2.", "expected_label": "horror"},
    {"text": "Exploring haunted mansions in Luigi's Mansion 3.", "expected_label": "horror"},
    {"text": "Solving cryptic puzzles in Dark Fall: The Journal.", "expected_label": "horror"},
    {"text": "Exploring haunting timelines in Eternal Threads.", "expected_label": "horror"},
    {"text": "Surviving cursed keeps in Dark Souls 3.", "expected_label": "horror"},
    {"text": "Uncovering sinister myths in Siren.", "expected_label": "horror"},
    {"text": "Surviving AI-driven horror in Observation.", "expected_label": "horror"},
    {"text": "Evading monsters in Monstrum.", "expected_label": "horror"},
    {"text": "Avoiding spectral forces in Pacify.", "expected_label": "horror"},
    {"text": "Fighting demonic threats in Malum.", "expected_label": "horror"},
    {"text": "Exploring sunken horrors in The Sinking City.", "expected_label": "horror"},
    {"text": "Walking ghostly trails in Witch Hunt.", "expected_label": "horror"},
    {"text": "Uncovering eerie stories in Stories Untold.", "expected_label": "horror"},
    {"text": "Investigating cursed enigmas in The Room VR.", "expected_label": "horror"},
    {"text": "Unraveling tormented tales in Tormented Souls.", "expected_label": "horror"},
    {"text": "Exploring cursed shores in Fear the Light.", "expected_label": "horror"},
    {"text": "Facing eldritch terrors in Lovecraft's Untold Stories.", "expected_label": "horror"},
    {"text": "Surviving demonic invasions in Doom Eternal.", "expected_label": "horror"},
    {"text": "Exploring eerie seas in Sunless Sea.", "expected_label": "horror"},
    {"text": "Escaping spectral threats in White Night.", "expected_label": "horror"},
    {"text": "Hiding from paranoia in Knock-Knock.", "expected_label": "horror"},
    {"text": "Facing haunting spirits in The Dark Occult.", "expected_label": "horror"},
    {"text": "Exploring cursed pathways in Lost in Vivo.", "expected_label": "horror"},
    {"text": "Investigating grisly crimes in The Painscreek Killings.", "expected_label": "horror"},
    {"text": "Fighting spectral entities in Ghostwire: Tokyo.", "expected_label": "horror"},
    {"text": "Uncovering sinister games in Inscryption.", "expected_label": "horror"},
    {"text": "Exploring ghostly legends in Don't Knock Twice.", "expected_label": "horror"},
    {"text": "Unraveling eerie estates in The Beast Inside.", "expected_label": "horror"},
    {"text": "Navigating haunted exhibits in Haunt Chaser.", "expected_label": "horror"},
    {"text": "Fending off spectral echoes in Devotion.", "expected_label": "horror"},
    {"text": "Exploring derelict vessels in Dead Effect.", "expected_label": "horror"},
    {"text": "Escaping AI-driven horror in Routine.", "expected_label": "horror"},
    {"text": "Facing psychological terror in The Cat Lady.", "expected_label": "horror"},
    {"text": "Exploring haunted woods in Blair Witch.", "expected_label": "horror"},
    {"text": "Navigating cursed waters in The Boatman's Song.", "expected_label": "horror"},
    {"text": "Uncovering cult secrets in The Blackout Club.", "expected_label": "horror"},
    {"text": "Facing cursed entities in The Council.", "expected_label": "horror"},
    {"text": "Facing relentless terror in Resident Evil 4 Remake.", "expected_label": "horror"},
    {"text": "Exploring the snowy landscapes of Resident Evil: Code Veronica.", "expected_label": "horror"},
    {"text": "Uncovering secrets in the terrifying depths of Resident Evil Zero.", "expected_label": "horror"},
    {"text": "Surviving the foggy streets of Silent Hill: Origins.", "expected_label": "horror"},
    {"text": "Escaping from the past in Silent Hill: Homecoming.", "expected_label": "horror"},
    {"text": "Facing shadowy figures in Silent Hill: Book of Memories.", "expected_label": "horror"},
    {"text": "Evading a horrifying beast in Amnesia: Rebirth.", "expected_label": "horror"},
    {"text": "Hiding from spectral killers in Dead by Daylight: Roots of Dread.", "expected_label": "horror"},
    {"text": "Solving twisted trials in Outlast: Trinity.", "expected_label": "horror"},
    {"text": "Avoiding malicious animatronics in Five Nights at Freddy's: Pizza Simulator.", "expected_label": "horror"},
    {"text": "Escaping corrupted dreams in The Evil Within: The Assignment.", "expected_label": "horror"},
    {"text": "Facing the nightmarish xenomorph in Alien: Isolation VR.", "expected_label": "horror"},
    {"text": "Surviving the deadly hordes in Dying Light: Hellraid.", "expected_label": "horror"},
    {"text": "Navigating a haunted wilderness in The Forest: Lost World.", "expected_label": "horror"},
    {"text": "Walking through cursed paintings in Layers of Fear: The Artist's Curse.", "expected_label": "horror"},
    {"text": "Solving ghostly riddles in Phasmophobia: Nightmare Mode.", "expected_label": "horror"},
    {"text": "Exploring underwater despair in Soma: The Abyss.", "expected_label": "horror"},
    {"text": "Battling grotesque monstrosities in Bloodborne: The Nightmare of Mensis.", "expected_label": "horror"},
    {"text": "Exploring abandoned ships in Man of Medan: Beyond the Waves.", "expected_label": "horror"},
    {"text": "Making life-altering choices in Until Dawn: The Butterfly Effect.", "expected_label": "horror"},
    {"text": "Investigating cosmic horrors in Call of Cthulhu: Dark Reflections.", "expected_label": "horror"},
    {"text": "Escaping from a relentless stalker in Slender: The Arrival Redux.", "expected_label": "horror"},
    {"text": "Facing cursed shadows in Darkwood: Forbidden Forest.", "expected_label": "horror"},
    {"text": "Unraveling nightmare scenarios in Little Nightmares: Depths of Fear.", "expected_label": "horror"},
    {"text": "Exploring haunted rooms in Visage: The Forgotten Chapters.", "expected_label": "horror"},
    {"text": "Surviving a cursed hallway in P.T.: Endless Echoes.", "expected_label": "horror"},
    {"text": "Capturing ghostly beings in Fatal Frame: Spirit Beyond.", "expected_label": "horror"},
    {"text": "Resisting madness in Eternal Darkness: Legacy of Fear.", "expected_label": "horror"},
    {"text": "Solving violent crimes in Condemned: The Final Truth.", "expected_label": "horror"},
    {"text": "Fighting necromorphs in Dead Space: Extraction Redux.", "expected_label": "horror"},
    {"text": "Uncovering the darkness in Alan Wake: Nightmare Edition.", "expected_label": "horror"},
    {"text": "Navigating tunnels of terror in Metro: Exodus Enhanced Edition.", "expected_label": "horror"},
    {"text": "Exploring cybernetic nightmares in Observer: Redux.", "expected_label": "horror"},
    {"text": "Surviving eerie bayous in Hunt: Showdown - Legends of the Swamp.", "expected_label": "horror"},
    {"text": "Making critical choices in The Quarry: Shadows of the Past.", "expected_label": "horror"},
    {"text": "Exploring cursed lands in House of Ashes: Eternal Darkness.", "expected_label": "horror"},
    {"text": "Unraveling ancient truths in Prey: Legacy of the Typhon.", "expected_label": "horror"},
    {"text": "Diving into haunted depths in Narcosis: Abyss Unveiled.", "expected_label": "horror"},
    {"text": "Facing dark family legacies in Black Mirror: Cradle of Shadows.", "expected_label": "horror"},
    {"text": "Escaping hellish dimensions in Agony: Dark Descent.", "expected_label": "horror"},
    {"text": "Surviving slasher nightmares in The Texas Chain Saw Massacre: Relentless.", "expected_label": "horror"},
    {"text": "Fighting cursed spirits in Devil Daggers: Inferno.", "expected_label": "horror"},
    {"text": "Exploring haunted schools in White Day: Secrets of the Moon.", "expected_label": "horror"},
    {"text": "Facing ghostly apparitions in Maid of Sker: Cursed Ballads.", "expected_label": "horror"},
    {"text": "Navigating sinister rituals in Detention: The Final Trials.", "expected_label": "horror"},
    {"text": "Battling irradiated beasts in Stalker: Heart of Shadows.", "expected_label": "horror"},
    {"text": "Uncovering chilling shipwreck mysteries in Returnal: Forgotten Abyss.", "expected_label": "horror"},
    {"text": "Defending against zombie hordes in World War Z: Ultimate Horde Mode.", "expected_label": "horror"},
    {"text": "Exploring frozen horrors in Subnautica: Frostbitten Depths.", "expected_label": "horror"},
    {"text": "Uncovering spectral truths in What Remains of Edith Finch: Legacy Edition.", "expected_label": "horror"},
    {"text": "Investigating supernatural echoes in Oxenfree: Silent Signals.", "expected_label": "horror"},
    {"text": "Facing inner demons in Alan Wake 2: Shadows of the Past.", "expected_label": "horror"},
    {"text": "Exploring haunted carnival rides in The Park: Dark Thrills.", "expected_label": "horror"},
    {"text": "Walking through fractured realities in The Medium: Eternal Duality.", "expected_label": "horror"},
    {"text": "Fighting unknown entities in Control: Legacy of Darkness.", "expected_label": "horror"},
    {"text": "Facing surreal terrors in Hellblade: The Last Sacrifice.", "expected_label": "horror"},
    {"text": "Surviving decay in Pathologic 2: A World Unraveled.", "expected_label": "horror"},
    {"text": "Exploring haunted halls in Luigi's Mansion: The Dark Moon.", "expected_label": "horror"},
    {"text": "Solving haunting enigmas in Dark Fall: The Lost Trails.", "expected_label": "horror"},
    {"text": "Uncovering eerie timelines in Eternal Threads: Fractured Paths.", "expected_label": "horror"},
    {"text": "Surviving cursed castles in Dark Souls: The Abyss Awakened.", "expected_label": "horror"},
    {"text": "Unraveling eldritch myths in Siren: Legacy of the Shadows.", "expected_label": "horror"},
    {"text": "Surviving AI terror in Observation: Digital Shadows.", "expected_label": "horror"},
    {"text": "Fleeing monstrous beings in Monstrum: The Final Chapter.", "expected_label": "horror"},
    {"text": "Escaping malicious specters in Pacify: Eternal Haunting.", "expected_label": "horror"},
    {"text": "Fighting malevolent spirits in Malum: Legacy of Shadows.", "expected_label": "horror"},
    {"text": "Exploring sunken horrors in The Sinking City: The Abyss Within.", "expected_label": "horror"},
    {"text": "Walking through ghostly trails in Witch Hunt: Cursed Legends.", "expected_label": "horror"},
    {"text": "Uncovering forbidden stories in Stories Untold: Shadows of the Past.", "expected_label": "horror"},
    {"text": "Investigating eerie enigmas in The Room VR: Legacy of Fear.", "expected_label": "horror"},
    {"text": "Facing tormenting shadows in Tormented Souls: Eternal Darkness.", "expected_label": "horror"},
    {"text": "Exploring cursed lighthouses in Fear the Light: Beyond the Horizon.", "expected_label": "horror"},
    {"text": "Unraveling ancient nightmares in Lovecraft's Untold Stories: Depths of Madness.", "expected_label": "horror"},
    {"text": "Surviving infernal invasions in Doom Eternal: The Final Reckoning.", "expected_label": "horror"},
    {"text": "Exploring eerie depths in Sunless Sea: Legacy of Shadows.", "expected_label": "horror"},
    {"text": "Hiding from spectral entities in White Night: Fragments of Fear.", "expected_label": "horror"},
    {"text": "Escaping paranoia in Knock-Knock: Eternal Dread.", "expected_label": "horror"},
    {"text": "Facing spectral presences in The Dark Occult: Shattered Memories.", "expected_label": "horror"},
    {"text": "Navigating haunted tunnels in Lost in Vivo: Legacy of Fear.", "expected_label": "horror"},
    {"text": "Exploring haunted laboratories in Resident Evil: Umbrella Chronicles.", "expected_label": "horror"},
    {"text": "Facing terrifying mutations in Resident Evil: Revelations.", "expected_label": "horror"},
    {"text": "Uncovering conspiracies in Resident Evil: Operation Raccoon City.", "expected_label": "horror"},
    {"text": "Surviving the horrors of the Silent Hill Arcade.", "expected_label": "horror"},
    {"text": "Navigating nightmarish mazes in Silent Hill HD Collection.", "expected_label": "horror"},
    {"text": "Escaping relentless monsters in Silent Hill: The Escape.", "expected_label": "horror"},
    {"text": "Facing cosmic terrors in Amnesia: Justine.", "expected_label": "horror"},
    {"text": "Hiding from merciless killers in Dead by Daylight: The Artist.", "expected_label": "horror"},
    {"text": "Exploring abandoned hospitals in Outlast: The Asylum.", "expected_label": "horror"},
    {"text": "Avoiding animatronic terrors in Five Nights at Freddy's: Ultimate Custom Night.", "expected_label": "horror"},
    {"text": "Solving twisted mysteries in The Evil Within: Consequences.", "expected_label": "horror"},
    {"text": "Surviving the alien menace in Alien: Colonial Marines.", "expected_label": "horror"},
    {"text": "Battling the infected in Dying Light: The Following.", "expected_label": "horror"},
    {"text": "Navigating eerie ruins in The Forest: Deep Woods.", "expected_label": "horror"},
    {"text": "Walking through surreal nightmares in Layers of Fear: VR Edition.", "expected_label": "horror"},
    {"text": "Solving spectral enigmas in Phasmophobia: Endless Haunt.", "expected_label": "horror"},
    {"text": "Exploring underwater horrors in Soma: Eternal Depths.", "expected_label": "horror"},
    {"text": "Fighting grotesque creatures in Bloodborne: The Hunter's Nightmare.", "expected_label": "horror"},
    {"text": "Exploring haunted waters in Man of Medan: Lost Souls.", "expected_label": "horror"},
    {"text": "Making life-changing decisions in Until Dawn: Dark Reflections.", "expected_label": "horror"},
    {"text": "Unraveling eldritch tales in Call of Cthulhu: The Dark Corners.", "expected_label": "horror"},
    {"text": "Escaping shadowy figures in Slender: The Endless Path.", "expected_label": "horror"},
    {"text": "Surviving twisted landscapes in Darkwood: The Forgotten Forest.", "expected_label": "horror"},
    {"text": "Exploring haunting environments in Little Nightmares: Echoes of Fear.", "expected_label": "horror"},
    {"text": "Investigating eerie happenings in Visage: Phantom Echoes.", "expected_label": "horror"},
    {"text": "Surviving looping corridors in P.T.: The Abyss Returns.", "expected_label": "horror"},
    {"text": "Capturing spectral apparitions in Fatal Frame: Maiden of Black Water.", "expected_label": "horror"},
    {"text": "Resisting insanity in Eternal Darkness: Requiem of Shadows.", "expected_label": "horror"},
    {"text": "Solving dark crimes in Condemned: Shattered Souls.", "expected_label": "horror"},
    {"text": "Fighting necromorphs in Dead Space: Ultimate Nightmare.", "expected_label": "horror"},
    {"text": "Exploring light and darkness in Alan Wake: Return to Shadows.", "expected_label": "horror"},
    {"text": "Surviving tunnels of despair in Metro Redux: Shadows of Chernobyl.", "expected_label": "horror"},
    {"text": "Facing cybernetic terrors in Observer: Eternal Watch.", "expected_label": "horror"},
    {"text": "Navigating cursed bayous in Hunt: Showdown - Phantom Prey.", "expected_label": "horror"},
    {"text": "Making pivotal choices in The Quarry: Shadows of the Woods.", "expected_label": "horror"},
    {"text": "Exploring ancient horrors in House of Ashes: Depths of Terror.", "expected_label": "horror"},
    {"text": "Unraveling alien secrets in Prey: Shadows of the Mind.", "expected_label": "horror"},
    {"text": "Exploring sunken vessels in Narcosis: The Abyss Awaits.", "expected_label": "horror"},
    {"text": "Facing haunting family legacies in Black Mirror: Cursed Reflections.", "expected_label": "horror"},
    {"text": "Escaping infernal dimensions in Agony: The Final Descent.", "expected_label": "horror"},
    {"text": "Avoiding slasher nightmares in The Texas Chain Saw Massacre: Legacy of Fear.", "expected_label": "horror"},
    {"text": "Fighting cursed specters in Devil Daggers: Abyssal Nightmares.", "expected_label": "horror"},
    {"text": "Exploring eerie schools in White Day: Nightfall Chronicles.", "expected_label": "horror"},
    {"text": "Facing folkloric apparitions in Maid of Sker: Eternal Echoes.", "expected_label": "horror"},
    {"text": "Investigating haunted memories in Detention: Final Haunting.", "expected_label": "horror"},
    {"text": "Surviving irradiated horrors in Stalker: Eternal Shadows.", "expected_label": "horror"},
    {"text": "Uncovering ghostly tales in Returnal: The Phantom Abyss.", "expected_label": "horror"},
    {"text": "Defending against zombies in World War Z: Nightmare Mode.", "expected_label": "horror"},
    {"text": "Exploring icy abysses in Subnautica: Frozen Shadows.", "expected_label": "horror"},
    {"text": "Uncovering family tragedies in What Remains of Edith Finch: Lost Legacies.", "expected_label": "horror"},
    {"text": "Investigating supernatural waves in Oxenfree: The Silent Frequencies.", "expected_label": "horror"},
    {"text": "Facing sinister memories in Alan Wake 2: The Final Chapters.", "expected_label": "horror"},
    {"text": "Exploring haunted fairgrounds in The Park: Dark Reflections.", "expected_label": "horror"},
    {"text": "Walking eerie dimensions in The Medium: Shattered Minds.", "expected_label": "horror"},
    {"text": "Fighting paranormal foes in Control: The Last Shadows.", "expected_label": "horror"},
    {"text": "Facing surreal nightmares in Hellblade: The Eternal Offering.", "expected_label": "horror"},
    {"text": "Surviving sickness in Pathologic 2: The Final Plague.", "expected_label": "horror"},
    {"text": "Exploring haunted rooms in Luigi's Mansion: Hidden Horrors.", "expected_label": "horror"},
    {"text": "Solving ghostly enigmas in Dark Fall: Phantom Shadows.", "expected_label": "horror"},
    {"text": "Unraveling twisted realities in Eternal Threads: The Abyss Chronicles.", "expected_label": "horror"},
    {"text": "Surviving cursed dungeons in Dark Souls: Shadows of the Abyss.", "expected_label": "horror"},
    {"text": "Unraveling eerie myths in Siren: Cursed Reflections.", "expected_label": "horror"},
    {"text": "Facing AI-driven terror in Observation: The Final Watch.", "expected_label": "horror"},
    {"text": "Escaping monstrous terrors in Monstrum: Eternal Fear.", "expected_label": "horror"},
    {"text": "Avoiding spectral forces in Pacify: Night of the Shadows.", "expected_label": "horror"},
    {"text": "Fighting demonic entities in Malum: Darkened Souls.", "expected_label": "horror"},
    {"text": "Exploring sunken terrors in The Sinking City: Abyssal Echoes.", "expected_label": "horror"},
    {"text": "Walking ghostly paths in Witch Hunt: The Final Shadows.", "expected_label": "horror"},
    {"text": "Uncovering forbidden enigmas in Stories Untold: Depths of Fear.", "expected_label": "horror"},
    {"text": "Investigating haunted locations in The Room VR: Legacy of Haunting.", "expected_label": "horror"},
    {"text": "Facing tormenting beings in Tormented Souls: Phantom Abyss.", "expected_label": "horror"},
    {"text": "Exploring cursed beacons in Fear the Light: Eternal Shadows.", "expected_label": "horror"},
    {"text": "Unraveling ancient nightmares in Lovecraft's Untold Stories: Final Horrors.", "expected_label": "horror"},
    {"text": "Surviving infernal invasions in Doom Eternal: Shadows of the Abyss.", "expected_label": "horror"},
    {"text": "Exploring haunted seas in Sunless Sea: Phantom Depths.", "expected_label": "horror"},
    {"text": "Escaping spectral horrors in White Night: Shattered Dreams.", "expected_label": "horror"},
    {"text": "Facing paranoia in Knock-Knock: Eternal Whispers.", "expected_label": "horror"},
    {"text": "Navigating haunted ruins in The Dark Occult: Shadows of Fear.", "expected_label": "horror"},
    {"text": "Exploring haunted depths in Lost in Vivo: The Final Descent.", "expected_label": "horror"},
    {"text": "Fighting off bioweapons in Resident Evil 5: Lost in Nightmares.", "expected_label": "horror"},
    {"text": "Surviving the horrors of Raccoon City in Resident Evil Outbreak.", "expected_label": "horror"},
    {"text": "Exploring eerie environments in Resident Evil: Revelations 2.", "expected_label": "horror"},
    {"text": "Escaping from sinister forces in Silent Hill: The Arcade.", "expected_label": "horror"},
    {"text": "Facing psychological threats in Silent Hill HD Collection.", "expected_label": "horror"},
    {"text": "Navigating haunted streets in Silent Hill: Mobile.", "expected_label": "horror"},
    {"text": "Fleeing from a relentless monster in Amnesia: The Dark Descent.", "expected_label": "horror"},
    {"text": "Surviving deadly killers in Dead by Daylight: Sadako Rising.", "expected_label": "horror"},
    {"text": "Uncovering twisted experiments in Outlast 2.", "expected_label": "horror"},
    {"text": "Avoiding animatronics in Five Nights at Freddy's: Sister Location.", "expected_label": "horror"},
    {"text": "Exploring surreal nightmares in The Evil Within: The Consequence.", "expected_label": "horror"},
    {"text": "Hiding from a deadly alien in Alien: Isolation.", "expected_label": "horror"},
    {"text": "Fighting infected swarms in Dying Light 2: The Following.", "expected_label": "horror"},
    {"text": "Navigating haunted forests in The Forest VR.", "expected_label": "horror"},
    {"text": "Walking through chilling corridors in Layers of Fear VR.", "expected_label": "horror"},
    {"text": "Investigating haunted locations in Phasmophobia.", "expected_label": "horror"},
    {"text": "Exploring the depths of fear in Soma.", "expected_label": "horror"},
    {"text": "Battling horrifying creatures in Bloodborne.", "expected_label": "horror"},
    {"text": "Unraveling a maritime mystery in Man of Medan.", "expected_label": "horror"},
    {"text": "Making tough choices in Until Dawn.", "expected_label": "horror"},
    {"text": "Facing cosmic terror in Call of Cthulhu.", "expected_label": "horror"},
    {"text": "Evading a faceless predator in Slender: The Eight Pages.", "expected_label": "horror"},
    {"text": "Exploring cursed woods in Darkwood.", "expected_label": "horror"},
    {"text": "Surviving haunting realms in Little Nightmares 2.", "expected_label": "horror"},
    {"text": "Investigating ghostly echoes in Visage.", "expected_label": "horror"},
    {"text": "Escaping endless corridors in P.T.", "expected_label": "horror"},
    {"text": "Capturing supernatural forces in Fatal Frame: Mask of the Lunar Eclipse.", "expected_label": "horror"},
    {"text": "Resisting madness in Eternal Darkness.", "expected_label": "horror"},
    {"text": "Solving macabre mysteries in Condemned: Criminal Origins.", "expected_label": "horror"},
    {"text": "Battling necromorphs in Dead Space 2.", "expected_label": "horror"},
    {"text": "Uncovering light and dark in Alan Wake: American Nightmare.", "expected_label": "horror"},
    {"text": "Navigating mutant-filled tunnels in Metro 2033.", "expected_label": "horror"},
    {"text": "Exploring haunting technologies in Observer.", "expected_label": "horror"},
    {"text": "Surviving supernatural horrors in Hunt: Showdown.", "expected_label": "horror"},
    {"text": "Facing tough decisions in The Quarry.", "expected_label": "horror"},
    {"text": "Unraveling sinister curses in House of Ashes.", "expected_label": "horror"},
    {"text": "Escaping alien nightmares in Prey.", "expected_label": "horror"},
    {"text": "Exploring deep-sea terror in Narcosis.", "expected_label": "horror"},
    {"text": "Uncovering chilling family secrets in Black Mirror.", "expected_label": "horror"},
    {"text": "Escaping the depths of hell in Agony.", "expected_label": "horror"},
    {"text": "Surviving slasher chaos in The Texas Chain Saw Massacre.", "expected_label": "horror"},
    {"text": "Facing cursed horrors in Devil Daggers.", "expected_label": "horror"},
    {"text": "Exploring haunted halls in White Day.", "expected_label": "horror"},
    {"text": "Navigating sinister paths in Maid of Sker.", "expected_label": "horror"},
    {"text": "Unraveling haunting truths in Detention.", "expected_label": "horror"},
    {"text": "Battling irradiated nightmares in Stalker: Call of Pripyat.", "expected_label": "horror"},
    {"text": "Exploring spectral mysteries in Returnal.", "expected_label": "horror"},
    {"text": "Fending off undead swarms in World War Z.", "expected_label": "horror"},
    {"text": "Navigating frozen depths in Subnautica: Below Zero.", "expected_label": "horror"},
    {"text": "Uncovering haunting stories in What Remains of Edith Finch.", "expected_label": "horror"},
    {"text": "Investigating supernatural frequencies in Oxenfree.", "expected_label": "horror"},
    {"text": "Facing inner darkness in Alan Wake 2.", "expected_label": "horror"},
    {"text": "Exploring haunted attractions in The Park.", "expected_label": "horror"},
    {"text": "Navigating eerie dimensions in The Medium.", "expected_label": "horror"},
    {"text": "Fighting paranormal entities in Control.", "expected_label": "horror"},
    {"text": "Facing unsettling realities in Hellblade.", "expected_label": "horror"},
    {"text": "Surviving sickness and despair in Pathologic 2.", "expected_label": "horror"},
    {"text": "Exploring ghostly mansions in Luigi's Mansion.", "expected_label": "horror"},
    {"text": "Unraveling sinister enigmas in Dark Fall.", "expected_label": "horror"},
    {"text": "Exploring haunting fates in Eternal Threads.", "expected_label": "horror"},
    {"text": "Surviving cursed castles in Dark Souls.", "expected_label": "horror"},
    {"text": "Unraveling eerie legends in Siren.", "expected_label": "horror"},
    {"text": "Facing haunting AI in Observation.", "expected_label": "horror"},
    {"text": "Escaping monstrous predators in Monstrum.", "expected_label": "horror"},
    {"text": "Fleeing from spectral forces in Pacify.", "expected_label": "horror"},
    {"text": "Defending against demonic beings in Malum.", "expected_label": "horror"},
    {"text": "Exploring haunted depths in The Sinking City.", "expected_label": "horror"},
    {"text": "Navigating ghostly trails in Witch Hunt.", "expected_label": "horror"},
    {"text": "Uncovering dark stories in Stories Untold.", "expected_label": "horror"},
    {"text": "Investigating cursed puzzles in The Room.", "expected_label": "horror"},
    {"text": "Unraveling spectral fates in Tormented Souls.", "expected_label": "horror"},
    {"text": "Exploring cursed beacons in Fear the Light.", "expected_label": "horror"},
    {"text": "Uncovering eldritch horrors in Lovecraft's Untold Stories.", "expected_label": "horror"},
    {"text": "Fending off demonic invasions in Doom Eternal.", "expected_label": "horror"},
    {"text": "Exploring eerie waters in Sunless Sea.", "expected_label": "horror"},
    {"text": "Escaping spectral apparitions in White Night.", "expected_label": "horror"},
    {"text": "Hiding from sinister beings in Knock-Knock.", "expected_label": "horror"},
    {"text": "Facing supernatural presences in The Dark Occult.", "expected_label": "horror"},
    {"text": "Exploring cursed pathways in Lost in Vivo.", "expected_label": "horror"},
    {"text": "Solving eerie murders in The Painscreek Killings.", "expected_label": "horror"},
    {"text": "Fighting spectral forces in Ghostwire: Tokyo.", "expected_label": "horror"},
    {"text": "Uncovering dark enigmas in Inscryption.", "expected_label": "horror"},
    {"text": "Exploring ghostly estates in Don't Knock Twice.", "expected_label": "horror"},
    {"text": "Unraveling haunted mysteries in The Beast Inside.", "expected_label": "horror"},
    {"text": "Navigating haunted exhibits in Haunt Chaser.", "expected_label": "horror"},
    {"text": "Facing spectral echoes in Devotion.", "expected_label": "horror"},
    {"text": "Exploring derelict spaceships in Dead Effect.", "expected_label": "horror"},
    {"text": "Escaping AI-driven nightmares in Routine.", "expected_label": "horror"},
    {"text": "Facing psychological fear in The Cat Lady.", "expected_label": "horror"},
    {"text": "Exploring haunted forests in Blair Witch.", "expected_label": "horror"},
    {"text": "Sailing ghostly waters in The Boatman's Song.", "expected_label": "horror"},
    {"text": "Uncovering cult horrors in The Blackout Club.", "expected_label": "horror"},
    {"text": "Facing cursed apparitions in The Council.", "expected_label": "horror"}
]