shooter_data = [
    {"text": "Engaging in intense firefights in Call of Duty", "expected_label": "shooter"},
    {"text": "Precision aiming and tactics in Counter Strike: Global Offensive", "expected_label": "shooter"},
    {"text": "Enjoying fast-paced battles in Apex Legends", "expected_label": "shooter"},
    {"text": "Blasting through enemies in DOOM Eternal", "expected_label": "shooter"},
    {"text": "Coordinating with my squad in Rainbow Six Siege", "expected_label": "shooter"},
    {"text": "Mastering sniping in Battlefield V", "expected_label": "shooter"},
    {"text": "Fighting off alien hordes in Halo Infinite", "expected_label": "shooter"},
    {"text": "Surviving waves of enemies in Left 4 Dead 2", "expected_label": "shooter"},
    {"text": "Reliving World War II battles in Medal of Honor", "expected_label": "shooter"},
    {"text": "Exploring tactical scenarios in Insurgency: Sandstorm", "expected_label": "shooter"},
    {"text": "Rushing through chaotic maps in Quake Champions", "expected_label": "shooter"},
    {"text": "Using a wide array of weapons in Destiny 2", "expected_label": "shooter"},
    {"text": "Fighting for survival in PUBG: Battlegrounds", "expected_label": "shooter"},
    {"text": "Hunting for loot in Escape from Tarkov", "expected_label": "shooter"},
    {"text": "Competing in fast-paced rounds of Valorant", "expected_label": "shooter"},
    {"text": "Exploring the Wild West in Red Dead Redemption's gunfights", "expected_label": "shooter"},
    {"text": "Sniping enemies in Ghost Recon Breakpoint", "expected_label": "shooter"},
    {"text": "Fighting intense naval battles in World of Warships", "expected_label": "shooter"},
    {"text": "Engaging in futuristic combat in Titanfall 2", "expected_label": "shooter"},
    {"text": "Leading a squad in Battlefield 2042", "expected_label": "shooter"},
    {"text": "Fighting alien invasions in Crysis 3", "expected_label": "shooter"},
    {"text": "Fighting robot hordes in Generation Zero", "expected_label": "shooter"},
    {"text": "Shooting enemies with precision in Sniper Elite 4", "expected_label": "shooter"},
    {"text": "Taking down opponents in Overwatch", "expected_label": "shooter"},
    {"text": "Fighting gang wars in Max Payne 3", "expected_label": "shooter"},
    {"text": "Exploring tactical missions in Spec Ops: The Line", "expected_label": "shooter"},
    {"text": "Shooting through levels in Hotline Miami", "expected_label": "shooter"},
    {"text": "Mastering the arena in Unreal Tournament", "expected_label": "shooter"},
    {"text": "Dodging bullets in Superhot", "expected_label": "shooter"},
    {"text": "Fighting mutant armies in Metro Exodus", "expected_label": "shooter"},
    {"text": "Exploring the horrors of Fear", "expected_label": "shooter"},
    {"text": "Hunting creatures in Hunt: Showdown", "expected_label": "shooter"},
    {"text": "Participating in WWI battles in Verdun", "expected_label": "shooter"},
    {"text": "Surviving post-apocalyptic battles in Fallout 76", "expected_label": "shooter"},
    {"text": "Fighting space pirates in Prey", "expected_label": "shooter"},
    {"text": "Competing in high-stakes matches in Warface", "expected_label": "shooter"},
    {"text": "Engaging in sci-fi battles in Destiny 2", "expected_label": "shooter"},
    {"text": "Leading covert missions in Splinter Cell", "expected_label": "shooter"},
    {"text": "Fighting for resources in The Division 2", "expected_label": "shooter"},
    {"text": "Taking on crime syndicates in Just Cause 4", "expected_label": "shooter"},
    {"text": "Shooting zombies in Back 4 Blood", "expected_label": "shooter"},
    {"text": "Fighting robot overlords in Half-Life 2", "expected_label": "shooter"},
    {"text": "Fighting alien creatures in Aliens: Fireteam Elite", "expected_label": "shooter"},
    {"text": "Shooting enemies in intense multiplayer matches in Blacklight: Retribution", "expected_label": "shooter"},
    {"text": "Defending the world in Earth Defense Force 5", "expected_label": "shooter"},
    {"text": "Fighting in team-based objectives in Enemy Territory: Quake Wars", "expected_label": "shooter"},
    {"text": "Blasting monsters in Painkiller", "expected_label": "shooter"},
    {"text": "Battling enemies in Borderlands 2's cel-shaded world", "expected_label": "shooter"},
    {"text": "Destroying the opposition in LawBreakers", "expected_label": "shooter"},
    {"text": "Taking on terrorists in America's Army", "expected_label": "shooter"},
    {"text": "Executing stealth kills in Sniper Ghost Warrior", "expected_label": "shooter"},
    {"text": "Engaging in space battles with lasers in Star Wars: Battlefront", "expected_label": "shooter"},
    {"text": "Fighting through futuristic levels in Warframe", "expected_label": "shooter"},
    {"text": "Joining large-scale battles in PlanetSide 2", "expected_label": "shooter"},
    {"text": "Defending objectives in Team Fortress 2", "expected_label": "shooter"},
    {"text": "Dodging missiles in Serious Sam", "expected_label": "shooter"},
    {"text": "Taking on missions in Operation Flashpoint", "expected_label": "shooter"},
    {"text": "Fighting for survival in Arma 3", "expected_label": "shooter"},
    {"text": "Taking part in sci-fi warfare in Killzone Shadow Fall", "expected_label": "shooter"},
    {"text": "Battling in multiplayer arenas in Crossfire", "expected_label": "shooter"},
    {"text": "Exploring apocalyptic ruins in S.T.A.L.K.E.R.: Shadow of Chernobyl", "expected_label": "shooter"},
    {"text": "Blasting mutants in Rage 2", "expected_label": "shooter"},
    {"text": "Surviving the wasteland in Borderlands 3", "expected_label": "shooter"},
    {"text": "Engaging in gunfights in The Darkness II", "expected_label": "shooter"},
    {"text": "Clearing enemies in Gears of War", "expected_label": "shooter"},
    {"text": "Competing in intense multiplayer matches in CrossfireX", "expected_label": "shooter"},
    {"text": "Fighting off aliens in The Bureau: XCOM Declassified", "expected_label": "shooter"},
    {"text": "Exploring vast maps in Battlefield 1", "expected_label": "shooter"},
    {"text": "Shooting your way through enemies in Homefront: The Revolution", "expected_label": "shooter"},
    {"text": "Clearing zombie-infested areas in World War Z", "expected_label": "shooter"},
    {"text": "Surviving relentless waves in Killing Floor 2", "expected_label": "shooter"},
    {"text": "Blasting demons in Shadow Warrior", "expected_label": "shooter"},
    {"text": "Fighting tactical battles in Squad", "expected_label": "shooter"},
    {"text": "Hunting for prey in Predator: Hunting Grounds", "expected_label": "shooter"},
    {"text": "Fighting for freedom in Far Cry 5", "expected_label": "shooter"},
    {"text": "Fighting on the frontlines in Enemy Front", "expected_label": "shooter"},
    {"text": "Taking down bounties in Red Dead Redemption 2's Deadeye mode", "expected_label": "shooter"},
    {"text": "Shooting your way through cyberpunk streets in Cyberpunk 2077", "expected_label": "shooter"},
    {"text": "Taking down targets in 007 Legends", "expected_label": "shooter"},
    {"text": "Blasting away enemies in Metal Gear Survive", "expected_label": "shooter"},
    {"text": "Leading tactical combat in Tom Clancy's Ghost Recon Wildlands", "expected_label": "shooter"},
    {"text": "Fighting in post-apocalyptic cities in Metro: Last Light", "expected_label": "shooter"},
    {"text": "Clearing alien bases in XCOM: Chimera Squad", "expected_label": "shooter"},
    {"text": "Battling mechs in Titanfall", "expected_label": "shooter"},
    {"text": "Exploring wild zones with guns blazing in Just Cause 3", "expected_label": "shooter"},
    {"text": "Clearing dungeons in Gunfire Reborn", "expected_label": "shooter"},
    {"text": "Fighting in epic WWII campaigns in Company of Heroes", "expected_label": "shooter"},
    {"text": "Using cutting-edge weapons in Star Citizen's FPS mode", "expected_label": "shooter"},
    {"text": "Engaging in high-stakes warfare in Advanced Warfare", "expected_label": "shooter"},
    {"text": "Fighting in desert battles in Spec Ops: Desert Storm", "expected_label": "shooter"},
    {"text": "Blowing up enemy camps in Far Cry Primal", "expected_label": "shooter"},
    {"text": "Battling hordes of zombies in State of Decay", "expected_label": "shooter"},
    {"text": "Fighting mutants in bullet-time in Max Payne", "expected_label": "shooter"},
    {"text": "Racking up kills in a futuristic battlefield in Section 8", "expected_label": "shooter"},
    {"text": "Shooting in stealthy combat in Tom Clancy's Splinter Cell: Conviction", "expected_label": "shooter"},
    {"text": "Fighting to survive in a brutal FPS rogue-lite, Void Bastards", "expected_label": "shooter"},
    {"text": "Surviving relentless machine enemies in Horizon: Zero Dawn", "expected_label": "shooter"},
    {"text": "Fighting massive dinosaurs in Second Extinction", "expected_label": "shooter"},
    {"text": "Competing in futuristic multiplayer modes in LawBreakers", "expected_label": "shooter"},
    {"text": "Engaging in intense combat missions in Doom Eternal", "expected_label": "shooter"},
    {"text": "Shooting targets in a simulation in Gun Club VR", "expected_label": "shooter"},
    {"text": "Sniping enemies from rooftops in Sniper Elite 5", "expected_label": "shooter"},
    {"text": "Clearing a desert outpost in Medal of Honor", "expected_label": "shooter"},
    {"text": "Participating in a futuristic war in Blacklight: Retribution", "expected_label": "shooter"},
    {"text": "Fighting crime in city streets in RoboCop: Rogue City", "expected_label": "shooter"},
    {"text": "Blasting through alien hives in Earth Defense Force", "expected_label": "shooter"},
    {"text": "Engaging in close-quarters combat in Rainbow Six Extraction", "expected_label": "shooter"},
    {"text": "Shooting enemies in a dystopian future in Syndicate", "expected_label": "shooter"},
    {"text": "Firing plasma weapons in Unreal Tournament", "expected_label": "shooter"},
    {"text": "Defending the galaxy in Mass Effect's action segments", "expected_label": "shooter"},
    {"text": "Engaging in cyberpunk combat in Deus Ex: Mankind Divided", "expected_label": "shooter"},
    {"text": "Fighting robotic enemies in Binary Domain", "expected_label": "shooter"},
    {"text": "Hunting dinosaurs in Primal Carnage", "expected_label": "shooter"},
    {"text": "Competing in military-style multiplayer in Warface", "expected_label": "shooter"},
    {"text": "Clearing a haunted swamp in Hunt: Showdown", "expected_label": "shooter"},
    {"text": "Fighting terrorists in Counter Strike Nexon", "expected_label": "shooter"},
    {"text": "Taking down zombies in Zombieland: Double Tap", "expected_label": "shooter"},
    {"text": "Exploring abandoned facilities with weapons in F.E.A.R.", "expected_label": "shooter"},
    {"text": "Blowing up alien ships in Alien Rage", "expected_label": "shooter"},
    {"text": "Clearing a jungle stronghold in Crysis", "expected_label": "shooter"},
    {"text": "Participating in gritty urban combat in Army of Two", "expected_label": "shooter"},
    {"text": "Hunting enemy commanders in Brothers in Arms", "expected_label": "shooter"},
    {"text": "Fighting on icy tundras in Lost Planet 2", "expected_label": "shooter"},
    {"text": "Shooting through medieval environments in Darkwatch", "expected_label": "shooter"},
    {"text": "Fighting high-tech enemies in Singularity", "expected_label": "shooter"},
    {"text": "Taking on bounties in Gunslinger mode in Call of Juarez", "expected_label": "shooter"},
    {"text": "Defending humanity in Resistance: Fall of Man", "expected_label": "shooter"},
    {"text": "Clearing battlefields in Enemy Territory: Quake Wars", "expected_label": "shooter"},
    {"text": "Fighting zombie hordes in Left 4 Dead 2", "expected_label": "shooter"},
    {"text": "Engaging in supernatural gunfights in Bulletstorm", "expected_label": "shooter"},
    {"text": "Shooting through an alien invasion in Halo Infinite", "expected_label": "shooter"},
    {"text": "Clearing space stations in Warhammer 40,000: Darktide", "expected_label": "shooter"},
    {"text": "Hunting down gang members in Kane & Lynch", "expected_label": "shooter"},
    {"text": "Battling AI enemies in Evolve", "expected_label": "shooter"},
    {"text": "Firing explosive rounds in TimeSplitters 2", "expected_label": "shooter"},
    {"text": "Fighting bosses in Tiny Tina's Wonderlands", "expected_label": "shooter"},
    {"text": "Engaging in epic sci-fi battles in Disintegration", "expected_label": "shooter"},
    {"text": "Shooting through surreal dreamscapes in Control", "expected_label": "shooter"},
    {"text": "Taking on drug cartels in Ghost Recon: Breakpoint", "expected_label": "shooter"},
    {"text": "Clearing military bunkers in Soldier of Fortune", "expected_label": "shooter"},
    {"text": "Fighting in large-scale battles in BattleCry", "expected_label": "shooter"},
    {"text": "Defending against an AI uprising in Generation Zero", "expected_label": "shooter"},
    {"text": "Hunting dangerous monsters in Turok", "expected_label": "shooter"},
    {"text": "Engaging in tactical team matches in Valorant", "expected_label": "shooter"},
    {"text": "Taking control of a gunship in Gunship Elite", "expected_label": "shooter"},
    {"text": "Blasting enemies in space in Chorus", "expected_label": "shooter"},
    {"text": "Exploring a post-apocalyptic wasteland in Fallout 76", "expected_label": "shooter"},
    {"text": "Clearing seedy nightclubs in Hotline Miami", "expected_label": "shooter"},
    {"text": "Infiltrating enemy bases with advanced weapons in Battlefield V", "expected_label": "shooter"},
    {"text": "Launching grenade attacks in Insurgency: Sandstorm", "expected_label": "shooter"},
    {"text": "Clearing skyscraper floors in SWAT 4", "expected_label": "shooter"},
    {"text": "Engaging in futuristic combat in Warframe", "expected_label": "shooter"},
    {"text": "Taking down mutant creatures in Metro Exodus", "expected_label": "shooter"},
    {"text": "Flying through space while shooting enemies in Star Wars: Squadrons", "expected_label": "shooter"},
    {"text": "Challenging rival teams in Overwatch 2", "expected_label": "shooter"},
    {"text": "Defending colonies on alien planets in Starship Troopers: Extermination", "expected_label": "shooter"},
    {"text": "Hunting vampires with firearms in Redfall", "expected_label": "shooter"},
    {"text": "Participating in realistic war scenarios in ARMA 3", "expected_label": "shooter"},
    {"text": "Firing high-tech laser weapons in Destiny 2", "expected_label": "shooter"},
    {"text": "Taking cover and firing in intense firefights in Gears 5", "expected_label": "shooter"},
    {"text": "Fighting robotic invaders in Binary Star Infinity", "expected_label": "shooter"},
    {"text": "Engaging in medieval-style gunfights in Weird West", "expected_label": "shooter"},
    {"text": "Sniping enemy vehicles in Sniper Ghost Warrior Contracts", "expected_label": "shooter"},
    {"text": "Exploring a dark cyberpunk city in Hard Reset", "expected_label": "shooter"},
    {"text": "Engaging in gladiator-style combat in Shadow Warrior 3", "expected_label": "shooter"},
    {"text": "Fighting through zombie-infested cities in Back 4 Blood", "expected_label": "shooter"},
    {"text": "Defending outposts against bandits in Rage 2", "expected_label": "shooter"},
    {"text": "Piloting advanced mechs in Titanfall 2", "expected_label": "shooter"},
    {"text": "Scouting enemy territory in Far Cry 5", "expected_label": "shooter"},
    {"text": "Firing railguns in the neon-lit arenas of Midnight Fight Express", "expected_label": "shooter"},
    {"text": "Blasting through hordes of enemies in Helldivers", "expected_label": "shooter"},
    {"text": "Engaging in stealth sniping missions in Ghost Recon Wildlands", "expected_label": "shooter"},
    {"text": "Fighting enemy warlords in Bulletstorm: Full Clip Edition", "expected_label": "shooter"},
    {"text": "Defending Earth against alien invaders in XCOM: Chimera Squad", "expected_label": "shooter"},
    {"text": "Competing in deadly arena matches in Splitgate", "expected_label": "shooter"},
    {"text": "Fighting supernatural enemies in Painkiller: Hell & Damnation", "expected_label": "shooter"},
    {"text": "Surviving post-apocalyptic firefights in STALKER 2", "expected_label": "shooter"},
    {"text": "Rescuing hostages in counter-terrorist missions in Black", "expected_label": "shooter"},
    {"text": "Eliminating enemy squads in intense multiplayer matches in Hyper Scape", "expected_label": "shooter"},
    {"text": "Dueling other players in high-stakes shootouts in High Noon VR", "expected_label": "shooter"},
    {"text": "Navigating war-torn environments in Call of Duty: Vanguard", "expected_label": "shooter"},
    {"text": "Firing energy weapons in a dystopian future in Killzone Shadow Fall", "expected_label": "shooter"},
    {"text": "Taking control of powerful tanks in Battlefield 2042", "expected_label": "shooter"},
    {"text": "Fighting cyborg enemies in Deus Ex: Invisible War", "expected_label": "shooter"},
    {"text": "Surviving endless waves of monsters in Serious Sam 4", "expected_label": "shooter"},
    {"text": "Competing in galactic tournaments in Rocket Arena", "expected_label": "shooter"},
    {"text": "Exploring underwater bases while armed in BioShock 2", "expected_label": "shooter"},
    {"text": "Fighting rival cartels in Narco Road", "expected_label": "shooter"},
    {"text": "Challenging rogue soldiers in Spec Ops: The Line", "expected_label": "shooter"},
    {"text": "Testing combat skills in the arenas of Quake Champions", "expected_label": "shooter"},
    {"text": "Fighting mutant creatures in The Darkness II", "expected_label": "shooter"},
    {"text": "Taking down airships in steampunk battles in Guns of Icarus Online", "expected_label": "shooter"},
    {"text": "Clearing hostile space stations in Prey (2017)", "expected_label": "shooter"},
    {"text": "Firing arrows and crossbows in the fantasy realm of Dishonored 2", "expected_label": "shooter"},
    {"text": "Defending moon colonies in Borderlands: The Pre-Sequel", "expected_label": "shooter"},
    {"text": "Shooting enemy drones in futuristic combat in Watch Dogs Legion", "expected_label": "shooter"},
    {"text": "Hunting massive alien creatures in Second Extinction", "expected_label": "shooter"},
    {"text": "Fighting supernatural forces in Immortal Redneck", "expected_label": "shooter"},
    {"text": "Engaging in western-style duels in Outlaws: Reloaded", "expected_label": "shooter"},
    {"text": "Fighting against terrorists in Counter Strike", "expected_label": "shooter"},
    {"text": "Engaging in firefights in Call of Duty: Black Ops", "expected_label": "shooter"},
    {"text": "Shooting down enemies in Battlefield 3", "expected_label": "shooter"},
    {"text": "Taking down mutants in Metro: Last Light", "expected_label": "shooter"},
    {"text": "Fighting against soldiers in Call of Duty: Warzone", "expected_label": "shooter"},
    {"text": "Joining a team to win tactical missions in Rainbow Six Siege", "expected_label": "shooter"},
    {"text": "Shooting zombies in Left 4 Dead", "expected_label": "shooter"},
    {"text": "Surviving and shooting your way out in PUBG", "expected_label": "shooter"},
    {"text": "Fighting aliens in Halo: Combat Evolved", "expected_label": "shooter"},
    {"text": "Shooting robotic enemies in Titanfall 2", "expected_label": "shooter"},
    {"text": "Leading a squad in modern warfare in Battlefield 1", "expected_label": "shooter"},
    {"text": "Engaging in battles to protect colonies in Destiny", "expected_label": "shooter"},
    {"text": "Blasting through hordes of mutants in Rage", "expected_label": "shooter"},
    {"text": "Taking down criminals in PayDay 2", "expected_label": "shooter"},
    {"text": "Leading an assault in futuristic warfare in Killzone", "expected_label": "shooter"},
    {"text": "Fighting criminals in high-speed chase in Call of Juarez", "expected_label": "shooter"},
    {"text": "Shooting through post-apocalyptic city in The Division", "expected_label": "shooter"},
    {"text": "Engaging in tactical sniper missions in Sniper Elite", "expected_label": "shooter"},
    {"text": "Fighting in urban combat in Spec Ops: The Line", "expected_label": "shooter"},
    {"text": "Using laser guns in space fights in Star Wars Battlefront", "expected_label": "shooter"},
    {"text": "Surviving horror and shooting enemies in F.E.A.R", "expected_label": "shooter"},
    {"text": "Blowing up enemy vehicles in Just Cause 2", "expected_label": "shooter"},
    {"text": "Clearing enemy bases in Call of Duty: Vanguard", "expected_label": "shooter"},
    {"text": "Destroying hordes of zombies in Killing Floor 2", "expected_label": "shooter"},
    {"text": "Engaging in intense firefights in Battlefield 5", "expected_label": "shooter"},
    {"text": "Fighting off demons in Doom Eternal", "expected_label": "shooter"},
    {"text": "Sniping enemies in open fields in Ghost Recon", "expected_label": "shooter"},
    {"text": "Fighting in large-scale multiplayer in Battlefront II", "expected_label": "shooter"},
    {"text": "Exploring derelict ships and shooting aliens in Prey", "expected_label": "shooter"},
    {"text": "Taking down alien invaders in XCOM", "expected_label": "shooter"},
    {"text": "Engaging in arena-based matches in Quake", "expected_label": "shooter"},
    {"text": "Fighting against warlords in Far Cry 5", "expected_label": "shooter"},
    {"text": "Blasting your way through levels in Duke Nukem", "expected_label": "shooter"},
    {"text": "Using rocket launchers in Turok", "expected_label": "shooter"},
    {"text": "Surviving and shooting enemies in Fortnite", "expected_label": "shooter"},
    {"text": "Defending against an alien invasion in Crysis 2", "expected_label": "shooter"},
    {"text": "Clearing out dungeons in Gunfire Reborn", "expected_label": "shooter"},
    {"text": "Participating in futuristic battles in Unreal Tournament", "expected_label": "shooter"},
    {"text": "Shooting through streets in Homefront: The Revolution", "expected_label": "shooter"},
    {"text": "Joining a military squad in realistic combat in Arma 3", "expected_label": "shooter"},
    {"text": "Shooting undead enemies in Dead Island", "expected_label": "shooter"},
    {"text": "Taking control in deathmatch in Counter-Strike: Source", "expected_label": "shooter"},
    {"text": "Fighting space pirates in Aliens: Colonial Marines", "expected_label": "shooter"},
    {"text": "Leading futuristic missions in Halo 3", "expected_label": "shooter"},
    {"text": "Defending against bandits in Mad Max", "expected_label": "shooter"},
    {"text": "Firing plasma weapons in Call of Duty: Infinite Warfare", "expected_label": "shooter"},
    {"text": "Shooting mutated enemies in Resident Evil Village", "expected_label": "shooter"},
    {"text": "Fighting warlords in Far Cry Primal", "expected_label": "shooter"},
    {"text": "Fighting enemies in Titanfall's multiplayer matches", "expected_label": "shooter"},
    {"text": "Fighting in urban combat against crime syndicates in Kane & Lynch", "expected_label": "shooter"},
    {"text": "Surviving relentless waves in Serious Sam 3", "expected_label": "shooter"},
    {"text": "Blowing up enemy ships in Earth Defense Force", "expected_label": "shooter"},
    {"text": "Fighting alien robots in Resistance 2", "expected_label": "shooter"},
    {"text": "Using crossbows to take down enemies in Dishonored", "expected_label": "shooter"},
    {"text": "Fighting your way through hostile territories in Far Cry 4", "expected_label": "shooter"},
    {"text": "Surviving the horrors and shooting ghosts in F.E.A.R 2", "expected_label": "shooter"},
    {"text": "Taking down space marines in DOOM (2016)", "expected_label": "shooter"},
    {"text": "Fighting through broken cities in Metro 2033", "expected_label": "shooter"},
    {"text": "Engaging in sniper missions in Sniper Ghost Warrior Contracts", "expected_label": "shooter"},
    {"text": "Clearing enemy bunkers in Soldier of Fortune", "expected_label": "shooter"},
    {"text": "Defending the planet in futuristic battles in Anthem", "expected_label": "shooter"},
    {"text": "Fighting mercenaries in Ghost Recon Breakpoint", "expected_label": "shooter"},
    {"text": "Fighting crime in Judge Dredd vs Death", "expected_label": "shooter"},
    {"text": "Engaging in firefights across urban landscapes in Homefront", "expected_label": "shooter"},
    {"text": "Participating in tactical stealth missions in Splinter Cell: Blacklist", "expected_label": "shooter"},
    {"text": "Shooting through monsters in Warhammer: Vermintide 2", "expected_label": "shooter"},
    {"text": "Blasting away enemies in Painkiller: Black Edition", "expected_label": "shooter"},
    {"text": "Firing energy weapons in futuristic combat in Destiny", "expected_label": "shooter"},
    {"text": "Engaging in tactical shootouts in America's Army", "expected_label": "shooter"},
    {"text": "Surviving and shooting your way through Hell in DOOM", "expected_label": "shooter"},
    {"text": "Shooting in historical settings of Verdun", "expected_label": "shooter"},
    {"text": "Taking down cyborgs in Deus Ex: Mankind Divided", "expected_label": "shooter"},
    {"text": "Fighting off zombie hordes in Killing Floor", "expected_label": "shooter"},
    {"text": "Exploring moon bases while shooting enemies in Destiny 2", "expected_label": "shooter"},
    {"text": "Joining sci-fi gunfights in Mass Effect", "expected_label": "shooter"},
    {"text": "Taking down space aliens in the battles of XCOM 2", "expected_label": "shooter"},
    {"text": "Clearing mutant-infested tunnels in Metro Redux", "expected_label": "shooter"},
    {"text": "Engaging in battles with heavy artillery in Titanfall", "expected_label": "shooter"},
    {"text": "Defending colonies from robots in Warhammer 40,000", "expected_label": "shooter"},
    {"text": "Firing advanced weapons in futuristic conflicts in Spec Ops: The Line", "expected_label": "shooter"},
    {"text": "Blasting through post-apocalyptic cities in Rage 2", "expected_label": "shooter"},
    {"text": "Taking part in multiplayer firefights in Valorant", "expected_label": "shooter"},
    {"text": "Surviving chaos in Fortnite's battle royale mode", "expected_label": "shooter"},
    {"text": "Fighting aliens in dark dungeons in Prey", "expected_label": "shooter"},
    {"text": "Engaging in epic shootouts in Gears of War", "expected_label": "shooter"},
    {"text": "Clearing abandoned buildings in Blacklight: Retribution", "expected_label": "shooter"},
    {"text": "Exploring post-nuclear cities in S.T.A.L.K.E.R.: Shadow of Chernobyl", "expected_label": "shooter"},
    {"text": "Running and gunning through levels in DOOM II", "expected_label": "shooter"},
    {"text": "Defending humanity against the Covenant in Halo 2", "expected_label": "shooter"},
    {"text": "Hunting for opponents in Rainbow Six: Vegas", "expected_label": "shooter"},
    {"text": "Firing weapons to clear a city in Medal of Honor: Warfighter", "expected_label": "shooter"},
    {"text": "Blasting through enemies in Unreal Tournament 2004", "expected_label": "shooter"},
    {"text": "Fighting for your life in The Darkness", "expected_label": "shooter"},
    {"text": "Sniping targets across wide open areas in Sniper Ghost Warrior", "expected_label": "shooter"},
    {"text": "Taking part in futuristic warfare in Call of Duty: Advanced Warfare", "expected_label": "shooter"},
    {"text": "Clearing out alien threats in Halo 4", "expected_label": "shooter"},
    {"text": "Shooting hostile robots in Binary Domain", "expected_label": "shooter"},
    {"text": "Engaging in fast-paced battles in Quake Live", "expected_label": "shooter"},
    {"text": "Defeating zombies in World War Z", "expected_label": "shooter"},
    {"text": "Shooting through haunted mansions in F.E.A.R. 3", "expected_label": "shooter"},
    {"text": "Fighting mutants in RAGE", "expected_label": "shooter"},
    {"text": "Clearing bunkers in Medal of Honor: Allied Assault", "expected_label": "shooter"},
    {"text": "Leading special ops missions in Tom Clancy's Rainbow Six 3", "expected_label": "shooter"},
    {"text": "Hunting down alien enemies in Halo: Reach", "expected_label": "shooter"},
    {"text": "Joining the battlefields of modern warfare in Battlefield: Bad Company 2", "expected_label": "shooter"},
    {"text": "Participating in tactical assaults in Insurgency", "expected_label": "shooter"},
    {"text": "Fighting against enemy factions in PlanetSide 2", "expected_label": "shooter"},
    {"text": "Engaging in arcade-style shooting in Serious Sam 2", "expected_label": "shooter"},
    {"text": "Navigating urban conflicts in Battlefield Hardline", "expected_label": "shooter"},
    {"text": "Fighting in naval battles in Battlefield 1943", "expected_label": "shooter"},
    {"text": "Surviving a post-apocalyptic Moscow in Metro 2033", "expected_label": "shooter"},
    {"text": "Fighting in gritty urban scenarios in Kane & Lynch 2: Dog Days", "expected_label": "shooter"},
    {"text": "Exploring vast levels and fighting hordes in Painkiller", "expected_label": "shooter"},
    {"text": "Fighting enemies in post-apocalyptic environments in Resistance: Retribution", "expected_label": "shooter"},
    {"text": "Taking part in realistic team-based combat in Squad", "expected_label": "shooter"},
    {"text": "Fighting in an abandoned city in Homefront: The Revolution", "expected_label": "shooter"},
    {"text": "Engaging in shootouts with rival gangs in Stranglehold", "expected_label": "shooter"},
    {"text": "Defending Earth against alien invaders in Earthfall", "expected_label": "shooter"},
    {"text": "Fighting against terrorists in global operations in Counter-Strike: Global Offensive", "expected_label": "shooter"},
    {"text": "Taking control of a lone soldier in Medal of Honor: Pacific Assault", "expected_label": "shooter"},
    {"text": "Fighting battles with modern military weapons in Call of Duty: Ghosts", "expected_label": "shooter"},
    {"text": "Using futuristic weaponry in Deus Ex: Human Revolution", "expected_label": "shooter"},
    {"text": "Engaging in open-world firefights in Just Cause 3", "expected_label": "shooter"},
    {"text": "Taking on crime lords in Max Payne", "expected_label": "shooter"},
    {"text": "Surviving in the zombie apocalypse in DayZ", "expected_label": "shooter"},
    {"text": "Exploring and fighting in the wastelands of Borderlands", "expected_label": "shooter"},
    {"text": "Leading a squad into battle in Gears of War", "expected_label": "shooter"},
    {"text": "Surviving a haunted mansion and shooting enemies in Resident Evil", "expected_label": "shooter"},
    {"text": "Clearing enemy bases in Brothers in Arms: Hell's Highway", "expected_label": "shooter"},
    {"text": "Exploring alien ruins in Halo 5: Guardians", "expected_label": "shooter"},
    {"text": "Defending against mutants in Half-Life 2", "expected_label": "shooter"},
    {"text": "Shooting enemies across sci-fi landscapes in Star Wars: Republic Commando", "expected_label": "shooter"},
    {"text": "Fighting off hordes of creatures in Killing Floor", "expected_label": "shooter"},
    {"text": "Sniping enemies from afar in Sniper Elite V2", "expected_label": "shooter"},
    {"text": "Fighting in a dystopian future in Killzone 3", "expected_label": "shooter"},
    {"text": "Clearing a zombie-infested school in Left 4 Dead 2", "expected_label": "shooter"},
    {"text": "Exploring an abandoned research facility in Doom 3", "expected_label": "shooter"},
    {"text": "Fighting mercenaries in Crysis Warhead", "expected_label": "shooter"},
    {"text": "Engaging in police chases and shootouts in Driver: San Francisco", "expected_label": "shooter"},
    {"text": "Fighting in World War II missions in Call of Duty: World at War", "expected_label": "shooter"},
    {"text": "Leading a tactical assault in Tom Clancy's Ghost Recon: Future Soldier", "expected_label": "shooter"},
    {"text": "Clearing the streets in Call of Juarez: Gunslinger", "expected_label": "shooter"},
    {"text": "Fighting on war-torn battlefields in Battlefield 1942", "expected_label": "shooter"},
    {"text": "Surviving zombie waves in Dead Nation", "expected_label": "shooter"},
    {"text": "Fighting against enemy militia in Spec Ops: The Line", "expected_label": "shooter"},
    {"text": "Shooting enemies in dark sci-fi settings in Dead Space", "expected_label": "shooter"},
    {"text": "Defending against rival soldiers in Call of Duty: Modern Warfare", "expected_label": "shooter"},
    {"text": "Leading a resistance movement in Rage", "expected_label": "shooter"},
    {"text": "Blasting through hordes of monsters in Serious Sam: The First Encounter", "expected_label": "shooter"},
    {"text": "Clearing out rebel forces in Mercenaries: Playground of Destruction", "expected_label": "shooter"},
    {"text": "Engaging in a firefight in the mountains in Far Cry", "expected_label": "shooter"},
    {"text": "Clearing enemies from an oil rig in Call of Duty: Modern Warfare 3", "expected_label": "shooter"},
    {"text": "Defending a village from attack in Medal of Honor: Airborne", "expected_label": "shooter"},
    {"text": "Blasting enemy spaceships in Warframe", "expected_label": "shooter"},
    {"text": "Taking down enemy commanders in Battlefield 4", "expected_label": "shooter"},
    {"text": "Defending yourself in a dangerous jungle in Far Cry 3", "expected_label": "shooter"},
    {"text": "Clearing space stations of hostile aliens in System Shock 2", "expected_label": "shooter"},
    {"text": "Leading a team of futuristic soldiers in Section 8: Prejudice", "expected_label": "shooter"},
    {"text": "Fighting through stormy environments in S.T.A.L.K.E.R.: Call of Pripyat", "expected_label": "shooter"},
    {"text": "Defending your spaceship from invaders in Everspace", "expected_label": "shooter"},
    {"text": "Fighting battles against rebels in Half-Life: Opposing Force", "expected_label": "shooter"},
    {"text": "Clearing enemy bunkers in Delta Force: Black Hawk Down", "expected_label": "shooter"},
    {"text": "Engaging in large-scale military battles in Call of Duty: Cold War", "expected_label": "shooter"},
    {"text": "Taking out mutant enemies in S.T.A.L.K.E.R.: Clear Sky", "expected_label": "shooter"},
    {"text": "Leading troops into war zones in Arma 2", "expected_label": "shooter"},
    {"text": "Defending against AI drones in Generation Zero", "expected_label": "shooter"},
    {"text": "Engaging in futuristic combat missions in Starlink: Battle for Atlas", "expected_label": "shooter"},
    {"text": "Taking control in a sci-fi universe in Mass Effect 3", "expected_label": "shooter"},
    {"text": "Fighting through frozen outposts in Lost Planet 3", "expected_label": "shooter"},
    {"text": "Taking down cultists in Far Cry 5", "expected_label": "shooter"},
    {"text": "Shooting through desert outposts in Medal of Honor", "expected_label": "shooter"},
    {"text": "Engaging in tactical missions in SWAT 4", "expected_label": "shooter"},
    {"text": "Clearing enemy trenches in Verdun", "expected_label": "shooter"},
    {"text": "Defending your base from alien attacks in Aliens vs. Predator", "expected_label": "shooter"},
    {"text": "Fighting through urban environments in Battlefield: Bad Company", "expected_label": "shooter"},
    {"text": "Surviving and shooting enemies in The Division 2", "expected_label": "shooter"},
    {"text": "Joining in multiplayer battles in Warface", "expected_label": "shooter"},
    {"text": "Fighting against extraterrestrial forces in XCOM: Enemy Unknown", "expected_label": "shooter"},
    {"text": "Leading an elite team in Star Wars: Battlefront II", "expected_label": "shooter"},
    {"text": "Fighting through the jungles in Far Cry: Instincts", "expected_label": "shooter"},
    {"text": "Defending humanity from mutants in Resistance 2", "expected_label": "shooter"},
    {"text": "Exploring derelict alien spaceships in Alien Isolation", "expected_label": "shooter"},
    {"text": "Surviving in a post-apocalyptic Moscow in Metro Last Light", "expected_label": "shooter"},
    {"text": "Leading an assault in Battlefield Vietnam", "expected_label": "shooter"},
    {"text": "Defending against a rogue AI uprising in System Shock", "expected_label": "shooter"},
    {"text": "Fighting off the Combine in Half-Life: Alyx", "expected_label": "shooter"},
    {"text": "Engaging in combat missions in Call of Duty: Black Ops II", "expected_label": "shooter"},
    {"text": "Battling aliens in Duke Nukem Forever", "expected_label": "shooter"},
    {"text": "Shooting down warplanes in Ace Combat 7", "expected_label": "shooter"},
    {"text": "Clearing a corrupted city in Prototype 2", "expected_label": "shooter"},
    {"text": "Taking on cyborg enemies in Warhammer 40,000: Space Marine", "expected_label": "shooter"},
    {"text": "Fighting criminals in futuristic neon settings in Cyberpunk 2077", "expected_label": "shooter"},
    {"text": "Hunting bounties in Mad Max", "expected_label": "shooter"},
    {"text": "Engaging in tactical espionage operations in Splinter Cell: Blacklist", "expected_label": "shooter"},
    {"text": "Clearing dungeons in Deep Rock Galactic", "expected_label": "shooter"},
    {"text": "Fighting in modern-day warfare in Warface: Breakout", "expected_label": "shooter"},
    {"text": "Surviving against other teams in Apex Legends' Battle Royale", "expected_label": "shooter"},
    {"text": "Clearing trenches in Wolfenstein: The New Order", "expected_label": "shooter"},
    {"text": "Fighting monsters in Hellgate: London", "expected_label": "shooter"},
    {"text": "Defending the city from cyborgs in Crackdown 3", "expected_label": "shooter"},
    {"text": "Fighting in medieval fantasy battles in Vermintide 2", "expected_label": "shooter"},
    {"text": "Defending moon outposts in Destiny", "expected_label": "shooter"},
    {"text": "Fighting gang wars in Mafia III", "expected_label": "shooter"},
    {"text": "Engaging in naval firefights in World of Warships: Legends", "expected_label": "shooter"},
    {"text": "Exploring nightmarish landscapes in Clive Barker's Jericho", "expected_label": "shooter"},
    {"text": "Shooting through a dystopian future in Hard Reset Redux", "expected_label": "shooter"},
    {"text": "Fighting through space stations in Aliens: Colonial Marines", "expected_label": "shooter"},
    {"text": "Clearing out werewolves in The Order: 1886", "expected_label": "shooter"},
    {"text": "Participating in intense cyber battles in Syndicate (2012)", "expected_label": "shooter"},
    {"text": "Fighting in the ruins of Moscow in Metro Exodus", "expected_label": "shooter"},
    {"text": "Engaging in realistic military operations in ARMA: Armed Assault", "expected_label": "shooter"},
    {"text": "Clearing haunted spaceships in Dead Space 3", "expected_label": "shooter"},
    {"text": "Fighting enemies in the dreamlike world of Control", "expected_label": "shooter"},
    {"text": "Engaging in aerial combat in Star Wars: Squadrons", "expected_label": "shooter"},
    {"text": "Defending against alien invasions in Bodycount", "expected_label": "shooter"},
    {"text": "Taking part in a futuristic gladiator arena in Toxikk", "expected_label": "shooter"},
    {"text": "Fighting zombies in Arizona Sunshine", "expected_label": "shooter"},
    {"text": "Defending the Ark from hostile factions in Brink", "expected_label": "shooter"},
    {"text": "Hunting enemies in Ghost Recon Advanced Warfighter", "expected_label": "shooter"},
    {"text": "Battling giant ants in Earth Defense Force 4.1", "expected_label": "shooter"},
    {"text": "Clearing out rebel camps in Just Cause 2", "expected_label": "shooter"},
    {"text": "Engaging in quick matches in Dirty Bomb", "expected_label": "shooter"},
    {"text": "Fighting rogue agents in Tom Clancy's The Division", "expected_label": "shooter"},
    {"text": "Participating in sci-fi skirmishes in Mass Effect: Andromeda", "expected_label": "shooter"},
    {"text": "Engaging in competitive matches in Black Squad", "expected_label": "shooter"},
    {"text": "Fighting enemy cyborgs in Vanquish", "expected_label": "shooter"},
    {"text": "Taking down targets in a snowy city in Tom Clancy's Rainbow Six Siege", "expected_label": "shooter"},
    {"text": "Clearing hostile facilities in Prey (2006)", "expected_label": "shooter"},
    {"text": "Engaging in multiplayer space battles in Fractured Space", "expected_label": "shooter"},
    {"text": "Taking part in massive online battles in MAG", "expected_label": "shooter"},
    {"text": "Fighting for survival in Fallout: New Vegas", "expected_label": "shooter"},
    {"text": "Blasting through hordes of enemies in Serious Sam 3", "expected_label": "shooter"},
    {"text": "Clearing the streets of monsters in Hellbound", "expected_label": "shooter"},
    {"text": "Fighting against elite soldiers in Counter-Strike: Condition Zero", "expected_label": "shooter"},
    {"text": "Engaging in futuristic warfare in Titanfall", "expected_label": "shooter"},
    {"text": "Taking on tactical missions in Delta Force Xtreme", "expected_label": "shooter"},
    {"text": "Defending against waves of AI in Robo Recall", "expected_label": "shooter"},
    {"text": "Shooting through military campaigns in Medal of Honor: Rising Sun", "expected_label": "shooter"},
    {"text": "Leading a small team in Call of Duty: Strike Team", "expected_label": "shooter"},
    {"text": "Fighting through an alien planet in Lost Planet: Extreme Condition", "expected_label": "shooter"},
    {"text": "Sniping enemies in the cold, harsh environment in Sniper Ghost Warrior 2", "expected_label": "shooter"},
    {"text": "Engaging in large-scale naval battles in World of Warships", "expected_label": "shooter"},
    {"text": "Defending outposts in Battlefield Play4Free", "expected_label": "shooter"},
    {"text": "Exploring dark castles and fighting monsters in Blood", "expected_label": "shooter"},
    {"text": "Fighting through the snow-covered levels in Turok (2008)", "expected_label": "shooter"},
    {"text": "Clearing abandoned mines in Painkiller: Overdose", "expected_label": "shooter"},
    {"text": "Defending against undead armies in Zombie Army 4", "expected_label": "shooter"},
    {"text": "Hunting for treasure in Borderlands 2", "expected_label": "shooter"},
    {"text": "Fighting as a mech pilot in Hawken", "expected_label": "shooter"},
    {"text": "Clearing alien-infested ships in Space Hulk: Deathwing", "expected_label": "shooter"},
    {"text": "Fighting in a dystopian world in Terminator: Resistance", "expected_label": "shooter"},
    {"text": "Engaging in quick-play deathmatches in Quake II", "expected_label": "shooter"},
    {"text": "Fighting through time-travel missions in TimeSplitters: Future Perfect", "expected_label": "shooter"},
    {"text": "Shooting through a spooky amusement park in CarnEvil", "expected_label": "shooter"},
    {"text": "Fighting alien forces in Halo: Combat Evolved", "expected_label": "shooter"},
    {"text": "Participating in high-octane firefights in Bulletstorm", "expected_label": "shooter"},
    {"text": "Engaging in dogfights in Call of Duty: Infinite Warfare", "expected_label": "shooter"},
    {"text": "Fighting off the Flood in Halo 3", "expected_label": "shooter"},
    {"text": "Fighting to survive against hordes of enemies in NecroVisioN", "expected_label": "shooter"},
    {"text": "Fighting in abandoned subway tunnels in S.T.A.L.K.E.R.: Lost Alpha", "expected_label": "shooter"},
    {"text": "Clearing zombie-infested high-rises in Daymare: 1998", "expected_label": "shooter"},
    {"text": "Shooting through a space station overrun with creatures in BioShock Infinite","expected_label": "shooter"},
    {"text": "Engaging in mech-on-mech combat in MechWarrior Online", "expected_label": "shooter"},
    {"text": "Fighting cyborgs in Binary Domain", "expected_label": "shooter"},
    {"text": "Engaging in close-quarters firefights in Rainbow Six: Extraction", "expected_label": "shooter"},
    {"text": "Shooting enemies through surreal landscapes in NecroVision: Lost Company", "expected_label": "shooter"},
    {"text": "Defending bases in the arctic in Battlefield 2142", "expected_label": "shooter"},
    {"text": "Engaging in chaotic firefights in Red Faction: Armageddon", "expected_label": "shooter"},
    {"text": "Exploring haunted forests with guns in Project Warlock", "expected_label": "shooter"},
    {"text": "Fighting mutants in a decaying city in ZombiU", "expected_label": "shooter"},
    {"text": "Surviving in a broken future in Bulletstorm: Duke of Switch Edition", "expected_label": "shooter"},
    {"text": "Defending settlements from mutants in Far Cry: New Dawn", "expected_label": "shooter"},
    {"text": "Hunting massive enemies in Daemon X Machina", "expected_label": "shooter"},
    {"text": "Clearing jungles of insurgents in Far Cry Instincts Predator", "expected_label": "shooter"},
    {"text": "Engaging in horror-themed firefights in Aftermath VR", "expected_label": "shooter"},
    {"text": "Taking part in simulated war games in Delta Force 2", "expected_label": "shooter"},
    {"text": "Fighting on distant planets in Warframe: Empyrean", "expected_label": "shooter"},
    {"text": "Leading resistance fighters in GoldenEye: Rogue Agent", "expected_label": "shooter"},
    {"text": "Fighting in a post-apocalyptic world in Rage 2: TerrorMania", "expected_label": "shooter"},
    {"text": "Clearing out alien hives in Earth Defense Force: Iron Rain", "expected_label": "shooter"},
    {"text": "Fighting through a post-apocalyptic city in The Surge 2", "expected_label": "shooter"},
    {"text": "Fighting in a cyberpunk world in Ruiner", "expected_label": "shooter"},
    {"text": "Engaging in tactical firefights in Tom Clancy's Rainbow Six: Lockdown", "expected_label": "shooter"},
    {"text": "Blasting through alien hordes in Alien Breed: Impact", "expected_label": "shooter"},
    {"text": "Engaging in tactical SWAT missions in Door Kickers", "expected_label": "shooter"},
    {"text": "Shooting enemies from helicopters in Battlefield 3", "expected_label": "shooter"},
    {"text": "Sniping from a distance in Sniper Ghost Warrior Contracts 2", "expected_label": "shooter"},
    {"text": "Defending bases from alien attacks in Halo Wars", "expected_label": "shooter"},
    {"text": "Fighting in a futuristic landscape in Binary Trigger", "expected_label": "shooter"},
    {"text": "Taking down drug cartels in Ghost Recon Wildlands", "expected_label": "shooter"},
    {"text": "Engaging in high-tech warfare in Advanced Warfare", "expected_label": "shooter"},
    {"text": "Exploring an open world in Far Cry 4 with guns blazing", "expected_label": "shooter"},
    {"text": "Hunting mutants in The Evil Within", "expected_label": "shooter"},
    {"text": "Fighting robotic invaders in Enslaved: Odyssey to the West", "expected_label": "shooter"},
    {"text": "Battling enemy ships in deep space in Star Trek: Voyager - Elite Force", "expected_label": "shooter"},
    {"text": "Defending Earth from invasion in Attack on Titan", "expected_label": "shooter"},
    {"text": "Engaging in covert operations in Medal of Honor: Allied Assault", "expected_label": "shooter"},
    {"text": "Fighting for survival against alien forces in Bulletstorm", "expected_label": "shooter"},
    {"text": "Exploring dark corridors with weapons in Fear Effect", "expected_label": "shooter"},
    {"text": "Engaging in jetpack-assisted combat in Dark Void", "expected_label": "shooter"},
    {"text": "Fighting in a city overrun by zombies in Resident Evil: Operation Raccoon City", "expected_label": "shooter"},
    {"text": "Battling armies in the Stone Age in Far Cry Primal", "expected_label": "shooter"},
    {"text": "Hunting dinosaurs in Orion: Prelude", "expected_label": "shooter"},
    {"text": "Taking down space pirates in Metroid Prime", "expected_label": "shooter"},
    {"text": "Fighting demons in Hell in Painkiller: Resurrection", "expected_label": "shooter"},
    {"text": "Sniping targets across snowy mountains in Sniper Elite 3", "expected_label": "shooter"},
    {"text": "Fighting against mercenaries in Spec Ops: Stealth Patrol", "expected_label": "shooter"},
    {"text": "Exploring a cyberpunk future in E.Y.E: Divine Cybermancy", "expected_label": "shooter"},
    {"text": "Taking control of soldiers in a squad-based shooter in Breach & Clear", "expected_label": "shooter"},
    {"text": "Shooting through waves of undead in Dying Light", "expected_label": "shooter"},
    {"text": "Fighting alien creatures on the surface of Mars in Red Faction: Guerilla", "expected_label": "shooter"},
    {"text": "Taking on stealth missions in Operation Flashpoint: Dragon Rising", "expected_label": "shooter"},
    {"text": "Engaging in large-scale online matches in Heroes & Generals", "expected_label": "shooter"},
    {"text": "Defending against robot uprisings in Ion Fury", "expected_label": "shooter"},
    {"text": "Shooting enemies with laser weapons in Hard Reset", "expected_label": "shooter"},
    {"text": "Exploring cursed caverns with firearms in Vaporum", "expected_label": "shooter"},
    {"text": "Clearing mutants from underground bunkers in S.T.A.L.K.E.R.: Clear Sky", "expected_label": "shooter"},
    {"text": "Blasting enemies with powerful plasma rifles in NecroVision", "expected_label": "shooter"},
    {"text": "Fighting terrorists in Delta Force: Black Hawk Down", "expected_label": "shooter"},
    {"text": "Clearing out a research facility in Area 51", "expected_label": "shooter"},
    {"text": "Shooting in neon-lit battle arenas in Sky Noon", "expected_label": "shooter"},
    {"text": "Fighting through a post-apocalyptic wasteland in Rage", "expected_label": "shooter"},
    {"text": "Engaging in high-stakes gang warfare in Kane & Lynch 2: Dog Days", "expected_label": "shooter"},
    {"text": "Fighting monstrous creatures in The Darkness", "expected_label": "shooter"},
    {"text": "Taking down enemy leaders in No One Lives Forever 2", "expected_label": "shooter"},
    {"text": "Engaging in multiplayer skirmishes in Gotham City Impostors", "expected_label": "shooter"},
    {"text": "Participating in mercenary missions in Contract J.A.C.K.", "expected_label": "shooter"},
    {"text": "Exploring an interdimensional city in Doom 64", "expected_label": "shooter"},
    {"text": "Defending the Federation against Klingon threats in Star Trek: Elite Force II", "expected_label": "shooter"},
    {"text": "Hunting vampires in Darkwatch", "expected_label": "shooter"},
    {"text": "Battling mutated beings in Singularity", "expected_label": "shooter"},
    {"text": "Clearing the streets of gang members in 25 to Life", "expected_label": "shooter"},
    {"text": "Fighting extraterrestrial creatures in Lost Planet 3", "expected_label": "shooter"},
    {"text": "Engaging in brutal arena combat in Unreal Championship 2", "expected_label": "shooter"},
    {"text": "Hunting alien leaders in Area 51 (2005)", "expected_label": "shooter"},
    {"text": "Shooting zombies with experimental weapons in Contagion", "expected_label": "shooter"},
    {"text": "Engaging in post-apocalyptic duels in Mad Max (2015)", "expected_label": "shooter"},
    {"text": "Battling opponents in a futuristic arena in TOXIKK", "expected_label": "shooter"},
    {"text": "Taking on bounty hunting missions in Call of Juarez: Bound in Blood", "expected_label": "shooter"},
    {"text": "Clearing hostile desert camps in Spec Ops: Ranger Team Bravo", "expected_label": "shooter"},
    {"text": "Fighting space aliens in Battleborn", "expected_label": "shooter"},
    {"text": "Defending the nation against cyber threats in Blacksite: Area 51", "expected_label": "shooter"},
    {"text": "Taking down dangerous fugitives in Cold Winter", "expected_label": "shooter"},
    {"text": "Clearing underground bunkers in Escape from Tarkov", "expected_label": "shooter"},
    {"text": "Engaging in modern military conflicts in Insurgency: Modern Infantry Combat", "expected_label": "shooter"},
    {"text": "Shooting through ruined factories in Metro 2033", "expected_label": "shooter"},
    {"text": "Surviving against mutant hordes in Killing Floor", "expected_label": "shooter"},
    {"text": "Defending villages in Earthfall", "expected_label": "shooter"},
    {"text": "Engaging in stealth-based firefights in Velvet Assassin", "expected_label": "shooter"},
    {"text": "Participating in large-scale battles in Frontlines: Fuel of War", "expected_label": "shooter"},
    {"text": "Blasting away robots in Robo Recall: Unplugged", "expected_label": "shooter"},
    {"text": "Shooting through futuristic cities in Project Eden", "expected_label": "shooter"},
    {"text": "Fighting for territory in Battlefield Hardline", "expected_label": "shooter"},
    {"text": "Clearing Nazi-occupied Paris in Wolfenstein: Youngblood", "expected_label": "shooter"},
    {"text": "Engaging in explosive firefights in Medal of Honor: Airborne", "expected_label": "shooter"},
    {"text": "Taking down terrorists in urban environments in Counter Terrorist Special Forces", "expected_label": "shooter"},
    {"text": "Fighting supernatural enemies in Clive Barker's Jericho", "expected_label": "shooter"},
    {"text": "Taking control of advanced weaponry in BattleTech", "expected_label": "shooter"},
    {"text": "Clearing cities of zombies in Dead Trigger", "expected_label": "shooter"},
    {"text": "Shooting down enemy aircraft in Iron Man VR", "expected_label": "shooter"},
    {"text": "Fighting against crime lords in Chicago in Watch Dogs 2", "expected_label": "shooter"},
    {"text": "Taking part in black ops missions in Black Ops Declassified", "expected_label": "shooter"},
    {"text": "Blasting through alien biomes in Bulletstorm: Full Clip", "expected_label": "shooter"},
    {"text": "Engaging in military simulation operations in Ghost Recon Phantoms", "expected_label": "shooter"},
    {"text": "Defending your ship from space pirates in Starlink: Battle for Atlas", "expected_label": "shooter"},
    {"text": "Fighting for glory in Gladiator: Sword of Vengeance", "expected_label": "shooter"},
    {"text": "Engaging in gang shootouts in The Getaway", "expected_label": "shooter"},
    {"text": "Shooting through haunted levels in Hellraid", "expected_label": "shooter"},
    {"text": "Battling mutants in Afterfall: Insanity", "expected_label": "shooter"},
    {"text": "Hunting outlaws in the wastelands in Borderlands: Mad Moxxi's Underdome Riot", "expected_label": "shooter"},
    {"text": "Fighting alien abominations in Warhammer 40,000: Space Hulk", "expected_label": "shooter"},
    {"text": "Engaging in naval bombardments in Naval Assault: The Killing Tide", "expected_label": "shooter"},
    {"text": "Participating in survival horror-style gunfights in Resident Evil: Revelations", "expected_label": "shooter"},
    {"text": "Exploring dark tunnels with guns in Singularity", "expected_label": "shooter"},
    {"text": "Shooting through alien-infested planets in Outriders", "expected_label": "shooter"},
    {"text": "Clearing desert war zones in Call of Duty: Warzone", "expected_label": "shooter"},
    {"text": "Fighting through futuristic bases in Duke Nukem: Manhattan Project", "expected_label": "shooter"},
    {"text": "Blasting through medieval castles in Iron Storm", "expected_label": "shooter"},
    {"text": "Clearing levels of mutated beasts in Dead Island", "expected_label": "shooter"},
    {"text": "Engaging in covert military operations in BlackSite", "expected_label": "shooter"},
    {"text": "Defending against alien invasions in Earth Defense Force 4.1: The Shadow of New Despair", "expected_label": "shooter"},
    {"text": "Shooting through a post-apocalyptic world in Bulletstorm: Full Clip Edition", "expected_label": "shooter"},
    {"text": "Fighting in a cyberpunk future in Ruiner", "expected_label": "shooter"},
    {"text": "Defending against alien invasions in Earth Defense Force 5", "expected_label": "shooter"},
    {"text": "Surviving in a world overrun by zombies in Dying Light", "expected_label": "shooter"},
    {"text": "Joining a team of elite soldiers in Tom Clancy's Ghost Recon: Breakpoint", "expected_label": "shooter"},
    {"text": "Taking out rival gangs in The Getaway: Black Monday", "expected_label": "shooter"},
    {"text": "Shooting through futuristic streets in LawBreakers", "expected_label": "shooter"},
    {"text": "Defending against hordes of monsters in Warhammer: Vermintide 2", "expected_label": "shooter"},
    {"text": "Engaging in urban warfare in Conflict: Global Terror", "expected_label": "shooter"},
    {"text": "Fighting alien creatures in Resistance 3", "expected_label": "shooter"},
    {"text": "Engaging in intense firefights in Modern Combat Versus", "expected_label": "shooter"},
    {"text": "Shooting through zombie-infested streets in Killing Floor: Incursion", "expected_label": "shooter"},
    {"text": "Fighting robot armies in Hard Reset Redux", "expected_label": "shooter"},
    {"text": "Taking control of heavy artillery in Command & Conquer: Renegade", "expected_label": "shooter"},
    {"text": "Hunting dangerous creatures in Turok 2: Seeds of Evil", "expected_label": "shooter"},
    {"text": "Engaging in team-based shootouts in Dirty Bomb", "expected_label": "shooter"},
    {"text": "Clearing alien bases in Red Faction II", "expected_label": "shooter"},
    {"text": "Fighting supernatural beings in Nightmare Reaper", "expected_label": "shooter"},
    {"text": "Blasting enemies in the streets of Los Angeles in Terminator: Resistance", "expected_label": "shooter"},
    {"text": "Engaging in tactical missions in Ghost Recon: Future Soldier", "expected_label": "shooter"},
    {"text": "Fighting space battles in Section 8: Prejudice", "expected_label": "shooter"},
    {"text": "Defending settlements in Fallout: New Vegas", "expected_label": "shooter"},
    {"text": "Clearing out enemies in futuristic levels in Vanquish", "expected_label": "shooter"},
    {"text": "Engaging in sniper battles in Enemy Front", "expected_label": "shooter"},
    {"text": "Fighting waves of enemies in Space Hulk: Deathwing", "expected_label": "shooter"},
    {"text": "Clearing war-torn cities in Enemy Territory", "expected_label": "shooter"},
    {"text": "Shooting through enemy bunkers in Medal of Honor: Rising Sun", "expected_label": "shooter"},
    {"text": "Battling monstrous bosses in Lost Planet: Extreme Condition", "expected_label": "shooter"},
    {"text": "Fighting demonic forces in Hellbound", "expected_label": "shooter"},
    {"text": "Defending against alien attacks in Destroy All Humans!", "expected_label": "shooter"},
    {"text": "Taking down warlords in Far Cry: Blood Dragon", "expected_label": "shooter"},
    {"text": "Hunting for treasure in Strange Brigade", "expected_label": "shooter"},
    {"text": "Engaging in intense firefights in Insurgency: Insurrection", "expected_label": "shooter"},
    {"text": "Clearing the streets of post-apocalyptic cities in The Walking Dead: Saints & Sinners", "expected_label": "shooter"},
    {"text": "Fighting through dystopian landscapes in The Surge", "expected_label": "shooter"},
    {"text": "Blasting mutant creatures in The Suffering", "expected_label": "shooter"},
    {"text": "Engaging in tactical shootouts in Operation Flashpoint: Red River", "expected_label": "shooter"},
    {"text": "Defending cities from mutant attacks in Sunset Overdrive", "expected_label": "shooter"},
    {"text": "Shooting through enemy-occupied factories in Medal of Honor: Warfighter", "expected_label": "shooter"},
    {"text": "Hunting down enemies in dystopian environments in Brink", "expected_label": "shooter"},
    {"text": "Battling through space stations in System Shock 2", "expected_label": "shooter"},
    {"text": "Defending outposts in the wilderness in Sniper: Ghost Warrior", "expected_label": "shooter"},
    {"text": "Engaging in jetpack-assisted firefights in Section 8", "expected_label": "shooter"},
    {"text": "Fighting in team-based objectives in Battalion 1944", "expected_label": "shooter"},
    {"text": "Blasting through hordes of zombies in RAGE", "expected_label": "shooter"},
    {"text": "Clearing haunted mansions with advanced weapons in Phantom Doctrine", "expected_label": "shooter"},
    {"text": "Engaging in tactical shootouts in Arma 2", "expected_label": "shooter"},
    {"text": "Participating in gang warfare in The Warriors", "expected_label": "shooter"},
    {"text": "Taking on covert missions in Medal of Honor: Heroes", "expected_label": "shooter"},
    {"text": "Clearing levels of mutants in NecroVisioN: Lost Company", "expected_label": "shooter"},
    {"text": "Exploring dystopian environments in Judge Dredd: Dredd vs Death", "expected_label": "shooter"},
    {"text": "Shooting through waves of futuristic enemies in Deep Rock Galactic", "expected_label": "shooter"},
    {"text": "Fighting through intense campaigns in Rogue Warrior", "expected_label": "shooter"},
    {"text": "Engaging in stealthy sniping missions in Silent Scope", "expected_label": "shooter"},
    {"text": "Clearing out enemies in Total Overdose", "expected_label": "shooter"},
    {"text": "Fighting off supernatural creatures in TimeSplitters: Future Perfect", "expected_label": "shooter"},
    {"text": "Blasting away robots in Wild Metal Country", "expected_label": "shooter"},
    {"text": "Participating in tactical operations in America's Army: Proving Grounds", "expected_label": "shooter"},
    {"text": "Defending against mutants in Homefront: The Revolution", "expected_label": "shooter"},
    {"text": "Engaging in gunfights in Wolfenstein: The New Order", "expected_label": "shooter"},
    {"text": "Clearing alien-infested ships in Space Hulk", "expected_label": "shooter"},
    {"text": "Fighting against hordes of mutants in Killing Floor 3", "expected_label": "shooter"},
    {"text": "Sniping from high vantage points in Sniper Elite V2", "expected_label": "shooter"},
    {"text": "Defending against cybernetic threats in Neon Chrome", "expected_label": "shooter"},
    {"text": "Engaging in urban shootouts in The Punisher", "expected_label": "shooter"},
    {"text": "Taking down terrorists in urban landscapes in Counter-Strike: Source", "expected_label": "shooter"},
    {"text": "Shooting enemies in chaotic firefights in Heavy Fire: Afghanistan", "expected_label": "shooter"},
    {"text": "Fighting zombie hordes in State of Decay 2", "expected_label": "shooter"},
    {"text": "Engaging in futuristic gunfights in LawBreakers", "expected_label": "shooter"},
    {"text": "Clearing caves filled with monstrous spiders in Arachnid Assault", "expected_label": "shooter"},
    {"text": "Battling through futuristic urban warfare in Shattered Horizon", "expected_label": "shooter"},
    {"text": "Fighting supernatural forces in Painkiller: Black Edition", "expected_label": "shooter"},
    {"text": "Taking control of drones to shoot enemies in Drone Strike Force", "expected_label": "shooter"},
    {"text": "Engaging in post-apocalyptic firefights in Metro Redux", "expected_label": "shooter"},
    {"text": "Blasting through dangerous jungles in Far Cry: Instincts", "expected_label": "shooter"},
    {"text": "Fighting gangs in underground arenas in Uprising: Join or Die", "expected_label": "shooter"},
    {"text": "Defending against alien forces in Starship Troopers: Terran Command", "expected_label": "shooter"},
    {"text": "Clearing dystopian cities in Project Warlock", "expected_label": "shooter"},
    {"text": "Shooting through hordes of demons in Hellbound", "expected_label": "shooter"},
    {"text": "Engaging in time-traveling gunfights in Quantum League", "expected_label": "shooter"},
    {"text": "Shooting through enemy-held ports in Hidden & Dangerous 2", "expected_label": "shooter"},
    {"text": "Blasting away at zombies in Zombie Army Trilogy", "expected_label": "shooter"},
    {"text": "Fighting cybercriminals in Watch Dogs Legion", "expected_label": "shooter"},
    {"text": "Clearing alien-infested islands in Crysis Warhead", "expected_label": "shooter"},
    {"text": "Taking control of experimental weaponry in The Darkness II", "expected_label": "shooter"},
    {"text": "Engaging in intense urban combat in BlackSite: Area 51", "expected_label": "shooter"},
    {"text": "Clearing rooms of dangerous criminals in Hotline Miami 2: Wrong Number", "expected_label": "shooter"},
    {"text": "Defending against alien attacks in Duke Nukem Forever", "expected_label": "shooter"},
    {"text": "Fighting enemy factions in the depths of Metro: Last Light Redux", "expected_label": "shooter"},
    {"text": "Blasting mutants in Rage: The Scorchers", "expected_label": "shooter"},
    {"text": "Clearing infested bunkers in XCOM: Enemy Within", "expected_label": "shooter"},
    {"text": "Defending cities from undead invasions in Dead Nation", "expected_label": "shooter"},
    {"text": "Taking control of mechs in Titanfall", "expected_label": "shooter"},
    {"text": "Fighting mutant rats in NecroVisioN: Lost Company", "expected_label": "shooter"},
    {"text": "Engaging in combat to save survivors in Killing Floor 2: Hellmark Edition", "expected_label": "shooter"},
    {"text": "Shooting through space colonies in Halo Wars 2", "expected_label": "shooter"},
    {"text": "Engaging in bullet-hell style gunfights in Enter the Gungeon", "expected_label": "shooter"},
    {"text": "Fighting supernatural creatures in Vampire: The Masquerade - Bloodhunt", "expected_label": "shooter"},
    {"text": "Taking control of a giant mech in Hawken", "expected_label": "shooter"},
    {"text": "Fighting through enemy soldiers in Battleborn", "expected_label": "shooter"},
    {"text": "Shooting through ruined landscapes in Necromunda: Hired Gun", "expected_label": "shooter"},
    {"text": "Fighting cybernetic enemies in Hard Reset", "expected_label": "shooter"},
    {"text": "Blasting away hostile forces in Singularity", "expected_label": "shooter"},
    {"text": "Clearing out zombie-infested cities in Dying Light 2", "expected_label": "shooter"},
    {"text": "Engaging in intense duels in Drawn to Death", "expected_label": "shooter"},
    {"text": "Defending humanity against alien invasions in X-Morph: Defense", "expected_label": "shooter"},
    {"text": "Shooting through hordes of robots in Robot Wars", "expected_label": "shooter"},
    {"text": "Fighting for control of territory in Enemy Front", "expected_label": "shooter"},
    {"text": "Sniping enemies from distant vantage points in Sniper Elite 3", "expected_label": "shooter"},
    {"text": "Clearing rooms full of enemies in Wanted: Weapons of Fate", "expected_label": "shooter"},
    {"text": "Engaging in fast-paced battles in DOOM 3", "expected_label": "shooter"},
    {"text": "Defending against hordes of mutants in Rage 2", "expected_label": "shooter"},
    {"text": "Fighting cyber soldiers in Bodycount", "expected_label": "shooter"},
    {"text": "Taking on hordes of undead in Killing Floor", "expected_label": "shooter"},
    {"text": "Shooting aliens with experimental weapons in Prey (2006)", "expected_label": "shooter"},
    {"text": "Exploring a destroyed planet in Lost Planet 3", "expected_label": "shooter"},
    {"text": "Engaging in aerial combat with advanced weapons in Skyforge", "expected_label": "shooter"},
    {"text": "Shooting through ancient temples in Serious Sam: The First Encounter", "expected_label": "shooter"},
    {"text": "Clearing out enemy forces in Shellshock 2: Blood Trails", "expected_label": "shooter"},
    {"text": "Engaging in sci-fi combat with laser weapons in Dark Sector", "expected_label": "shooter"},
    {"text": "Clearing out crime syndicates in Kane & Lynch 2: Dog Days", "expected_label": "shooter"},
    {"text": "Shooting through a dystopian society in Binary Domain", "expected_label": "shooter"},
    {"text": "Taking on assassinations in No One Lives Forever", "expected_label": "shooter"},
    {"text": "Blasting enemies in chaotic environments in Bulletstorm", "expected_label": "shooter"},
    {"text": "Participating in military operations in War Rock", "expected_label": "shooter"},
    {"text": "Taking on covert missions in Rogue Ops", "expected_label": "shooter"},
    {"text": "Engaging in desert warfare in Medal of Honor: Allied Assault", "expected_label": "shooter"},
    {"text": "Shooting zombies in a carnival in Left 4 Dead", "expected_label": "shooter"},
    {"text": "Exploring abandoned laboratories in The Scourge Project", "expected_label": "shooter"},
    {"text": "Blasting through hordes of demons in Devil Daggers", "expected_label": "shooter"},
    {"text": "Shooting through bank heists in Payday 2", "expected_label": "shooter"},
    {"text": "Fighting supernatural monsters in NecroVisioN", "expected_label": "shooter"},
    {"text": "Taking down soldiers in Resistance: Retribution", "expected_label": "shooter"},
    {"text": "Engaging in air and land combat in Future Cop: LAPD", "expected_label": "shooter"},
    {"text": "Clearing levels filled with dangerous enemies in Rise of the Triad", "expected_label": "shooter"},
    {"text": "Fighting in historical settings in Wolfenstein: Youngblood", "expected_label": "shooter"},
    {"text": "Hunting down rogue agents in Crackdown 3", "expected_label": "shooter"},
    {"text": "Shooting your way through sewers in Vampyr", "expected_label": "shooter"},
    {"text": "Taking down criminals in Time Crisis 5", "expected_label": "shooter"},
    {"text": "Clearing demon-infested temples in Ziggurat", "expected_label": "shooter"},
    {"text": "Engaging in helicopter assaults in Project IGI", "expected_label": "shooter"},
    {"text": "Fighting through castles in Darkwatch", "expected_label": "shooter"},
    {"text": "Shooting through enemy defenses in Heavy Fire: Shattered Spear", "expected_label": "shooter"},
    {"text": "Fighting enemies in far-off colonies in Earth Defense Force 4.1", "expected_label": "shooter"},
    {"text": "Sniping from hidden locations in Silent Scope 3", "expected_label": "shooter"},
    {"text": "Taking control of futuristic tanks in Battlezone 98 Redux", "expected_label": "shooter"},
    {"text": "Clearing out criminal hideouts in Narco Terror", "expected_label": "shooter"},
    {"text": "Engaging in fast-paced street battles in Warhammer 40,000: Space Marine", "expected_label": "shooter"},
    {"text": "Participating in dangerous missions in Operation Flashpoint: Dragon Rising", "expected_label": "shooter"},
    {"text": "Shooting through post-apocalyptic wastelands in Dead Effect", "expected_label": "shooter"},
    {"text": "Clearing rooms of enemies in Breach & Clear: Deadline", "expected_label": "shooter"},
    {"text": "Fighting alien robots in Project Eden", "expected_label": "shooter"},
    {"text": "Blasting through chaotic warzones in Battlefield: Bad Company", "expected_label": "shooter"},
    {"text": "Shooting down infected creatures in Fear the Wolves", "expected_label": "shooter"},
    {"text": "Engaging in military-style raids in Insurgency", "expected_label": "shooter"},
    {"text": "Defending against marauding bands in Borderlands: Game of the Year Edition", "expected_label": "shooter"},
    {"text": "Engaging in space combat with laser rifles in Elite Dangerous: Odyssey", "expected_label": "shooter"},
    {"text": "Clearing pirate hideouts in Sea of Thieves", "expected_label": "shooter"},
    {"text": "Shooting mutants in Rage", "expected_label": "shooter"},
    {"text": "Engaging in war against robot overlords in Machine World", "expected_label": "shooter"},
    {"text": "Taking down bandit leaders in Crossfire", "expected_label": "shooter"},
    {"text": "Shooting through enemy-occupied oil rigs in Rainbow Six: Lockdown", "expected_label": "shooter"},
    {"text": "Blasting through alien territories in Alien Rage: Unlimited", "expected_label": "shooter"},
    {"text": "Defending against raiders in Mad Max", "expected_label": "shooter"},
    {"text": "Engaging in stealth-based shootouts in XIII", "expected_label": "shooter"},
    {"text": "Shooting zombies in dark alleys in Dead Rising", "expected_label": "shooter"},
    {"text": "Blasting through military bases in Heavy Fire: Red Shadow", "expected_label": "shooter"},
    {"text": "Fighting extraterrestrial forces in The Red Solstice", "expected_label": "shooter"},
    {"text": "Clearing haunted facilities in Dead Space 3", "expected_label": "shooter"},
    {"text": "Shooting mutant animals in Evolve: Stage 2", "expected_label": "shooter"},
    {"text": "Engaging in tactical squad shootouts in SWAT 3", "expected_label": "shooter"},
    {"text": "Shooting enemy soldiers in H-Hour: World's Elite", "expected_label": "shooter"},
    {"text": "Blasting mutants in a futuristic city in Sin Episodes", "expected_label": "shooter"},
    {"text": "Defending against robots in a cyberpunk world in Ruiner", "expected_label": "shooter"},
    {"text": "Engaging in explosive shootouts in Conflict: Desert Storm", "expected_label": "shooter"},
    {"text": "Fighting rogue AI in Beyond Human", "expected_label": "shooter"},
    {"text": "Shooting rival gang members in The Club", "expected_label": "shooter"},
    {"text": "Clearing out bandit camps in Outlaws of the Old West", "expected_label": "shooter"},
    {"text": "Shooting through wave after wave of enemies in Alien Breed 3: Descent", "expected_label": "shooter"},
    {"text": "Engaging in space station shootouts in Starhawk", "expected_label": "shooter"},
    {"text": "Shooting in alien battle arenas in Loadout", "expected_label": "shooter"},
    {"text": "Defending against marauding mutants in Afterfall: Insanity", "expected_label": "shooter"},
    {"text": "Engaging in city-wide firefights in APB Reloaded", "expected_label": "shooter"},
    {"text": "Shooting through haunted forests in Blair Witch", "expected_label": "shooter"},
    {"text": "Fighting futuristic soldiers in TimeShift", "expected_label": "shooter"},
    {"text": "Engaging in secret agent missions in Alpha Protocol", "expected_label": "shooter"},
    {"text": "Clearing alien vessels in Dark Void", "expected_label": "shooter"},
    {"text": "Blasting through mutant-infested zones in Aftermath", "expected_label": "shooter"},
    {"text": "Fighting through nightmare levels in Dreamkiller", "expected_label": "shooter"},
    {"text": "Engaging in helicopter battles in Heli Heroes", "expected_label": "shooter"},
    {"text": "Taking down rogue knights in Chivalry: Deadliest Warrior", "expected_label": "shooter"},
    {"text": "Blasting away threats in Heavy Fire: Black Arms", "expected_label": "shooter"},
    {"text": "Fighting through abandoned cities in Enlisted", "expected_label": "shooter"},
    {"text": "Engaging in futuristic space battles in Planetside Arena", "expected_label": "shooter"},
    {"text": "Taking cover while dodging bullets in Vanquish", "expected_label": "shooter"},
    {"text": "Fighting intense firefights in Freedom Fighters", "expected_label": "shooter"},
    {"text": "Clearing demonic swarms in Devil May Cry 5's gunfights", "expected_label": "shooter"},
    {"text": "Engaging in tactical battles in Ghost Recon Phantoms", "expected_label": "shooter"},
    {"text": "Firing dual pistols in Wet", "expected_label": "shooter"},
    {"text": "Engaging in brutal skirmishes in Painkiller Overdose", "expected_label": "shooter"},
    {"text": "Shooting through crowded urban environments in Call of Juarez: Gunslinger", "expected_label": "shooter"},
    {"text": "Engaging in mass battles in Tom Clancy's EndWar", "expected_label": "shooter"},
    {"text": "Engaging in chaotic firefights in Bulletstorm: Full Clip Edition", "expected_label": "shooter"},
    {"text": "Participating in large-scale multiplayer battles in Battlecry", "expected_label": "shooter"},
    {"text": "Taking out enemy tanks in Iron Storm", "expected_label": "shooter"},
    {"text": "Engaging in close-quarters firefights in Wet", "expected_label": "shooter"},
    {"text": "Clearing enemy strongholds in Red Faction Guerrilla", "expected_label": "shooter"},
    {"text": "Taking part in skirmishes in Shadowrun", "expected_label": "shooter"},
    {"text": "Defending against waves of mutants in The Walking Dead: Saints & Sinners", "expected_label": "shooter"},
    {"text": "Sniping alien invaders in XCOM 2", "expected_label": "shooter"},
    {"text": "Engaging in fast-paced cyberpunk shootouts in Hard Reset Redux", "expected_label": "shooter"},
    {"text": "Firing heavy artillery in Scavengers", "expected_label": "shooter"},
    {"text": "Surviving in a post-apocalyptic world in Aftermath: The Last Survivor", "expected_label": "shooter"},
    {"text": "Taking control of futuristic weapons in Shogo: Mobile Armor Division", "expected_label": "shooter"},
    {"text": "Clearing rooms full of zombies in Dead Alliance", "expected_label": "shooter"},
    {"text": "Fighting for control in a ravaged wasteland in Hired Ops", "expected_label": "shooter"},
    {"text": "Sniping enemy patrols in Land of the Dead: Road to Fiddler's Green", "expected_label": "shooter"},
    {"text": "Fighting in gladiator-style arenas in Madballs in Babo: Invasion", "expected_label": "shooter"},
    {"text": "Battling pirates in Blood & Gold: Caribbean!", "expected_label": "shooter"},
    {"text": "Surviving in a lawless world in Dead Man's Hand", "expected_label": "shooter"},
    {"text": "Fighting zombie hordes in The Haunted: Hells Reach", "expected_label": "shooter"},
    {"text": "Clearing out enemy fortifications in Resistance 3", "expected_label": "shooter"},
    {"text": "Engaging in firefights in a cyberpunk world in Neotokyo", "expected_label": "shooter"},
    {"text": "Shooting enemies on an alien world in Scorn", "expected_label": "shooter"},
    {"text": "Taking on giant mechs in Front Mission Evolved", "expected_label": "shooter"},
    {"text": "Clearing rooms in a haunted mansion in Rest House", "expected_label": "shooter"},
    {"text": "Fighting off hordes of giant insects in Earth Defense Force 2025", "expected_label": "shooter"},
    {"text": "Engaging in covert operations in Rogue Warrior", "expected_label": "shooter"},
    {"text": "Shooting through enemy-occupied cities in Killzone 2", "expected_label": "shooter"},
    {"text": "Defending against rogue AI in E.Y.E: Divine Cybermancy", "expected_label": "shooter"},
    {"text": "Shooting mutants with explosive rounds in Extermination", "expected_label": "shooter"},
    {"text": "Clearing derelict ships in Warhammer 40,000: Space Hulk Deathwing", "expected_label": "shooter"},
    {"text": "Blasting enemies in a survival arena in Last Man Standing", "expected_label": "shooter"},
    {"text": "Sniping targets from a distance in Silent Scope", "expected_label": "shooter"},
    {"text": "Shooting mutant creatures in Project Warlock", "expected_label": "shooter"},
    {"text": "Engaging in aerial combat in Warbirds 2020", "expected_label": "shooter"},
    {"text": "Fighting rival gangs in GUN", "expected_label": "shooter"},
    {"text": "Participating in a battle royale in Darwin Project", "expected_label": "shooter"},
    {"text": "Engaging in tactical combat in Alliance of Valiant Arms", "expected_label": "shooter"},
    {"text": "Fighting through a dystopian future in Disruptor", "expected_label": "shooter"},
    {"text": "Taking part in modern military engagements in Squad", "expected_label": "shooter"},
    {"text": "Shooting criminals in the Wild West in Outlaws", "expected_label": "shooter"},
    {"text": "Engaging in intense space battles in Star Conflict", "expected_label": "shooter"},
    {"text": "Fighting robotic enemies in Silicon Rising", "expected_label": "shooter"},
    {"text": "Clearing rooms of enemies in Bravo Team", "expected_label": "shooter"},
    {"text": "Shooting hostile creatures in Aliens versus Predator", "expected_label": "shooter"},
    {"text": "Blasting through levels in Battlezone Gold Edition", "expected_label": "shooter"},
    {"text": "Fighting against supernatural beings in Hellforces", "expected_label": "shooter"},
    {"text": "Taking down enemies in firefights in Deus Ex: The Fall", "expected_label": "shooter"},
    {"text": "Participating in sci-fi battles in Space Siege", "expected_label": "shooter"},
    {"text": "Shooting rival bounty hunters in LawBreakers", "expected_label": "shooter"},
    {"text": "Surviving zombie onslaughts in Dead Nation", "expected_label": "shooter"},
    {"text": "Taking out rogue robots in Alien Swarm", "expected_label": "shooter"},
    {"text": "Shooting through fantasy landscapes in NecroVisioN: Lost Company", "expected_label": "shooter"},
    {"text": "Shooting through drug cartel hideouts in Army of Two: The 40th Day", "expected_label": "shooter"},
    {"text": "Fighting mutant hordes in Metro: Last Light Redux", "expected_label": "shooter"},
    {"text": "Taking control of combat drones in Drone Strike Force", "expected_label": "shooter"},
    {"text": "Engaging in mass battles in Halo Wars 2", "expected_label": "shooter"},
    {"text": "Fighting pirates in Sea Dogs: To Each His Own", "expected_label": "shooter"},
    {"text": "Engaging in tactical firefights in XIII", "expected_label": "shooter"},
    {"text": "Taking part in mercenary missions in Soldier of Fortune II", "expected_label": "shooter"},
    {"text": "Shooting rival wizards in SpellForce 3", "expected_label": "shooter"},
    {"text": "Blasting through chaotic environments in Painkiller Redemption", "expected_label": "shooter"},
    {"text": "Clearing out city blocks in Blue Estate", "expected_label": "shooter"},
    {"text": "Surviving onslaughts of robot enemies in Mothergunship", "expected_label": "shooter"},
    {"text": "Shooting zombies in a theme park in Zombie Army 4: Dead War", "expected_label": "shooter"},
    {"text": "Taking on military operations in Operation Flashpoint: Red River", "expected_label": "shooter"},
    {"text": "Fighting against waves of aliens in Alien Breed 2: Assault", "expected_label": "shooter"},
    {"text": "Engaging in military shootouts in Frontlines: Fuel of War", "expected_label": "shooter"},
    {"text": "Blasting away giant insects in Insect Armageddon", "expected_label": "shooter"},
    {"text": "Taking control of advanced armor in Titanfall", "expected_label": "shooter"},
    {"text": "Engaging in survivalist firefights in The Mean Greens", "expected_label": "shooter"},
    {"text": "Fighting other bounty hunters in Hunt Showdown", "expected_label": "shooter"},
    {"text": "Shooting criminals from speeding vehicles in Roadkill", "expected_label": "shooter"},
    {"text": "Shooting through an alien metropolis in The Precursors", "expected_label": "shooter"},
    {"text": "Defending against hordes of the undead in The Brookhaven Experiment", "expected_label": "shooter"},
    {"text": "Shooting through a post-apocalyptic city in Dead Trigger", "expected_label": "shooter"},
    {"text": "Taking part in sci-fi warfare in Red Faction Armageddon", "expected_label": "shooter"},
    {"text": "Shooting robots in a haunted factory in Terminator: Resistance", "expected_label": "shooter"},
    {"text": "Clearing out crime rings in Chinatown Wars", "expected_label": "shooter"},
    {"text": "Shooting mutant creatures in Deep Black", "expected_label": "shooter"},
    {"text": "Participating in futuristic gladiator matches in Mobile Forces", "expected_label": "shooter"},
    {"text": "Defending humanity against synthetic beings in Scavengers", "expected_label": "shooter"},
    {"text": "Shooting enemies in a comic book world in Bedlam", "expected_label": "shooter"},
    {"text": "Clearing enemy fortresses in Battle Carnival", "expected_label": "shooter"},
    {"text": "Taking part in mercenary operations in Rogue Ops", "expected_label": "shooter"},
    {"text": "Engaging in war-torn environments in The Division", "expected_label": "shooter"},
    {"text": "Shooting your way through space battles in Battlestar Galactica Deadlock", "expected_label": "shooter"},
    {"text": "Blasting through alien hives in Prey (2017)", "expected_label": "shooter"},
    {"text": "Defending human settlements in Killzone: Mercenary", "expected_label": "shooter"},
    {"text": "Fighting cyber ninjas in Bright Memory", "expected_label": "shooter"},
    {"text": "Surviving intense battles in Battlefield: Bad Company 2", "expected_label": "shooter"},
    {"text": "Fighting off waves of robots in Robo Recall", "expected_label": "shooter"},
    {"text": "Shooting down alien starships in Space Hulk: Deathwing", "expected_label": "shooter"},
    {"text": "Competing in team-based firefights in Enemy Territory", "expected_label": "shooter"},
    {"text": "Battling crime bosses in Kane & Lynch 2: Dog Days", "expected_label": "shooter"},
    {"text": "Defending against Nazi zombies in Call of Duty: World at War", "expected_label": "shooter"},
    {"text": "Engaging in mech warfare in MechWarrior 5: Mercenaries", "expected_label": "shooter"},
    {"text": "Shooting enemies in a futuristic Tokyo in Tokyo 42", "expected_label": "shooter"},
    {"text": "Navigating urban warfare in The Regiment", "expected_label": "shooter"},
    {"text": "Taking out enemy positions in Medal of Honor: Warfighter", "expected_label": "shooter"},
    {"text": "Fighting through time distortions in TimeShift", "expected_label": "shooter"},
    {"text": "Fighting back an alien occupation in Resistance: Burning Skies", "expected_label": "shooter"},
    {"text": "Participating in a war on drugs in Narcos: Rise of the Cartels", "expected_label": "shooter"},
    {"text": "Clearing zombie-infested areas in Dead Frontier 2", "expected_label": "shooter"},
    {"text": "Fighting supernatural threats in Clive Barker's Jericho", "expected_label": "shooter"},
    {"text": "Blasting away alien forces in Red Faction II", "expected_label": "shooter"},
    {"text": "Fighting in abandoned cities in The Signal From Tölva", "expected_label": "shooter"},
    {"text": "Participating in fast-paced shootouts in Nexuiz", "expected_label": "shooter"},
    {"text": "Fighting intergalactic enemies in Halo 4", "expected_label": "shooter"},
    {"text": "Blasting zombie hordes in Dead Space 3", "expected_label": "shooter"},
    {"text": "Firing plasma weapons in Binary Domain", "expected_label": "shooter"},
    {"text": "Shooting through a cyberpunk city in Ruiner", "expected_label": "shooter"},
    {"text": "Fighting through medieval-style settings in Witchfire", "expected_label": "shooter"},
    {"text": "Shooting through high-tech facilities in Wolfenstein: The Old Blood", "expected_label": "shooter"},
    {"text": "Taking on elite squads in Project IGI: I'm Going In", "expected_label": "shooter"},
    {"text": "Shooting down enemy drones in Drone Swarm", "expected_label": "shooter"},
    {"text": "Engaging in intense shootouts in Call of Juarez", "expected_label": "shooter"},
    {"text": "Defending Earth from invaders in Alien Rage Unlimited", "expected_label": "shooter"},
    {"text": "Taking part in corporate warfare in Syndicate (2012)", "expected_label": "shooter"},
    {"text": "Battling demons in Hellbound", "expected_label": "shooter"},
    {"text": "Fighting in sci-fi environments in Iron Harvest", "expected_label": "shooter"},
    {"text": "Sniping enemies across vast landscapes in Far Cry New Dawn", "expected_label": "shooter"},
    {"text": "Taking out enemies in skyscraper firefights in Battlefield Hardline", "expected_label": "shooter"},
    {"text": "Clearing enemies in a haunted hospital in Fear 2: Project Origin", "expected_label": "shooter"},
    {"text": "Fighting enemies in frozen landscapes in Lost Planet: Extreme Condition", "expected_label": "shooter"},
    {"text": "Participating in combat trials in Rage", "expected_label": "shooter"},
    {"text": "Defending against hordes of creatures in Quarantine Circular", "expected_label": "shooter"},
    {"text": "Blasting alien structures in Red Faction Guerrilla: Re-Mars-tered", "expected_label": "shooter"},
    {"text": "Shooting criminals in gang-ridden cities in APB Reloaded", "expected_label": "shooter"},
    {"text": "Navigating a sci-fi dystopia in Blacklight: Tango Down", "expected_label": "shooter"},
    {"text": "Fighting against massive bosses in Devil's Third", "expected_label": "shooter"},
    {"text": "Participating in the fight against cyborg threats in Terminator: Future Shock","expected_label": "shooter"},
    {"text": "Shooting through paranormal occurrences in Daylight", "expected_label": "shooter"},
    {"text": "Battling rival factions in Brink", "expected_label": "shooter"},
    {"text": "Clearing rooms of aliens in Duke Nukem Forever", "expected_label": "shooter"},
    {"text": "Defending against unknown entities in The Conduit", "expected_label": "shooter"},
    {"text": "Fighting in the jungles of the Congo in Congo", "expected_label": "shooter"},
    {"text": "Taking down corrupt officials in Hatred", "expected_label": "shooter"},
    {"text": "Shooting through ancient Egyptian tombs in Immortal Redneck", "expected_label": "shooter"},
    {"text": "Taking part in intense helicopter gunfights in Thunder Strike", "expected_label": "shooter"},
    {"text": "Defending against waves of zombies in Killing Floor: Incursion", "expected_label": "shooter"},
    {"text": "Blasting enemies in a haunted forest in Betrayer", "expected_label": "shooter"},
    {"text": "Clearing sci-fi labs in Shattered Horizon", "expected_label": "shooter"},
    {"text": "Fighting zombie outbreaks in Nation Red", "expected_label": "shooter"},
    {"text": "Shooting enemies from rooftops in Sniper: Ghost Warrior 3", "expected_label": "shooter"},
    {"text": "Navigating frozen wastelands in Frostbite", "expected_label": "shooter"},
    {"text": "Blasting enemies in chaos-filled arenas in Nitro Family", "expected_label": "shooter"},
    {"text": "Fighting robotic overlords in Hard Reset", "expected_label": "shooter"},
    {"text": "Surviving dystopian battles in Disjunction", "expected_label": "shooter"},
    {"text": "Fighting through monster-infested streets in Afterfall: Insanity", "expected_label": "shooter"},
    {"text": "Shooting gang members in the streets of Chicago in The Punisher", "expected_label": "shooter"},
    {"text": "Defending against aggressive mutant species in Area 51", "expected_label": "shooter"},
    {"text": "Clearing sci-fi towers in Skyhill", "expected_label": "shooter"},
    {"text": "Fighting robot armies in Killzone Mercenary", "expected_label": "shooter"},
    {"text": "Shooting through futuristic levels in MorphX", "expected_label": "shooter"},
    {"text": "Battling for survival in post-apocalyptic Russia in Metro Redux", "expected_label": "shooter"},
    {"text": "Fighting dangerous creatures in Hellgate VR", "expected_label": "shooter"},
    {"text": "Clearing secret bases in Heavy Fire: Afghanistan", "expected_label": "shooter"},
    {"text": "Shooting mutants in abandoned laboratories in Project Eden", "expected_label": "shooter"},
    {"text": "Participating in military operations in ShadowOps: Red Mercury", "expected_label": "shooter"},
    {"text": "Shooting through crime-ridden streets in CrimeCraft", "expected_label": "shooter"},
    {"text": "Taking out enemies in a grimy urban environment in 25 to Life", "expected_label": "shooter"},
    {"text": "Blasting hordes of enemies in the Arctic in Singularity", "expected_label": "shooter"},
    {"text": "Shooting through an underwater complex in Deep Down", "expected_label": "shooter"},
    {"text": "Shooting down enemy aircraft in Attack on Pearl Harbor", "expected_label": "shooter"},
    {"text": "Clearing out alien ships in The Fall of Gods", "expected_label": "shooter"},
    {"text": "Participating in covert operations in The Sniper", "expected_label": "shooter"},
    {"text": "Fighting in an alternate history setting in Resistance: Retribution", "expected_label": "shooter"},
    {"text": "Shooting through robot-infested labs in Neural Uprising", "expected_label": "shooter"},
    {"text": "Engaging in close-quarters combat in Contagion", "expected_label": "shooter"},
    {"text": "Fighting rival crews in Ride or Die", "expected_label": "shooter"},
    {"text": "Surviving post-apocalyptic chaos in Badlands", "expected_label": "shooter"},
    {"text": "Defending against demonic forces in Rage of the Dragons", "expected_label": "shooter"},
    {"text": "Engaging in covert sniper missions in Art of War", "expected_label": "shooter"},
    {"text": "Taking down terrorist cells in Shadow Warrior", "expected_label": "shooter"},
    {"text": "Blasting aliens in Armageddon Riders", "expected_label": "shooter"},
    {"text": "Clearing hordes of infected in Virus Outbreak", "expected_label": "shooter"},
    {"text": "Engaging in fierce urban warfare in Urban Terror", "expected_label": "shooter"},
    {"text": "Defending colonies on Mars in Red Planet Revolution", "expected_label": "shooter"},
    {"text": "Fighting across the Pacific in Battlefield 1943", "expected_label": "shooter"},
    {"text": "Engaging in tactical shootouts in SWAT 3: Close Quarters Battle", "expected_label": "shooter"},
    {"text": "Shooting enemies in chaotic city streets in Urban Chaos", "expected_label": "shooter"},
    {"text": "Hunting down rogue androids in Binary Domain", "expected_label": "shooter"},
    {"text": "Defending against hostile robots in The Surge 2", "expected_label": "shooter"},
    {"text": "Clearing hostile areas in Half-Life: Opposing Force", "expected_label": "shooter"},
    {"text": "Shooting zombies in a western setting in Dead West", "expected_label": "shooter"},
    {"text": "Taking down enemy warlords in Spec Ops: Ranger Elite", "expected_label": "shooter"},
    {"text": "Engaging in brutal firefights in Kill.Switch", "expected_label": "shooter"},
    {"text": "Shooting through futuristic levels in Alien Shooter 2: Reloaded", "expected_label": "shooter"},
    {"text": "Fighting robotic soldiers in Terminator Salvation", "expected_label": "shooter"},
    {"text": "Blasting through infected areas in Contagion VR: Outbreak", "expected_label": "shooter"},
    {"text": "Shooting down space pirates in Starlink: Battle for Atlas", "expected_label": "shooter"},
    {"text": "Engaging in sniper missions in Ghost Recon Phantoms", "expected_label": "shooter"},
    {"text": "Taking part in epic space battles in Void Bastards", "expected_label": "shooter"},
    {"text": "Navigating a cyberpunk city while shooting enemies in Ghostrunner", "expected_label": "shooter"},
    {"text": "Fighting enemy combatants in Warface Breakout", "expected_label": "shooter"},
    {"text": "Blasting through monster-infested areas in Doom 3: Resurrection of Evil", "expected_label": "shooter"},
    {"text": "Engaging in fast-paced action in Unreal Championship 2", "expected_label": "shooter"},
    {"text": "Taking on bounty missions in Star Wars: Bounty Hunter", "expected_label": "shooter"},
    {"text": "Fighting in futuristic arenas in TimeSplitters: Future Perfect", "expected_label": "shooter"},
    {"text": "Clearing alien-infested facilities in Alien Breed 3: Descent", "expected_label": "shooter"},
    {"text": "Coordinating with your team in Valorant", "expected_label": "shooter"},
    {"text": "Competing in fast-paced arena battles in Overwatch", "expected_label": "shooter"},
    {"text": "Navigating dynamic environments in Call of Duty: Warzone", "expected_label": "shooter"},
    {"text": "Clearing post-apocalyptic zones in Metro Exodus", "expected_label": "shooter"},
    {"text": "Fighting robot invaders in Titanfall", "expected_label": "shooter"},
    {"text": "Blasting through hordes of demons in DOOM Eternal", "expected_label": "shooter"},
    {"text": "Defending against waves of mutants in Gears of War", "expected_label": "shooter"},
    {"text": "Leading tactical operations in Rainbow Six Siege", "expected_label": "shooter"},
    {"text": "Taking down targets with precision in Hitman", "expected_label": "shooter"},
    {"text": "Mastering the art of sniping in Sniper Elite", "expected_label": "shooter"},
    {"text": "Fighting for survival in intense matches of PUBG", "expected_label": "shooter"},
    {"text": "Engaging in explosive battles in Battlefield", "expected_label": "shooter"},
    {"text": "Battling aliens in space in Destiny 2", "expected_label": "shooter"},
    {"text": "Surviving chaotic firefights in Counter-Strike", "expected_label": "shooter"},
    {"text": "Firing futuristic weapons in Halo Infinite", "expected_label": "shooter"},
    {"text": "Surviving zombie outbreaks in Left 4 Dead", "expected_label": "shooter"},
    {"text": "Fighting for dominance in futuristic cities in Cyberpunk 2077", "expected_label": "shooter"},
    {"text": "Engaging in sci-fi combat in Warframe", "expected_label": "shooter"}
]